satsolver: src/bitmap.c File Reference
bitmap.c File Reference
#include <stdlib.h>
#include <string.h>
#include "bitmap.h"
#include "util.h"
Functions
void map_init (Map *m, int n)
void map_free (Map *m)
void map_init_clone (Map *t, Map *s)
void map_grow (Map *m, int n)
Function Documentation
void map_init (Map * m, int n)
Definition at line 21 of file bitmap.c.
References _Map::map, sat_calloc(), and _Map::size.
Referenced by addfileprovides_cb(), analyze(), analyze_unsolvable(), findrecommendedsuggested(), pool_addfileprovides_ids(), pool_addfileprovides_search(), pool_calc_duchanges(), pool_create_state_maps(), solvable_trivial_installable_queue(), solvable_trivial_installable_repo(), solver_addchoicerules(), solver_create(), solver_createcleandepsmap(), solver_createdupmaps(), solver_disablechoicerules(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_calculate(), transaction_check_order(), and transaction_create_installedmap().
void map_free (Map * m)
Definition at line 29 of file bitmap.c.
References _Map::map, sat_free(), and _Map::size.
Referenced by analyze(), analyze_unsolvable(), findrecommendedsuggested(), jobtodisablelist(), pool_addfileprovides_ids(), pool_addfileprovides_search(), pool_calc_duchanges(), solvable_trivial_installable_queue(), solvable_trivial_installable_repo(), solver_addchoicerules(), solver_calc_duchanges(), solver_calc_installsizechange(), solver_createcleandepsmap(), solver_free(), solver_freedupmaps(), solver_run_sat(), solver_solve(), solver_trivial_installable(), transaction_add_obsoleted(), transaction_calc_duchanges(), transaction_calc_installsizechange(), transaction_check_order(), and transaction_free().
void map_init_clone (Map * t, Map * s)
Definition at line 37 of file bitmap.c.
References _Map::map, sat_malloc(), and _Map::size.
Referenced by transaction_calculate(), and transaction_init_clone().
void map_grow (Map * m, int n)
Definition at line 51 of file bitmap.c.
References _Map::map, sat_realloc(), and _Map::size.
Referenced by jobtodisablelist(), solver_addduprules(), solver_calculate_noobsmap(), and solver_solve().