satsolver: src/bitmap.h File Reference
bitmap.h File Reference
#include <string.h>
Classes
struct _Map
Defines
#define MAPZERO(m) (memset((m)->map, 0, (m)->size))
#define MAPSET(m, n) ((m)->map[(n) >> 3] |= 1 << ((n) & 7))
#define MAPCLR(m, n) ((m)->map[(n) >> 3] &= ~(1 << ((n) & 7)))
#define MAPTST(m, n) ((m)->map[(n) >> 3] & (1 << ((n) & 7)))
Typedefs
typedef struct _Map Map
Functions
static void map_empty (Map *m)
void map_init (Map *m, int n)
void map_init_clone (Map *t, Map *s)
void map_grow (Map *m, int n)
void map_free (Map *m)
Define Documentation
#define MAPZERO (m) (memset((m)->map, 0, (m)->size))
Definition at line 23 of file bitmap.h.
Referenced by findrecommendedsuggested(), map_empty(), prune_to_recommended(), solver_disablepolicyrules(), and transaction_check_order().
#define MAPSET (m, n) ((m)->map[(n) >> 3] |= 1 << ((n) & 7))
Definition at line 24 of file bitmap.h.
Referenced by addfileprovides_cb(), analyze(), analyze_unsolvable(), disableupdaterule(), findrecommendedsuggested(), jobtodisablelist(), pool_addfileprovides_dep(), pool_addfileprovides_search(), pool_calc_duchanges(), pool_create_state_maps(), prune_to_recommended(), solvable_trivial_installable_queue(), solvable_trivial_installable_repo(), solver_addchoicerules(), solver_addduprules(), solver_addrpmrulesforsolvable(), solver_calculate_noobsmap(), solver_createcleandepsmap(), solver_createdupmaps(), solver_disablechoicerules(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_calculate(), transaction_check_order(), transaction_check_pkg(), and transaction_create_installedmap().
#define MAPCLR (m, n) ((m)->map[(n) >> 3] &= ~(1 << ((n) & 7)))
Definition at line 25 of file bitmap.h.
Referenced by analyze(), jobtodisablelist(), reenableupdaterule(), solver_createcleandepsmap(), solver_createdupmaps(), solver_disablechoicerules(), transaction_calculate(), and transaction_check_order().
#define MAPTST (m, n) ((m)->map[(n) >> 3] & (1 << ((n) & 7)))
Definition at line 26 of file bitmap.h.
Referenced by addduppackages(), addfileprovides_cb(), addsolvableedges(), analyze(), analyze_unsolvable(), analyze_unsolvable_rule(), convertsolution(), create_transaction_info(), dep_possible(), enableweakrules(), findrecommendedsuggested(), jobtodisablelist(), makemultiversionconflict(), makeruledecisions(), pool_addfileprovides_dep(), pool_addfileprovides_search(), pool_calc_duchanges(), pool_calc_installsizechange(), pool_installable(), pool_trivial_installable_noobsoletesmap(), providedbyinstalled(), prune_installed_dup_packages(), prune_to_recommended(), repodata_merge_some_attrs(), solvable_trivial_installable_map(), solver_addchoicerules(), solver_addduprules(), solver_addinfarchrules(), solver_addrpmrulesforsolvable(), solver_addrpmrulesforupdaters(), solver_addrpmrulesforweak(), solver_addupdaterule(), solver_create_decisions_obsoletesmap(), solver_createcleandepsmap(), solver_disablechoicerules(), solver_disablepolicyrules(), solver_printruleclass(), solver_reenablepolicyrules(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_base_type(), transaction_calculate(), transaction_check_pkg(), transaction_create_installedmap(), and transaction_installedresult().
Typedef Documentation
typedef struct _Map Map
Function Documentation
static void map_empty (Map * m) [inline, static]
Definition at line 29 of file bitmap.h.
References MAPZERO.
Referenced by pool_addfileprovides_search(), solver_addchoicerules(), and solver_createcleandepsmap().
void map_init (Map * m, int n)
Definition at line 21 of file bitmap.c.
References _Map::map, sat_calloc(), and _Map::size.
Referenced by addfileprovides_cb(), analyze(), analyze_unsolvable(), findrecommendedsuggested(), pool_addfileprovides_ids(), pool_addfileprovides_search(), pool_calc_duchanges(), pool_create_state_maps(), solvable_trivial_installable_queue(), solvable_trivial_installable_repo(), solver_addchoicerules(), solver_create(), solver_createcleandepsmap(), solver_createdupmaps(), solver_disablechoicerules(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_calculate(), transaction_check_order(), and transaction_create_installedmap().
void map_init_clone (Map * t, Map * s)
Definition at line 37 of file bitmap.c.
References _Map::map, sat_malloc(), and _Map::size.
Referenced by transaction_calculate(), and transaction_init_clone().
void map_grow (Map * m, int n)
Definition at line 51 of file bitmap.c.
References _Map::map, sat_realloc(), and _Map::size.
Referenced by jobtodisablelist(), solver_addduprules(), solver_calculate_noobsmap(), and solver_solve().
void map_free (Map * m)
Definition at line 29 of file bitmap.c.
References _Map::map, sat_free(), and _Map::size.
Referenced by analyze(), analyze_unsolvable(), findrecommendedsuggested(), jobtodisablelist(), pool_addfileprovides_ids(), pool_addfileprovides_search(), pool_calc_duchanges(), solvable_trivial_installable_queue(), solvable_trivial_installable_repo(), solver_addchoicerules(), solver_calc_duchanges(), solver_calc_installsizechange(), solver_createcleandepsmap(), solver_free(), solver_freedupmaps(), solver_run_sat(), solver_solve(), solver_trivial_installable(), transaction_add_obsoleted(), transaction_calc_duchanges(), transaction_calc_installsizechange(), transaction_check_order(), and transaction_free().