satsolver: src/dirpool.h File Reference
dirpool.h File Reference
#include "pooltypes.h"
#include "util.h"
Classes
struct _Dirpool
Typedefs
typedef struct _Dirpool Dirpool
Functions
void dirpool_init (Dirpool *dp)
void dirpool_free (Dirpool *dp)
void dirpool_make_dirtraverse (Dirpool *dp)
Id dirpool_add_dir (Dirpool *dp, Id parent, Id comp, int create)
static Id dirpool_parent (Dirpool *dp, Id did)
static Id dirpool_sibling (Dirpool *dp, Id did)
static Id dirpool_child (Dirpool *dp, Id did)
static void dirpool_free_dirtraverse (Dirpool *dp)
static Id dirpool_compid (Dirpool *dp, Id did)
Typedef Documentation
typedef struct _Dirpool Dirpool
Function Documentation
void dirpool_init (Dirpool * dp)
Definition at line 18 of file dirpool.c.
void dirpool_free (Dirpool * dp)
Definition at line 24 of file dirpool.c.
References _Dirpool::dirs, _Dirpool::dirtraverse, and sat_free().
Referenced by repodata_freedata().
void dirpool_make_dirtraverse (Dirpool * dp)
Definition at line 31 of file dirpool.c.
References DIR_BLOCK, _Dirpool::dirs, _Dirpool::dirtraverse, _Dirpool::ndirs, sat_calloc_block(), and sat_extend_resize().
Referenced by dirpool_add_dir(), dirpool_child(), and dirpool_sibling().
Id dirpool_add_dir (Dirpool * dp, Id parent, Id comp, int create)
Definition at line 50 of file dirpool.c.
References DIR_BLOCK, dirpool_make_dirtraverse(), _Dirpool::dirs, _Dirpool::dirtraverse, _Dirpool::ndirs, sat_extend(), and sat_extend_resize().
Referenced by repodata_str2dir().
static Id dirpool_parent (Dirpool * dp, Id did) [inline, static]
Definition at line 26 of file dirpool.h.
References _Dirpool::dirs.
Referenced by repodata_dir2str().
static Id dirpool_sibling (Dirpool * dp, Id did) [inline, static]
Definition at line 36 of file dirpool.h.
References dirpool_make_dirtraverse(), _Dirpool::dirs, _Dirpool::dirtraverse, and _Dirpool::ndirs.
static Id dirpool_child (Dirpool * dp, Id did) [inline, static]
Definition at line 51 of file dirpool.h.
References dirpool_make_dirtraverse(), and _Dirpool::dirtraverse.
static void dirpool_free_dirtraverse (Dirpool * dp) [inline, static]
Definition at line 59 of file dirpool.h.
References _Dirpool::dirtraverse, and sat_free().
static Id dirpool_compid (Dirpool * dp, Id did) [inline, static]
Definition at line 66 of file dirpool.h.
References _Dirpool::dirs.
Referenced by repodata_dir2str().