satsolver: src/dirpool.c File Reference
dirpool.c File Reference
#include <stdio.h>
#include <string.h>
#include "pool.h"
#include "util.h"
#include "dirpool.h"
Defines
#define DIR_BLOCK 127
Functions
void dirpool_init (Dirpool *dp)
void dirpool_free (Dirpool *dp)
void dirpool_make_dirtraverse (Dirpool *dp)
Id dirpool_add_dir (Dirpool *dp, Id parent, Id comp, int create)
Define Documentation
#define DIR_BLOCK 127
Definition at line 15 of file dirpool.c.
Referenced by dirpool_add_dir(), and dirpool_make_dirtraverse().
Function Documentation
void dirpool_init (Dirpool * dp)
Definition at line 18 of file dirpool.c.
void dirpool_free (Dirpool * dp)
Definition at line 24 of file dirpool.c.
References _Dirpool::dirs, _Dirpool::dirtraverse, and sat_free().
Referenced by repodata_freedata().
void dirpool_make_dirtraverse (Dirpool * dp)
Definition at line 31 of file dirpool.c.
References DIR_BLOCK, _Dirpool::dirs, _Dirpool::dirtraverse, _Dirpool::ndirs, sat_calloc_block(), and sat_extend_resize().
Referenced by dirpool_add_dir(), dirpool_child(), and dirpool_sibling().
Id dirpool_add_dir (Dirpool * dp, Id parent, Id comp, int create)
Definition at line 50 of file dirpool.c.
References DIR_BLOCK, dirpool_make_dirtraverse(), _Dirpool::dirs, _Dirpool::dirtraverse, _Dirpool::ndirs, sat_extend(), and sat_extend_resize().
Referenced by repodata_str2dir().