satsolver: src/evr.h File Reference
evr.h File Reference
#include "pooltypes.h"
Defines
#define EVRCMP_COMPARE 0
#define EVRCMP_MATCH_RELEASE 1
#define EVRCMP_MATCH 2
#define EVRCMP_COMPARE_EVONLY 3
Functions
int vercmp (const char *s1, const char *q1, const char *s2, const char *q2)
int evrcmp_str (const Pool *pool, const char *evr1, const char *evr2, int mode)
int evrcmp (const Pool *pool, Id evr1id, Id evr2id, int mode)
int evrmatch (const Pool *pool, Id evrid, const char *epoch, const char *version, const char *release)
Define Documentation
#define EVRCMP_COMPARE 0
Definition at line 22 of file evr.h.
Referenced by classify_cmp_pkgs(), evrcmp_str(), obsq_sortcmp(), policy_findupdatepackages(), policy_is_illegal(), prune_to_best_version(), and transaction_base_type().
#define EVRCMP_MATCH_RELEASE 1
Definition at line 23 of file evr.h.
#define EVRCMP_MATCH 2
Definition at line 24 of file evr.h.
Referenced by evrcmp_str().
#define EVRCMP_COMPARE_EVONLY 3
Definition at line 25 of file evr.h.
Referenced by evrcmp_str(), and jobtodisablelist().
Function Documentation
int vercmp (const char * s1, const char * q1, const char * s2, const char * q2)
Definition at line 77 of file evr.c.
Referenced by evrcmp_str(), and evrmatch().
int evrcmp_str (const Pool * pool, const char * evr1, const char * evr2, int mode)
Definition at line 141 of file evr.c.
References EVRCMP_COMPARE, EVRCMP_COMPARE_EVONLY, EVRCMP_MATCH, POOL_DEBUG, _Pool::promoteepoch, and vercmp().
Referenced by evrcmp().
int evrcmp (const Pool * pool, Id evr1id, Id evr2id, int mode)
Definition at line 229 of file evr.c.
References evrcmp_str(), and id2str().
Referenced by classify_cmp_pkgs(), jobtodisablelist(), obsq_sortcmp(), policy_findupdatepackages(), policy_is_illegal(), pool_match_flags_evr(), pool_match_nevr_rel(), prune_to_best_version(), and transaction_base_type().
int evrmatch (const Pool * pool, Id evrid, const char * epoch, const char * version, const char * release)
Definition at line 240 of file evr.c.
References id2str(), and vercmp().