satsolver: src/evr.c File Reference
evr.c File Reference
#include <stdio.h>
#include <string.h>
#include "evr.h"
#include "pool.h"
Functions
int vercmp (const char *s1, const char *q1, const char *s2, const char *q2)
int evrcmp_str (const Pool *pool, const char *evr1, const char *evr2, int mode)
int evrcmp (const Pool *pool, Id evr1id, Id evr2id, int mode)
int evrmatch (const Pool *pool, Id evrid, const char *epoch, const char *version, const char *release)
Function Documentation
int vercmp (const char * s1, const char * q1, const char * s2, const char * q2)
Definition at line 77 of file evr.c.
Referenced by evrcmp_str(), and evrmatch().
int evrcmp_str (const Pool * pool, const char * evr1, const char * evr2, int mode)
Definition at line 141 of file evr.c.
References EVRCMP_COMPARE, EVRCMP_COMPARE_EVONLY, EVRCMP_MATCH, POOL_DEBUG, _Pool::promoteepoch, and vercmp().
Referenced by evrcmp().
int evrcmp (const Pool * pool, Id evr1id, Id evr2id, int mode)
Definition at line 229 of file evr.c.
References evrcmp_str(), and id2str().
Referenced by classify_cmp_pkgs(), jobtodisablelist(), obsq_sortcmp(), policy_findupdatepackages(), policy_is_illegal(), pool_match_flags_evr(), pool_match_nevr_rel(), prune_to_best_version(), and transaction_base_type().
int evrmatch (const Pool * pool, Id evrid, const char * epoch, const char * version, const char * release)
Definition at line 240 of file evr.c.
References id2str(), and vercmp().