satsolver: src/hash.h File Reference
hash.h File Reference
#include "pooltypes.h"
Defines
#define HASHCHAIN_START 7
#define HASHCHAIN_NEXT(h, hh, mask) (((h) + (hh)++) & (mask))
Typedefs
typedef unsigned int Hashval
typedef unsigned int Hashmask
typedef Id * Hashtable
Functions
static Hashval strhash (const char *str)
static Hashval strnhash (const char *str, unsigned len)
static Hashval strhash_cont (const char *str, Hashval r)
static Hashval relhash (Id name, Id evr, int flags)
static Hashmask mkmask (unsigned int num)
Define Documentation
#define HASHCHAIN_START 7
Definition at line 28 of file hash.h.
#define HASHCHAIN_NEXT (h, hh, mask) (((h) + (hh)++) & (mask))
Definition at line 29 of file hash.h.
Referenced by rel2id(), repo_add_solv_flags(), and stringpool_strn2id().
Typedef Documentation
typedef unsigned int Hashval
Definition at line 19 of file hash.h.
typedef unsigned int Hashmask
Definition at line 22 of file hash.h.
typedef Id* Hashtable
Definition at line 25 of file hash.h.
Function Documentation
static Hashval strhash (const char * str) [inline, static]
Definition at line 35 of file hash.h.
Referenced by repo_add_solv_flags(), and stringpool_strn2id().
static Hashval strnhash (const char * str, unsigned len) [inline, static]
Definition at line 45 of file hash.h.
Referenced by stringpool_strn2id().
static Hashval strhash_cont (const char * str, Hashval r) [inline, static]
Definition at line 55 of file hash.h.
static Hashval relhash (Id name, Id evr, int flags) [inline, static]
Definition at line 68 of file hash.h.
Referenced by rel2id(), and repo_add_solv_flags().
static Hashmask mkmask (unsigned int num) [inline, static]
Definition at line 80 of file hash.h.
Referenced by rel2id(), repo_add_solv_flags(), and stringpool_strn2id().