satsolver: src/md5.h File Reference
md5.h File Reference
Classes
struct MD5_CTX
Typedefs
typedef unsigned long MD5_u32plus
Functions
void sat_MD5_Init (MD5_CTX *ctx)
void sat_MD5_Update (MD5_CTX *ctx, void *data, unsigned long size)
void sat_MD5_Final (unsigned char *result, MD5_CTX *ctx)
Typedef Documentation
typedef unsigned long MD5_u32plus
Definition at line 10 of file md5.h.
Function Documentation
void sat_MD5_Init (MD5_CTX * ctx)
Definition at line 176 of file md5.c.
References MD5_CTX::a, MD5_CTX::b, MD5_CTX::c, MD5_CTX::d, MD5_CTX::hi, and MD5_CTX::lo.
Referenced by sat_chksum_create().
void sat_MD5_Update (MD5_CTX * ctx, void * data, unsigned long size)
Definition at line 187 of file md5.c.
References body(), MD5_CTX::buffer, MD5_CTX::hi, and MD5_CTX::lo.
Referenced by sat_chksum_add().
void sat_MD5_Final (unsigned char * result, MD5_CTX * ctx)
Definition at line 221 of file md5.c.
References MD5_CTX::a, MD5_CTX::b, body(), MD5_CTX::buffer, MD5_CTX::c, MD5_CTX::d, MD5_CTX::hi, and MD5_CTX::lo.
Referenced by sat_chksum_get().