satsolver: src/policy.h File Reference
policy.h File Reference
#include "solver.h"
Defines
#define POLICY_MODE_CHOOSE 0
#define POLICY_MODE_RECOMMEND 1
#define POLICY_MODE_SUGGEST 2
#define POLICY_ILLEGAL_DOWNGRADE 1
#define POLICY_ILLEGAL_ARCHCHANGE 2
#define POLICY_ILLEGAL_VENDORCHANGE 4
Functions
void prune_best_arch_name_version (const Solver *solv, Pool *pool, Queue *plist)
void prune_to_best_arch (const Pool *pool, Queue *plist)
void prune_to_best_version (Pool *pool, Queue *plist)
void policy_filter_unwanted (Solver *solv, Queue *plist, int mode)
int policy_illegal_archchange (Solver *solv, Solvable *s1, Solvable *s2)
int policy_illegal_vendorchange (Solver *solv, Solvable *s1, Solvable *s2)
int policy_is_illegal (Solver *solv, Solvable *s1, Solvable *s2, int ignore)
void policy_findupdatepackages (Solver *solv, Solvable *s, Queue *qs, int allowall)
void policy_create_obsolete_index (Solver *solv)
Define Documentation
#define POLICY_MODE_CHOOSE 0
Definition at line 15 of file policy.h.
Referenced by policy_filter_unwanted(), selectandinstall(), and solver_run_sat().
#define POLICY_MODE_RECOMMEND 1
Definition at line 16 of file policy.h.
Referenced by solver_run_sat().
#define POLICY_MODE_SUGGEST 2
Definition at line 17 of file policy.h.
Referenced by findrecommendedsuggested(), and policy_filter_unwanted().
#define POLICY_ILLEGAL_DOWNGRADE 1
Definition at line 60 of file policy.h.
Referenced by jobtodisablelist(), policy_is_illegal(), and solver_printsolution().
#define POLICY_ILLEGAL_ARCHCHANGE 2
Definition at line 61 of file policy.h.
Referenced by policy_is_illegal(), and solver_printsolution().
#define POLICY_ILLEGAL_VENDORCHANGE 4
Definition at line 62 of file policy.h.
Referenced by policy_is_illegal(), and solver_printsolution().
Function Documentation
void prune_best_arch_name_version (const Solver * solv, Pool * pool, Queue * plist)
Definition at line 409 of file policy.c.
References _Solver::bestSolvableCb, _Queue::count, _Solver::pool, prune_to_best_arch(), and prune_to_best_version().
Referenced by policy_filter_unwanted().
void prune_to_best_arch (const Pool * pool, Queue * plist)
Definition at line 263 of file policy.c.
References _Solvable::arch, _Queue::count, _Queue::elements, _Pool::id2arch, _Pool::lastarch, and _Pool::solvables.
Referenced by prune_best_arch_name_version().
void prune_to_best_version (Pool * pool, Queue * plist)
Definition at line 352 of file policy.c.
References _Queue::count, _Queue::elements, _Solvable::evr, evrcmp(), EVRCMP_COMPARE, _Pool::installed, _Solvable::name, POOL_DEBUG, prune_obsoleted(), prune_to_best_version_sortcmp(), _Solvable::repo, SAT_DEBUG_POLICY, sat_sort(), solvable2str(), and _Pool::solvables.
Referenced by prune_best_arch_name_version().
void policy_filter_unwanted (Solver * solv, Queue * plist, int mode)
Definition at line 457 of file policy.c.
References _Queue::count, _Solver::dupinvolvedmap, _Solver::dupmap_all, _Pool::installed, POLICY_MODE_CHOOSE, POLICY_MODE_SUGGEST, _Solver::pool, prune_best_arch_name_version(), prune_installed_dup_packages(), prune_to_highest_prio(), prune_to_highest_prio_per_name(), prune_to_recommended(), and _Map::size.
Referenced by findrecommendedsuggested(), selectandinstall(), and solver_run_sat().
int policy_illegal_archchange (Solver * solv, Solvable * s1, Solvable * s2)
Definition at line 478 of file policy.c.
References _Solvable::arch, _Solver::archCheckCb, _Pool::id2arch, _Pool::lastarch, and _Solver::pool.
Referenced by policy_findupdatepackages(), and policy_is_illegal().
int policy_illegal_vendorchange (Solver * solv, Solvable * s1, Solvable * s2)
Definition at line 506 of file policy.c.
References _Solver::pool, pool_vendor2mask(), _Solvable::vendor, and _Solver::vendorCheckCb.
Referenced by policy_findupdatepackages(), and policy_is_illegal().
int policy_is_illegal (Solver * solv, Solvable * s1, Solvable * s2, int ignore)
Definition at line 534 of file policy.c.
References _Solver::allowarchchange, _Solver::allowdowngrade, _Solver::allowvendorchange, _Solvable::arch, _Solvable::evr, evrcmp(), EVRCMP_COMPARE, _Solvable::name, policy_illegal_archchange(), POLICY_ILLEGAL_ARCHCHANGE, POLICY_ILLEGAL_DOWNGRADE, policy_illegal_vendorchange(), POLICY_ILLEGAL_VENDORCHANGE, _Solver::pool, and _Solvable::vendor.
Referenced by jobtodisablelist(), solver_addchoicerules(), and solver_printsolution().
void policy_findupdatepackages (Solver * solv, Solvable * s, Queue * qs, int allowall)
Definition at line 649 of file policy.c.
References _Solver::allowarchchange, _Solver::allowdowngrade, _Solver::allowvendorchange, _Solvable::arch, _Solvable::evr, evrcmp(), EVRCMP_COMPARE, FOR_PROVIDES, _Repo::idarraydata, _Solver::installed, _Solvable::name, _Solver::noupdateprovide, _Solver::obsoletes, _Solvable::obsoletes, _Solver::obsoletes_data, _Pool::obsoleteusescolors, _Pool::obsoleteusesprovides, policy_illegal_archchange(), policy_illegal_vendorchange(), _Solver::pool, pool_colormatch(), pool_match_nevr(), queue_empty(), queue_push(), _Solvable::repo, _Pool::solvables, _Repo::start, _Solver::updateCandidateCb, and _Solvable::vendor.
Referenced by addduppackages(), finddistupgradepackages(), solver_addrpmrulesforupdaters(), and solver_addupdaterule().
void policy_create_obsolete_index (Solver * solv)
Definition at line 565 of file policy.c.
References _Repo::end, FOR_PROVIDES, _Repo::idarraydata, _Solver::installed, _Solvable::name, _Pool::nsolvables, _Solvable::obsoletes, _Solver::obsoletes, _Solver::obsoletes_data, _Pool::obsoleteusescolors, _Pool::obsoleteusesprovides, _Solver::pool, pool_colormatch(), POOL_DEBUG, pool_installable(), pool_match_nevr(), _Solvable::repo, sat_calloc(), SAT_DEBUG_STATS, _Pool::solvables, and _Repo::start.
Referenced by solver_solve().