satsolver: src/poolid.c File Reference
poolid.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "pool.h"
#include "poolid.h"
#include "poolid_private.h"
#include "util.h"
Functions
Id str2id (Pool *pool, const char *str, int create)
Id strn2id (Pool *pool, const char *str, unsigned int len, int create)
Id rel2id (Pool *pool, Id name, Id evr, int flags, int create)
const char * id2str (const Pool *pool, Id id)
const char * id2rel (const Pool *pool, Id id)
const char * id2evr (const Pool *pool, Id id)
static int dep2strlen (const Pool *pool, Id id)
static void dep2strcpy (const Pool *pool, char *p, Id id, int oldrel)
const char * dep2str (Pool *pool, Id id)
void pool_shrink_strings (Pool *pool)
void pool_shrink_rels (Pool *pool)
void pool_freeidhashes (Pool *pool)
Variables
static const char * rels []
Function Documentation
Id str2id (Pool * pool, const char * str, int create)
Definition at line 27 of file poolid.c.
References _Stringpool::nstrings, sat_realloc(), _Pool::ss, stringpool_str2id(), _Pool::whatprovides, and WHATPROVIDES_BLOCK.
Referenced by pool_id2langid(), repo_add_solv_flags(), repo_fix_conflicts(), repo_fix_supplements(), repodata_add_poolstr_array(), repodata_globalize_id(), and repodata_set_poolstr().
Id strn2id (Pool * pool, const char * str, unsigned int len, int create)
Definition at line 41 of file poolid.c.
References _Stringpool::nstrings, sat_realloc(), _Pool::ss, stringpool_strn2id(), _Pool::whatprovides, and WHATPROVIDES_BLOCK.
Referenced by pool_setarch(), and repodata_str2dir().
Id rel2id (Pool * pool, Id name, Id evr, int flags, int create)
Definition at line 55 of file poolid.c.
References _Reldep::evr, _Reldep::flags, HASHCHAIN_NEXT, MAKERELDEP, mkmask(), _Reldep::name, _Pool::nrels, REL_BLOCK, relhash(), _Pool::relhashmask, _Pool::relhashtbl, _Pool::rels, sat_calloc(), sat_extend(), sat_free(), sat_realloc2(), WHATPROVIDES_BLOCK, and _Pool::whatprovides_rel.
Referenced by pool_add_fileconflicts_deps(), repo_fix_conflicts(), repo_fix_supplements(), and solvable_selfprovidedep().
const char* id2str (const Pool * pool, Id id)
Definition at line 124 of file poolid.c.
References GETRELDEP, ISRELDEP, _Reldep::name, _Pool::ss, _Stringpool::strings, and _Stringpool::stringspace.
Referenced by classify_cmp(), classify_cmp_pkgs(), evrcmp(), evrid2vrstr(), evrmatch(), havescripts(), id2strnone(), jobtodisablelist(), obsq_sortcmp(), pool_addfileprovides_dep(), pool_addfileprovides_ids(), pool_addfileprovides_search(), pool_addrelproviders(), pool_arch2color_slow(), pool_id2langid(), pool_trivial_installable_noobsoletesmap(), pool_vendor2mask(), prune_to_best_version_sortcmp(), repo_add_solv_flags(), repo_fix_conflicts(), repo_fix_supplements(), repo_lookup_str(), repodata_internalize(), repodata_lookup_str(), repodata_serialize_key(), repodata_set_location(), repodata_stringify(), solvable2str(), solvable_get_location(), solver_addrpmrulesforsolvable(), solver_fill_DU_cb(), solver_printsolution(), solver_printtransaction(), solver_printtrivial(), transaction_calculate(), transaction_check_pkg(), and transaction_type().
const char* id2rel (const Pool * pool, Id id)
Definition at line 158 of file poolid.c.
References _Reldep::flags, GETRELDEP, ISRELDEP, REL_AND, REL_ARCH, REL_FILECONFLICT, REL_NAMESPACE, REL_OR, REL_WITH, and rels.
Referenced by dep2strcpy(), and dep2strlen().
const char* id2evr (const Pool * pool, Id id)
Definition at line 191 of file poolid.c.
References _Reldep::evr, GETRELDEP, ISRELDEP, _Pool::ss, _Stringpool::strings, and _Stringpool::stringspace.
static int dep2strlen (const Pool * pool, Id id) [static]
Definition at line 203 of file poolid.c.
References _Reldep::evr, GETRELDEP, id2rel(), ISRELDEP, _Reldep::name, _Pool::ss, _Stringpool::strings, and _Stringpool::stringspace.
Referenced by dep2str().
static void dep2strcpy (const Pool * pool, char * p, Id id, int oldrel) [static]
Definition at line 218 of file poolid.c.
References _Reldep::evr, _Reldep::flags, GETRELDEP, id2rel(), ISRELDEP, _Reldep::name, REL_AND, REL_FILECONFLICT, REL_NAMESPACE, REL_OR, REL_WITH, _Pool::ss, _Stringpool::strings, and _Stringpool::stringspace.
Referenced by dep2str().
const char* dep2str (Pool * pool, Id id)
Definition at line 259 of file poolid.c.
References dep2strcpy(), dep2strlen(), ISRELDEP, pool_alloctmpspace(), _Pool::ss, _Stringpool::strings, and _Stringpool::stringspace.
Referenced by addsolvableedges(), pool_addrelproviders(), repo_add_solv_flags(), solver_addrpmrulesforsolvable(), solver_printproblemruleinfo(), solver_select2str(), and transaction_check_pkg().
void pool_shrink_strings (Pool * pool)
Definition at line 270 of file poolid.c.
References _Pool::ss, and stringpool_shrink().
Referenced by repo_add_solv_flags().
void pool_shrink_rels (Pool * pool)
Definition at line 276 of file poolid.c.
References _Pool::nrels, REL_BLOCK, _Pool::rels, and sat_extend_resize().
Referenced by repo_add_solv_flags().
void pool_freeidhashes (Pool * pool)
Definition at line 284 of file poolid.c.
References _Pool::relhashmask, _Pool::relhashtbl, sat_free(), _Pool::ss, and stringpool_freehash().
Referenced by pool_add_fileconflicts_deps(), pool_createwhatprovides(), pool_free(), and repo_add_solv_flags().
Variable Documentation
const char* rels[] [static]
Initial value:
 {
  " ! ",
  " > ",
  " = ",
  " >= ",
  " < ",
  " <> ",
  " <= ",
  " <=> "
}
Definition at line 136 of file poolid.c.
Referenced by id2rel().