satsolver: src/poolarch.h File Reference
poolarch.h File Reference
#include "pool.h"
Defines
#define ARCHCOLOR_32 1
#define ARCHCOLOR_64 2
#define ARCHCOLOR_ALL 255
Functions
void pool_setarch (Pool *, const char *)
unsigned char pool_arch2color_slow (Pool *pool, Id arch)
static unsigned char pool_arch2color (Pool *pool, Id arch)
static int pool_colormatch (Pool *pool, Solvable *s1, Solvable *s2)
Define Documentation
#define ARCHCOLOR_32 1
Definition at line 16 of file poolarch.h.
#define ARCHCOLOR_64 2
Definition at line 17 of file poolarch.h.
#define ARCHCOLOR_ALL 255
Definition at line 18 of file poolarch.h.
Function Documentation
void pool_setarch (Pool * , const char *)
Definition at line 55 of file poolarch.c.
References archpolicies, _Pool::id2arch, _Pool::id2color, _Pool::lastarch, sat_calloc(), sat_free(), sat_realloc(), and strn2id().
unsigned char pool_arch2color_slow (Pool * pool, Id arch)
Definition at line 118 of file poolarch.c.
References _Pool::id2color, id2str(), _Pool::lastarch, and sat_calloc().
Referenced by pool_arch2color().
static unsigned char pool_arch2color (Pool * pool, Id arch) [inline, static]
Definition at line 20 of file poolarch.h.
References _Pool::id2color, _Pool::lastarch, and pool_arch2color_slow().
Referenced by pool_colormatch().
static int pool_colormatch (Pool * pool, Solvable * s1, Solvable * s2) [inline, static]
Definition at line 29 of file poolarch.h.
References _Solvable::arch, and pool_arch2color().
Referenced by create_transaction_info(), jobtodisablelist(), policy_create_obsolete_index(), policy_findupdatepackages(), prune_obsoleted(), solver_addchoicerules(), solver_addrpmrulesforsolvable(), solver_create_decisions_obsoletesmap(), and solver_createdupmaps().