satsolver: src/poolarch.c File Reference
poolarch.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pool.h"
#include "poolid.h"
#include "poolarch.h"
#include "util.h"
Functions
void pool_setarch (Pool *pool, const char *arch)
unsigned char pool_arch2color_slow (Pool *pool, Id arch)
Variables
const char * archpolicies []
Function Documentation
void pool_setarch (Pool * pool, const char * arch)
Definition at line 55 of file poolarch.c.
References archpolicies, _Pool::id2arch, _Pool::id2color, _Pool::lastarch, sat_calloc(), sat_free(), sat_realloc(), and strn2id().
unsigned char pool_arch2color_slow (Pool * pool, Id arch)
Definition at line 118 of file poolarch.c.
References _Pool::id2color, id2str(), _Pool::lastarch, and sat_calloc().
Referenced by pool_arch2color().
Variable Documentation
const char* archpolicies[]
Initial value:
 {
  "x86_64",     "x86_64:i686:i586:i486:i386",
  "i686",       "i686:i586:i486:i386",
  "i586",       "i586:i486:i386",
  "i486",       "i486:i386",
  "i386",       "i386",
  "s390x",      "s390x:s390",
  "s390",       "s390",
  "ia64",       "ia64:i686:i586:i486:i386",
  "ppc64",      "ppc64:ppc",
  "ppc",        "ppc",
  "armv7l",     "armv7l:armv6l:armv5tejl:armv5tel:armv5l:armv4tl:armv4l:armv3l",
  "armv6l",     "armv6l:armv5tejl:armv5tel:armv5l:armv4tl:armv4l:armv3l",
  "armv5tejl",  "armv5tejl:armv5tel:armv5l:armv4tl:armv4l:armv3l",
  "armv5tel",   "armv5tel:armv5l:armv4tl:armv4l:armv3l",
  "armv5l",     "armv5l:armv4tl:armv4l:armv3l",
  "armv4tl",    "armv4tl:armv4l:armv3l",
  "armv4l",     "armv4l:armv3l",
  "armv3l",     "armv3l",
  "sh3",        "sh3",
  "sh4",        "sh4",
  "sh4a",       "sh4a:sh4",
  "sparc64v",   "sparc64v:sparc64:sparcv9v:sparcv9:sparcv8:sparc",
  "sparc64",    "sparc64:sparcv9:sparcv8:sparc",
  "sparcv9v",   "sparcv9v:sparcv9:sparcv8:sparc",
  "sparcv9",    "sparcv9:sparcv8:sparc",
  "sparcv8",    "sparcv8:sparc",
  "sparc",      "sparc",
  0
}
Definition at line 23 of file poolarch.c.
Referenced by pool_setarch().