satsolver: src/poolvendor.c File Reference
poolvendor.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fnmatch.h>
#include "pool.h"
#include "poolid.h"
#include "poolvendor.h"
#include "util.h"
Functions
Id pool_vendor2mask (Pool *pool, Id vendor)
Variables
const char * vendors []
Function Documentation
Id pool_vendor2mask (Pool * pool, Id vendor)
Definition at line 38 of file poolvendor.c.
References _Queue::count, _Queue::elements, id2str(), queue_push(), _Pool::vendormap, and vendors.
Referenced by policy_illegal_vendorchange().
Variable Documentation
const char* vendors[]
Initial value:
 {
  "!openSUSE Build Service*",
  "SUSE*",
  "openSUSE*",
  "SGI*",
  "Novell*",
  "Silicon Graphics*",
  "Jpackage Project*",
  "ATI Technologies Inc.*",
  "Nvidia*",
  0,
  0,
}
Definition at line 24 of file poolvendor.c.
Referenced by pool_vendor2mask().