satsolver: src/problems.h File Reference
problems.h File Reference
Defines
#define SOLVER_SOLUTION_JOB (0)
#define SOLVER_SOLUTION_DISTUPGRADE (-1)
#define SOLVER_SOLUTION_INFARCH (-2)
Functions
void solver_disableproblem (struct _Solver *solv, Id v)
void solver_enableproblem (struct _Solver *solv, Id v)
int solver_prepare_solutions (struct _Solver *solv)
unsigned int solver_problem_count (struct _Solver *solv)
Id solver_next_problem (struct _Solver *solv, Id problem)
unsigned int solver_solution_count (struct _Solver *solv, Id problem)
Id solver_next_solution (struct _Solver *solv, Id problem, Id solution)
unsigned int solver_solutionelement_count (struct _Solver *solv, Id problem, Id solution)
Id solver_next_solutionelement (struct _Solver *solv, Id problem, Id solution, Id element, Id *p, Id *rp)
void solver_take_solutionelement (struct _Solver *solv, Id p, Id rp, Queue *job)
void solver_take_solution (struct _Solver *solv, Id problem, Id solution, Queue *job)
Id solver_findproblemrule (struct _Solver *solv, Id problem)
void solver_findallproblemrules (struct _Solver *solv, Id problem, Queue *rules)
Define Documentation
#define SOLVER_SOLUTION_JOB (0)
Definition at line 23 of file problems.h.
Referenced by solver_printsolution(), and solver_take_solutionelement().
#define SOLVER_SOLUTION_DISTUPGRADE (-1)
Definition at line 24 of file problems.h.
Referenced by convertsolution(), and solver_printsolution().
#define SOLVER_SOLUTION_INFARCH (-2)
Definition at line 25 of file problems.h.
Referenced by convertsolution(), and solver_printsolution().
Function Documentation
void solver_disableproblem (struct _Solver * solv, Id v)
Definition at line 35 of file problems.c.
References _Solver::duprules, _Solver::duprules_end, _Queue::elements, _Solver::featurerules, _Solver::infarchrules, _Solver::infarchrules_end, _Solver::jobrules, _Solvable::name, _Rule::p, _Solver::pool, _Solver::rules, _Solver::ruletojob, _Pool::solvables, solver_disablerule(), solver_enablerule(), and _Solver::updaterules.
Referenced by analyze_unsolvable(), makeruledecisions(), and refine_suggestion().
void solver_enableproblem (struct _Solver * solv, Id v)
Definition at line 88 of file problems.c.
References _Rule::d, _Solver::duprules, _Solver::duprules_end, _Queue::elements, _Solver::featurerules, _Solver::infarchrules, _Solver::infarchrules_end, _Solver::jobrules, _Solvable::name, _Rule::p, _Solver::pool, _Solver::rules, _Solver::ruletojob, _Pool::solvables, solver_disablerule(), solver_enablerule(), and _Solver::updaterules.
Referenced by refine_suggestion().
int solver_prepare_solutions (struct _Solver * solv)
Definition at line 480 of file problems.c.
References _Queue::count, _Queue::elements, _Solver::problems, queue_push(), and _Solver::solutions.
Referenced by solver_solve().
unsigned int solver_problem_count (struct _Solver * solv)
Definition at line 630 of file problems.c.
References _Queue::count, and _Solver::problems.
Id solver_next_problem (struct _Solver * solv, Id problem)
Definition at line 636 of file problems.c.
References _Queue::count, and _Solver::problems.
Referenced by solver_printallsolutions().
unsigned int solver_solution_count (struct _Solver * solv, Id problem)
Definition at line 644 of file problems.c.
References create_solutions(), _Queue::elements, _Solver::problems, and _Solver::solutions.
Id solver_next_solution (struct _Solver * solv, Id problem, Id solution)
Definition at line 653 of file problems.c.
References create_solutions(), _Queue::elements, _Solver::problems, and _Solver::solutions.
Referenced by solver_printallsolutions().
unsigned int solver_solutionelement_count (struct _Solver * solv, Id problem, Id solution)
Definition at line 662 of file problems.c.
References _Queue::elements, _Solver::problems, and _Solver::solutions.
Id solver_next_solutionelement (struct _Solver * solv, Id problem, Id solution, Id element, Id * p, Id * rp)
Definition at line 695 of file problems.c.
References _Queue::elements, _Solver::problems, and _Solver::solutions.
Referenced by solver_printsolution(), and solver_take_solution().
void solver_take_solutionelement (struct _Solver * solv, Id p, Id rp, Queue * job)
Definition at line 710 of file problems.c.
References _Queue::count, _Queue::elements, queue_push2(), SOLVER_ERASE, SOLVER_INSTALL, and SOLVER_SOLUTION_JOB.
Referenced by solver_take_solution().
void solver_take_solution (struct _Solver * solv, Id problem, Id solution, Queue * job)
Definition at line 736 of file problems.c.
References solver_next_solutionelement(), and solver_take_solutionelement().
Id solver_findproblemrule (struct _Solver * solv, Id problem)
Definition at line 851 of file problems.c.
References _Queue::elements, findproblemrule_internal(), and _Solver::problems.
Referenced by solver_printprobleminfo().
void solver_findallproblemrules (struct _Solver * solv, Id problem, Queue * rules)
Definition at line 894 of file problems.c.
References _Queue::elements, findallproblemrules_internal(), _Solver::problems, and queue_empty().
Referenced by solver_printcompleteprobleminfo().