satsolver: src/queue.h File Reference
queue.h File Reference
#include "pooltypes.h"
Classes
struct _Queue
Typedefs
typedef struct _Queue Queue
Functions
void queue_alloc_one (Queue *q)
void queue_alloc_one_head (Queue *q)
static void queue_empty (Queue *q)
static Id queue_shift (Queue *q)
static Id queue_pop (Queue *q)
static void queue_unshift (Queue *q, Id id)
static void queue_push (Queue *q, Id id)
static void queue_pushunique (Queue *q, Id id)
static void queue_push2 (Queue *q, Id id1, Id id2)
static void queue_truncate (Queue *q, int n)
void queue_init (Queue *q)
void queue_init_buffer (Queue *q, Id *buf, int size)
void queue_init_clone (Queue *t, Queue *s)
void queue_free (Queue *q)
void queue_insert (Queue *q, int pos, Id id)
void queue_insert2 (Queue *q, int pos, Id id1, Id id2)
void queue_insertn (Queue *q, int pos, int n)
void queue_delete (Queue *q, int pos)
void queue_delete2 (Queue *q, int pos)
void queue_deleten (Queue *q, int pos, int n)
Typedef Documentation
typedef struct _Queue Queue
Function Documentation
void queue_alloc_one (Queue * q)
Definition at line 64 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE, _Queue::left, sat_malloc2(), and sat_realloc2().
Referenced by queue_alloc_one_head(), queue_insertn(), and queue_push().
void queue_alloc_one_head (Queue * q)
Definition at line 91 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE_HEAD, _Queue::left, and queue_alloc_one().
Referenced by queue_unshift().
static void queue_empty (Queue * q) [inline, static]
Definition at line 31 of file queue.h.
References _Queue::alloc, _Queue::count, _Queue::elements, and _Queue::left.
Referenced by addcycleedges(), addsolvableedges(), create_solutions(), create_transaction_info(), dump_tes(), policy_findupdatepackages(), prune_to_highest_prio_per_name(), refine_suggestion(), removedisabledconflicts(), repodata_lookup_idarray(), solvable_lookup_idarray(), solver_addchoicerules(), solver_addinfarchrules(), solver_allruleinfos(), solver_findallproblemrules(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_all_obs_pkgs(), transaction_calculate(), transaction_classify(), transaction_classify_pkgs(), transaction_installedresult(), and transaction_order().
static Id queue_shift (Queue * q) [inline, static]
Definition at line 44 of file queue.h.
References _Queue::count, and _Queue::elements.
Referenced by solver_addrpmrulesforsolvable(), solver_addupdaterule(), solver_allruleinfos(), solver_createcleandepsmap(), solver_solve(), and transaction_order().
static Id queue_pop (Queue * q) [inline, static]
Definition at line 53 of file queue.h.
References _Queue::count, _Queue::elements, and _Queue::left.
Referenced by addcycleedges(), and transaction_order().
static void queue_unshift (Queue * q, Id id) [inline, static]
Definition at line 62 of file queue.h.
References _Queue::alloc, _Queue::count, _Queue::elements, and queue_alloc_one_head().
Referenced by transaction_classify().
static void queue_push (Queue * q, Id id) [inline, static]
Definition at line 71 of file queue.h.
References _Queue::count, _Queue::elements, _Queue::left, and queue_alloc_one().
Referenced by addcycleedges(), addrpmruleinfo(), analyze(), analyze_unsolvable(), analyze_unsolvable_rule(), breakcycle(), convertsolution(), create_solutions(), create_transaction_info(), findrecommendedsuggested(), makemultiversionconflict(), makeruledecisions(), policy_findupdatepackages(), pool_addrelproviders(), pool_vendor2mask(), propagate(), prune_to_highest_prio_per_name(), queue_insert(), queue_insert2(), queue_push2(), queue_pushunique(), refine_suggestion(), removedisabledconflicts(), repodata_lookup_idarray(), selectandinstall(), setpropagatelearn(), solvable_lookup_idarray(), solver_addchoicerules(), solver_addinfarchrules(), solver_addjobrule(), solver_addrpmrulesforsolvable(), solver_addupdaterule(), solver_allruleinfos(), solver_createcleandepsmap(), solver_prepare_solutions(), solver_printtrivial(), solver_ruleinfo(), solver_run_sat(), solver_solve(), transaction_all_obs_pkgs(), transaction_calculate(), transaction_classify(), transaction_classify_pkgs(), transaction_installedresult(), transaction_order(), transaction_order_add_choices(), and weaken_solvable_deps().
static void queue_pushunique (Queue * q, Id id) [inline, static]
Definition at line 80 of file queue.h.
References _Queue::count, _Queue::elements, and queue_push().
Referenced by addduppackages(), addsolvableedges(), findallproblemrules_internal(), findrecommendedsuggested(), pool_addrelproviders(), solver_addinfarchrules(), and solver_run_sat().
static void queue_push2 (Queue * q, Id id1, Id id2) [inline, static]
Definition at line 90 of file queue.h.
References queue_push().
Referenced by jobtodisablelist(), solver_disablepolicyrules(), solver_reenablepolicyrules(), and solver_take_solutionelement().
static void queue_truncate (Queue * q, int n) [inline, static]
Definition at line 97 of file queue.h.
References _Queue::count, and _Queue::left.
Referenced by jobtodisablelist(), and transaction_add_obsoleted().
void queue_init (Queue * q)
Definition at line 23 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, and _Queue::left.
Referenced by addsolvableedges(), analyze(), create_solutions(), dump_tes(), findrecommendedsuggested(), pool_addfileprovides_search(), pool_create(), prune_to_highest_prio_per_name(), refine_suggestion(), solver_addchoicerules(), solver_addinfarchrules(), solver_create(), solver_createcleandepsmap(), solver_printcompleteprobleminfo(), solver_printdecisions(), solver_printtransaction(), solver_printtrivial(), solver_ruleinfo(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_order(), and transaction_type().
void queue_init_buffer (Queue * q, Id * buf, int size)
Definition at line 46 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, and _Queue::left.
Referenced by addduppackages(), addedge(), havechoice(), makemultiversionconflict(), pool_addrelproviders(), solver_addrpmrulesforsolvable(), solver_addrpmrulesforupdaters(), solver_addupdaterule(), solver_disablepolicyrules(), solver_reenablepolicyrules(), and transaction_obs_pkg().
void queue_init_clone (Queue * t, Queue * s)
Definition at line 30 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE, _Queue::left, and sat_malloc2().
Referenced by pool_trivial_installable_noobsoletesmap(), solver_solve(), and transaction_init_clone().
void queue_free (Queue * q)
Definition at line 55 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, _Queue::left, and sat_free().
Referenced by addduppackages(), addedge(), addsolvableedges(), create_solutions(), findrecommendedsuggested(), havechoice(), pool_addfileprovides_search(), pool_addrelproviders(), pool_free(), pool_trivial_installable_noobsoletesmap(), prune_to_highest_prio_per_name(), refine_suggestion(), solver_addchoicerules(), solver_addinfarchrules(), solver_addrpmrulesforsolvable(), solver_addrpmrulesforupdaters(), solver_addupdaterule(), solver_createcleandepsmap(), solver_disablepolicyrules(), solver_free(), solver_printcompleteprobleminfo(), solver_printdecisions(), solver_printtransaction(), solver_printtrivial(), solver_reenablepolicyrules(), solver_ruleinfo(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_free(), transaction_obs_pkg(), transaction_order(), and transaction_type().
void queue_insert (Queue * q, int pos, Id id)
Definition at line 104 of file queue.c.
References _Queue::count, _Queue::elements, and queue_push().
void queue_insert2 (Queue * q, int pos, Id id1, Id id2)
Definition at line 126 of file queue.c.
References _Queue::count, _Queue::elements, and queue_push().
void queue_insertn (Queue * q, int pos, int n)
Definition at line 156 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE, _Queue::left, queue_alloc_one(), and sat_realloc2().
Referenced by transaction_add_obsoleted().
void queue_delete (Queue * q, int pos)
Definition at line 115 of file queue.c.
References _Queue::count, _Queue::elements, and _Queue::left.
void queue_delete2 (Queue * q, int pos)
Definition at line 139 of file queue.c.
References _Queue::count, _Queue::elements, and _Queue::left.
void queue_deleten (Queue * q, int pos, int n)
Definition at line 180 of file queue.c.
References _Queue::count, _Queue::elements, and _Queue::left.