satsolver: src/queue.c File Reference
queue.c File Reference
#include <stdlib.h>
#include <string.h>
#include "queue.h"
#include "util.h"
Defines
#define EXTRA_SPACE 8
#define EXTRA_SPACE_HEAD 8
Functions
void queue_init (Queue *q)
void queue_init_clone (Queue *t, Queue *s)
void queue_init_buffer (Queue *q, Id *buf, int size)
void queue_free (Queue *q)
void queue_alloc_one (Queue *q)
void queue_alloc_one_head (Queue *q)
void queue_insert (Queue *q, int pos, Id id)
void queue_delete (Queue *q, int pos)
void queue_insert2 (Queue *q, int pos, Id id1, Id id2)
void queue_delete2 (Queue *q, int pos)
void queue_insertn (Queue *q, int pos, int n)
void queue_deleten (Queue *q, int pos, int n)
Define Documentation
#define EXTRA_SPACE 8
Definition at line 19 of file queue.c.
Referenced by queue_alloc_one(), queue_init_clone(), and queue_insertn().
#define EXTRA_SPACE_HEAD 8
Definition at line 20 of file queue.c.
Referenced by queue_alloc_one_head().
Function Documentation
void queue_init (Queue * q)
Definition at line 23 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, and _Queue::left.
Referenced by addsolvableedges(), analyze(), create_solutions(), dump_tes(), findrecommendedsuggested(), pool_addfileprovides_search(), pool_create(), prune_to_highest_prio_per_name(), refine_suggestion(), solver_addchoicerules(), solver_addinfarchrules(), solver_create(), solver_createcleandepsmap(), solver_printcompleteprobleminfo(), solver_printdecisions(), solver_printtransaction(), solver_printtrivial(), solver_ruleinfo(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_order(), and transaction_type().
void queue_init_clone (Queue * t, Queue * s)
Definition at line 30 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE, _Queue::left, and sat_malloc2().
Referenced by pool_trivial_installable_noobsoletesmap(), solver_solve(), and transaction_init_clone().
void queue_init_buffer (Queue * q, Id * buf, int size)
Definition at line 46 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, and _Queue::left.
Referenced by addduppackages(), addedge(), havechoice(), makemultiversionconflict(), pool_addrelproviders(), solver_addrpmrulesforsolvable(), solver_addrpmrulesforupdaters(), solver_addupdaterule(), solver_disablepolicyrules(), solver_reenablepolicyrules(), and transaction_obs_pkg().
void queue_free (Queue * q)
Definition at line 55 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, _Queue::left, and sat_free().
Referenced by addduppackages(), addedge(), addsolvableedges(), create_solutions(), findrecommendedsuggested(), havechoice(), pool_addfileprovides_search(), pool_addrelproviders(), pool_free(), pool_trivial_installable_noobsoletesmap(), prune_to_highest_prio_per_name(), refine_suggestion(), solver_addchoicerules(), solver_addinfarchrules(), solver_addrpmrulesforsolvable(), solver_addrpmrulesforupdaters(), solver_addupdaterule(), solver_createcleandepsmap(), solver_disablepolicyrules(), solver_free(), solver_printcompleteprobleminfo(), solver_printdecisions(), solver_printtransaction(), solver_printtrivial(), solver_reenablepolicyrules(), solver_ruleinfo(), solver_run_sat(), solver_solve(), transaction_add_obsoleted(), transaction_free(), transaction_obs_pkg(), transaction_order(), and transaction_type().
void queue_alloc_one (Queue * q)
Definition at line 64 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE, _Queue::left, sat_malloc2(), and sat_realloc2().
Referenced by queue_alloc_one_head(), queue_insertn(), and queue_push().
void queue_alloc_one_head (Queue * q)
Definition at line 91 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE_HEAD, _Queue::left, and queue_alloc_one().
Referenced by queue_unshift().
void queue_insert (Queue * q, int pos, Id id)
Definition at line 104 of file queue.c.
References _Queue::count, _Queue::elements, and queue_push().
void queue_delete (Queue * q, int pos)
Definition at line 115 of file queue.c.
References _Queue::count, _Queue::elements, and _Queue::left.
void queue_insert2 (Queue * q, int pos, Id id1, Id id2)
Definition at line 126 of file queue.c.
References _Queue::count, _Queue::elements, and queue_push().
void queue_delete2 (Queue * q, int pos)
Definition at line 139 of file queue.c.
References _Queue::count, _Queue::elements, and _Queue::left.
void queue_insertn (Queue * q, int pos, int n)
Definition at line 156 of file queue.c.
References _Queue::alloc, _Queue::count, _Queue::elements, EXTRA_SPACE, _Queue::left, queue_alloc_one(), and sat_realloc2().
Referenced by transaction_add_obsoleted().
void queue_deleten (Queue * q, int pos, int n)
Definition at line 180 of file queue.c.
References _Queue::count, _Queue::elements, and _Queue::left.