satsolver: src/repo.h File Reference
repo.h File Reference
#include "pooltypes.h"
#include "pool.h"
#include "repodata.h"
Classes
struct _Repo
struct _KeyValue
struct _Datamatcher
struct _Dataiterator
struct _Dataiterator::di_parent
Defines
#define FOR_REPO_SOLVABLES(r, p, s)
#define SEARCH_NEXT_KEY 1
#define SEARCH_NEXT_SOLVABLE 2
#define SEARCH_STOP 3
#define SEARCH_ENTERSUB -1
#define SEARCH_STRINGMASK 15
#define SEARCH_STRING 1
#define SEARCH_STRINGSTART 2
#define SEARCH_STRINGEND 3
#define SEARCH_SUBSTRING 4
#define SEARCH_GLOB 5
#define SEARCH_REGEX 6
#define SEARCH_ERROR 15
#define SEARCH_NOCASE (1<<7)
#define SEARCH_NO_STORAGE_SOLVABLE (1<<8)
#define SEARCH_SUB (1<<9)
#define SEARCH_ARRAYSENTINEL (1<<10)
#define SEARCH_DISABLED_REPOS (1<<11)
#define SEARCH_COMPLETE_FILELIST (1<<12)
#define SEARCH_SKIP_KIND (1<<16)
#define SEARCH_FILES (1<<17)
#define SEARCH_CHECKSUMS (1<<18)
#define SEARCH_THISSOLVID (1<<31)
#define REPO_REUSE_REPODATA (1 << 0)
#define REPO_NO_INTERNALIZE (1 << 1)
#define REPO_LOCALPOOL (1 << 2)
#define REPO_USE_LOADING (1 << 3)
#define REPO_EXTEND_SOLVABLES (1 << 4)
#define DI_SEEK_STAY (1 << 16)
#define DI_SEEK_CHILD 1
#define DI_SEEK_PARENT 2
#define DI_SEEK_REWIND 3
Typedefs
typedef struct _Repo Repo
typedef struct _KeyValue KeyValue
typedef struct _Datamatcher Datamatcher
typedef struct _Dataiterator Dataiterator
Functions
Repo * repo_create (Pool *pool, const char *name)
void repo_free (Repo *repo, int reuseids)
void repo_empty (Repo *repo, int reuseids)
void repo_freeallrepos (Pool *pool, int reuseids)
void repo_free_solvable_block (Repo *repo, Id start, int count, int reuseids)
void * repo_sidedata_create (Repo *repo, size_t size)
void * repo_sidedata_extend (Repo *repo, void *b, size_t size, Id p, int count)
Offset repo_addid (Repo *repo, Offset olddeps, Id id)
Offset repo_addid_dep (Repo *repo, Offset olddeps, Id id, Id marker)
Offset repo_reserve_ids (Repo *repo, Offset olddeps, int num)
Offset repo_fix_supplements (Repo *repo, Offset provides, Offset supplements, Offset freshens)
Offset repo_fix_conflicts (Repo *repo, Offset conflicts)
static const char * repo_name (const Repo *repo)
static Id repo_add_solvable (Repo *repo)
static Id repo_add_solvable_block (Repo *repo, int count)
static Repo * pool_id2repo (Pool *pool, Id repoid)
static int pool_installable (const Pool *pool, Solvable *s)
Repodata * repo_add_repodata (Repo *repo, int flags)
Repodata * repo_last_repodata (Repo *repo)
void repo_search (Repo *repo, Id p, Id key, const char *match, int flags, int(*callback)(void *cbdata, Solvable *s, Repodata *data, Repokey *key, KeyValue *kv), void *cbdata)
const char * repo_lookup_str (Repo *repo, Id entry, Id key)
unsigned int repo_lookup_num (Repo *repo, Id entry, Id key, unsigned int notfound)
Id repo_lookup_id (Repo *repo, Id entry, Id keyid)
int repo_lookup_void (Repo *repo, Id entry, Id keyid)
const unsigned char * repo_lookup_bin_checksum (Repo *repo, Id entry, Id keyid, Id *typep)
int datamatcher_init (Datamatcher *ma, const char *match, int flags)
void datamatcher_free (Datamatcher *ma)
int datamatcher_match (Datamatcher *ma, const char *str)
int dataiterator_init (Dataiterator *di, Pool *pool, Repo *repo, Id p, Id keyname, const char *match, int flags)
void dataiterator_init_clone (Dataiterator *di, Dataiterator *from)
void dataiterator_set_search (Dataiterator *di, Repo *repo, Id p)
void dataiterator_set_keyname (Dataiterator *di, Id keyname)
int dataiterator_set_match (Dataiterator *di, const char *match, int flags)
void dataiterator_prepend_keyname (Dataiterator *di, Id keyname)
void dataiterator_free (Dataiterator *di)
int dataiterator_step (Dataiterator *di)
void dataiterator_setpos (Dataiterator *di)
void dataiterator_setpos_parent (Dataiterator *di)
int dataiterator_match (Dataiterator *di, Datamatcher *ma)
void dataiterator_skip_attribute (Dataiterator *di)
void dataiterator_skip_solvable (Dataiterator *di)
void dataiterator_skip_repo (Dataiterator *di)
void dataiterator_jump_to_solvid (Dataiterator *di, Id solvid)
void dataiterator_jump_to_repo (Dataiterator *di, Repo *repo)
void dataiterator_entersub (Dataiterator *di)
void dataiterator_clonepos (Dataiterator *di, Dataiterator *from)
void dataiterator_seek (Dataiterator *di, int whence)
void repo_set_id (Repo *repo, Id p, Id keyname, Id id)
void repo_set_num (Repo *repo, Id p, Id keyname, Id num)
void repo_set_str (Repo *repo, Id p, Id keyname, const char *str)
void repo_set_poolstr (Repo *repo, Id p, Id keyname, const char *str)
void repo_add_poolstr_array (Repo *repo, Id p, Id keyname, const char *str)
void repo_internalize (Repo *repo)
void repo_disable_paging (Repo *repo)
Define Documentation
#define FOR_REPO_SOLVABLES (r, p, s)
Value:
for (p = (r)->start, s = (r)->pool->solvables + p; p < (r)->end; p++, s = (r)->pool->solvables + p)     \
    if (s->repo == (r))
Definition at line 108 of file repo.h.
Referenced by pool_calc_duchanges(), pool_calc_installsizechange(), solvable_trivial_installable_repo(), solver_createdupmaps(), solver_solve(), transaction_add_obsoleted(), transaction_calculate(), transaction_check_order(), transaction_create_installedmap(), and transaction_installedresult().
#define SEARCH_NEXT_KEY 1
Definition at line 139 of file repo.h.
Referenced by repo_search_md(), and repodata_search().
#define SEARCH_NEXT_SOLVABLE 2
Definition at line 140 of file repo.h.
Referenced by repo_search_md().
#define SEARCH_STOP 3
Definition at line 141 of file repo.h.
#define SEARCH_ENTERSUB -1
Definition at line 142 of file repo.h.
Referenced by repodata_search().
#define SEARCH_STRINGMASK 15
Definition at line 157 of file repo.h.
Referenced by dataiterator_filelistcheck(), dataiterator_step(), datamatcher_free(), datamatcher_init(), and datamatcher_match().
#define SEARCH_STRING 1
Definition at line 158 of file repo.h.
Referenced by dataiterator_filelistcheck(), dataiterator_step(), and datamatcher_match().
#define SEARCH_STRINGSTART 2
Definition at line 159 of file repo.h.
Referenced by datamatcher_match().
#define SEARCH_STRINGEND 3
Definition at line 160 of file repo.h.
Referenced by datamatcher_match().
#define SEARCH_SUBSTRING 4
Definition at line 161 of file repo.h.
Referenced by datamatcher_match().
#define SEARCH_GLOB 5
Definition at line 162 of file repo.h.
Referenced by dataiterator_filelistcheck(), and datamatcher_match().
#define SEARCH_REGEX 6
Definition at line 163 of file repo.h.
Referenced by datamatcher_free(), datamatcher_init(), and datamatcher_match().
#define SEARCH_ERROR 15
Definition at line 164 of file repo.h.
Referenced by datamatcher_init().
#define SEARCH_NOCASE (1<<7)
Definition at line 165 of file repo.h.
Referenced by dataiterator_filelistcheck(), dataiterator_step(), datamatcher_init(), and datamatcher_match().
#define SEARCH_NO_STORAGE_SOLVABLE (1<<8)
Definition at line 168 of file repo.h.
Referenced by dataiterator_step(), and repo_search_md().
#define SEARCH_SUB (1<<9)
Definition at line 169 of file repo.h.
Referenced by dataiterator_step(), and repodata_search().
#define SEARCH_ARRAYSENTINEL (1<<10)
Definition at line 170 of file repo.h.
Referenced by dataiterator_step(), repodata_search(), and solvable_lookup_idarray().
#define SEARCH_DISABLED_REPOS (1<<11)
Definition at line 171 of file repo.h.
Referenced by dataiterator_step(), and repo_search().
#define SEARCH_COMPLETE_FILELIST (1<<12)
Definition at line 172 of file repo.h.
Referenced by dataiterator_filelistcheck(), and repo_search_md().
#define SEARCH_SKIP_KIND (1<<16)
Definition at line 175 of file repo.h.
Referenced by repodata_stringify().
#define SEARCH_FILES (1<<17)
Definition at line 179 of file repo.h.
Referenced by dataiterator_step(), and repodata_stringify().
#define SEARCH_CHECKSUMS (1<<18)
Definition at line 180 of file repo.h.
Referenced by repodata_stringify().
#define SEARCH_THISSOLVID (1<<31)
Definition at line 183 of file repo.h.
Referenced by dataiterator_set_match(), and dataiterator_step().
#define REPO_REUSE_REPODATA (1 << 0)
Definition at line 187 of file repo.h.
Referenced by repo_add_repodata(), and repo_add_solv_flags().
#define REPO_NO_INTERNALIZE (1 << 1)
Definition at line 188 of file repo.h.
#define REPO_LOCALPOOL (1 << 2)
Definition at line 189 of file repo.h.
Referenced by repo_add_repodata(), and repo_add_solv_flags().
#define REPO_USE_LOADING (1 << 3)
Definition at line 190 of file repo.h.
Referenced by repo_add_repodata(), and repo_add_solv_flags().
#define REPO_EXTEND_SOLVABLES (1 << 4)
Definition at line 191 of file repo.h.
#define DI_SEEK_STAY (1 << 16)
Definition at line 306 of file repo.h.
Referenced by dataiterator_seek().
#define DI_SEEK_CHILD 1
Definition at line 307 of file repo.h.
Referenced by dataiterator_seek().
#define DI_SEEK_PARENT 2
Definition at line 308 of file repo.h.
Referenced by dataiterator_seek().
#define DI_SEEK_REWIND 3
Definition at line 309 of file repo.h.
Referenced by dataiterator_seek().
Typedef Documentation
typedef struct _Repo Repo
typedef struct _KeyValue KeyValue
typedef struct _Datamatcher Datamatcher
typedef struct _Dataiterator Dataiterator
Function Documentation
Repo* repo_create (Pool * pool, const char * name)
Definition at line 41 of file repo.c.
References _Repo::end, _Repo::name, _Pool::nrepos, _Repo::nsolvables, _Pool::nsolvables, _Repo::pool, pool_freewhatprovides(), _Repo::repoid, _Pool::repos, sat_calloc(), sat_realloc2(), and _Repo::start.
void repo_free (Repo * repo, int reuseids)
Definition at line 117 of file repo.c.
References _Pool::nrepos, _Repo::pool, repo_empty(), repo_freedata(), _Repo::repoid, and _Pool::repos.
void repo_empty (Repo * repo, int reuseids)
Definition at line 74 of file repo.c.
References _Repo::end, _Repo::idarraydata, _Repo::idarraysize, _Pool::installed, _Repo::lastoff, _Repo::nrepodata, _Repo::nsolvables, _Pool::nsolvables, _Repo::pool, pool_free_solvable_block(), pool_freewhatprovides(), _Solvable::repo, _Repo::repodata, repodata_freedata(), _Repo::rpmdbid, sat_free(), _Pool::solvables, and _Repo::start.
Referenced by repo_free().
void repo_freeallrepos (Pool * pool, int reuseids)
Definition at line 140 of file repo.c.
References _Pool::nrepos, _Pool::nsolvables, pool_free_solvable_block(), pool_freewhatprovides(), repo_freedata(), _Pool::repos, and sat_free().
Referenced by pool_free().
void repo_free_solvable_block (Repo * repo, Id start, int count, int reuseids)
Definition at line 153 of file repo.c.
References _Repodata::end, _Repo::end, _Repo::nsolvables, _Repo::pool, pool_free_solvable_block(), _Solvable::repo, _Repo::repodata, repodata_shrink(), and _Pool::solvables.
Referenced by repo_add_solv_flags().
void* repo_sidedata_create (Repo * repo, size_t size)
Definition at line 180 of file repo.c.
References _Repo::end, REPO_SIDEDATA_BLOCK, sat_calloc_block(), and _Repo::start.
Referenced by repo_add_solv_flags().
void* repo_sidedata_extend (Repo * repo, void * b, size_t size, Id p, int count)
Definition at line 186 of file repo.c.
References _Repo::end, REPO_SIDEDATA_BLOCK, sat_extend(), and _Repo::start.
Referenced by repo_add_solvable(), and repo_add_solvable_block().
Offset repo_addid (Repo * repo, Offset olddeps, Id id)
Definition at line 213 of file repo.c.
References IDARRAY_BLOCK, _Repo::idarraydata, _Repo::idarraysize, _Repo::lastoff, sat_extend(), and sat_extend_resize().
Referenced by repo_addid_dep().
Offset repo_addid_dep (Repo * repo, Offset olddeps, Id id, Id marker)
Definition at line 270 of file repo.c.
References _Repo::idarraydata, and repo_addid().
Referenced by addfileprovides_cb(), pool_add_fileconflicts_deps(), and repo_fix_supplements().
Offset repo_reserve_ids (Repo * repo, Offset olddeps, int num)
Definition at line 355 of file repo.c.
References IDARRAY_BLOCK, _Repo::idarraydata, _Repo::idarraysize, _Repo::lastoff, sat_extend(), and sat_extend_resize().
Referenced by repo_add_solv_flags().
Offset repo_fix_supplements (Repo * repo, Offset provides, Offset supplements, Offset freshens)
Definition at line 406 of file repo.c.
References id2str(), _Repo::idarraydata, ISRELDEP, _Repo::pool, rel2id(), REL_AND, REL_NAMESPACE, REL_OR, REL_WITH, repo_addid_dep(), and str2id().
Offset repo_fix_conflicts (Repo * repo, Offset conflicts)
Definition at line 598 of file repo.c.
References id2str(), _Repo::idarraydata, ISRELDEP, _Repo::pool, rel2id(), REL_NAMESPACE, and str2id().
static const char* repo_name (const Repo * repo) [inline, static]
Definition at line 61 of file repo.h.
References _Repo::name.
static Id repo_add_solvable (Repo * repo) [inline, static]
Definition at line 66 of file repo.h.
References _Repo::end, _Repo::nsolvables, _Repo::pool, pool_add_solvable(), _Solvable::repo, repo_sidedata_extend(), _Repo::rpmdbid, _Pool::solvables, and _Repo::start.
static Id repo_add_solvable_block (Repo * repo, int count) [inline, static]
Definition at line 84 of file repo.h.
References _Repo::end, _Repo::nsolvables, _Repo::pool, pool_add_solvable_block(), _Solvable::repo, repo_sidedata_extend(), _Repo::rpmdbid, _Pool::solvables, and _Repo::start.
Referenced by repo_add_solv_flags().
static Repo* pool_id2repo (Pool * pool, Id repoid) [inline, static]
Definition at line 115 of file repo.h.
References _Pool::repos.
Referenced by solver_createdupmaps().
static int pool_installable (const Pool * pool, Solvable * s) [inline, static]
Definition at line 120 of file repo.h.
References _Solvable::arch, _Pool::considered, _Repo::disabled, _Pool::id2arch, _Pool::lastarch, MAPTST, _Solvable::repo, and _Pool::solvables.
Referenced by findrecommendedsuggested(), policy_create_obsolete_index(), pool_createwhatprovides(), solver_addrpmrulesforsolvable(), solver_addrpmrulesforweak(), solver_run_sat(), and solver_solve().
Repodata* repo_add_repodata (Repo * repo, int flags)
Definition at line 1019 of file repo.c.
References _Repo::nrepodata, REPO_LOCALPOOL, REPO_REUSE_REPODATA, REPO_USE_LOADING, _Repo::repodata, repodata_create(), repodata_freedata(), repodata_initdata(), REPODATA_LOADING, REPODATA_STUB, and _Repodata::state.
Referenced by repo_add_solv_flags(), repo_last_repodata(), and repodata_create_stubs().
Repodata* repo_last_repodata (Repo * repo)
Definition at line 1049 of file repo.c.
References _Repo::nrepodata, repo_add_repodata(), _Repo::repodata, REPODATA_STUB, and _Repodata::state.
Referenced by repo_add_poolstr_array(), repo_set_id(), repo_set_num(), repo_set_poolstr(), and repo_set_str().
void repo_search (Repo * repo, Id p, Id key, const char * match, int flags, int(*)(void *cbdata, Solvable *s, Repodata *data, Repokey *key, KeyValue *kv) callback, void * cbdata)
Definition at line 845 of file repo.c.
References matchdata::callback, matchdata::callback_data, datamatcher_free(), datamatcher_init(), _Repo::disabled, matchdata::flags, matchdata::matcher, _Repo::pool, matchdata::pool, repo_search_md(), and SEARCH_DISABLED_REPOS.
Referenced by pool_calc_duchanges(), and pool_search().
const char* repo_lookup_str (Repo * repo, Id entry, Id key)
Definition at line 864 of file repo.c.
References _Solvable::arch, _Repodata::end, _Solvable::evr, id2str(), _Repodata::keys, _Repokey::name, _Solvable::name, _Repodata::nkeys, _Repo::pool, matchdata::pool, _Repo::repodata, repodata_lookup_str(), repodata_precheck_keyname(), _Pool::solvables, SOLVID_META, _Repokey::type, and _Solvable::vendor.
Referenced by solvable_lookup_str().
unsigned int repo_lookup_num (Repo * repo, Id entry, Id key, unsigned int notfound)
Definition at line 898 of file repo.c.
References _Repodata::end, _Repodata::keys, _Repokey::name, _Repodata::nkeys, _Repo::repodata, repodata_lookup_num(), repodata_precheck_keyname(), _Repo::rpmdbid, SOLVID_META, _Repo::start, and _Repokey::type.
Referenced by solvable_lookup_num().
Id repo_lookup_id (Repo * repo, Id entry, Id keyid)
Definition at line 932 of file repo.c.
References _Solvable::arch, _Repodata::end, _Solvable::evr, _Repodata::keys, _Repodata::localpool, _Repokey::name, _Solvable::name, _Repodata::nkeys, _Repo::pool, _Repo::repodata, repodata_globalize_id(), repodata_lookup_id(), repodata_precheck_keyname(), _Pool::solvables, SOLVID_META, _Repokey::type, and _Solvable::vendor.
Referenced by solvable_lookup_id().
int repo_lookup_void (Repo * repo, Id entry, Id keyid)
Definition at line 993 of file repo.c.
References _Repodata::end, _Repodata::keys, _Repokey::name, _Repodata::nkeys, _Repo::repodata, repodata_lookup_void(), repodata_precheck_keyname(), SOLVID_META, and _Repokey::type.
Referenced by solvable_lookup_void().
const unsigned char* repo_lookup_bin_checksum (Repo * repo, Id entry, Id keyid, Id * typep)
Definition at line 968 of file repo.c.
References _Repodata::end, _Repodata::keys, _Repokey::name, _Repodata::nkeys, _Repo::repodata, repodata_lookup_bin_checksum(), repodata_precheck_keyname(), and SOLVID_META.
Referenced by solvable_lookup_bin_checksum().
int datamatcher_init (Datamatcher * ma, const char * match, int flags)
Definition at line 934 of file repodata.c.
References _Datamatcher::error, _Datamatcher::flags, _Datamatcher::match, _Datamatcher::matchdata, sat_calloc(), sat_free(), SEARCH_ERROR, SEARCH_NOCASE, SEARCH_REGEX, and SEARCH_STRINGMASK.
Referenced by dataiterator_init(), dataiterator_init_clone(), dataiterator_set_match(), and repo_search().
void datamatcher_free (Datamatcher * ma)
Definition at line 954 of file repodata.c.
References _Datamatcher::flags, _Datamatcher::matchdata, sat_free(), SEARCH_REGEX, and SEARCH_STRINGMASK.
Referenced by dataiterator_free(), dataiterator_set_match(), and repo_search().
int datamatcher_match (Datamatcher * ma, const char * str)
Definition at line 964 of file repodata.c.
References _Datamatcher::flags, _Datamatcher::match, _Datamatcher::matchdata, SEARCH_GLOB, SEARCH_NOCASE, SEARCH_REGEX, SEARCH_STRING, SEARCH_STRINGEND, SEARCH_STRINGMASK, SEARCH_STRINGSTART, and SEARCH_SUBSTRING.
Referenced by dataiterator_match(), dataiterator_step(), and repo_matchvalue().
int dataiterator_init (Dataiterator * di, Pool * pool, Repo * repo, Id p, Id keyname, const char * match, int flags)
Definition at line 1077 of file repodata.c.
References dataiterator_set_search(), datamatcher_init(), _Dataiterator::flags, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::matcher, _Repo::pool, _Dataiterator::pool, and _Dataiterator::state.
Referenced by repodata_create_stubs(), and solvable_lookup_idarray().
void dataiterator_init_clone (Dataiterator * di, Dataiterator * from)
Definition at line 1103 of file repodata.c.
References datamatcher_init(), _Datamatcher::flags, _Dataiterator::kv, _Dataiterator::di_parent::kv, _Datamatcher::match, _Dataiterator::matcher, _Dataiterator::nparents, _KeyValue::parent, and _Dataiterator::parents.
void dataiterator_set_search (Dataiterator * di, Repo * repo, Id p)
Definition at line 1138 of file repodata.c.
References dataiterator_jump_to_solvid(), _Dataiterator::flags, _Dataiterator::nparents, _Pool::nrepos, _Dataiterator::pool, _Dataiterator::repo, _Dataiterator::repodataid, _Dataiterator::repoid, _Pool::repos, _Dataiterator::rootlevel, and _Dataiterator::state.
Referenced by dataiterator_init().
void dataiterator_set_keyname (Dataiterator * di, Id keyname)
Definition at line 1162 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, and _Dataiterator::nkeynames.
int dataiterator_set_match (Dataiterator * di, const char * match, int flags)
Definition at line 1120 of file repodata.c.
References datamatcher_free(), datamatcher_init(), _Dataiterator::flags, _Dataiterator::matcher, SEARCH_THISSOLVID, and _Dataiterator::state.
void dataiterator_prepend_keyname (Dataiterator * di, Id keyname)
Definition at line 1170 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::nkeynames, and _Dataiterator::state.
void dataiterator_free (Dataiterator * di)
Definition at line 1186 of file repodata.c.
References datamatcher_free(), _Datamatcher::match, and _Dataiterator::matcher.
Referenced by repodata_create_stubs(), and solvable_lookup_idarray().
int dataiterator_step (Dataiterator * di)
Definition at line 1233 of file repodata.c.
References _Dataiterator::data, data_fetch(), data_read_id(), data_skip_schema(), dataiterator_filelistcheck(), dataiterator_find_keyname(), datamatcher_match(), _Dataiterator::ddp, di_bye, di_enterarray, di_enterkey, di_enterrepo, di_enterrepodata, di_enterschema, di_entersolvable, di_entersolvablekey, di_entersub, di_leavesub, di_nextarrayelement, di_nextattr, di_nextkey, di_nextrepo, di_nextrepodata, di_nextsolvable, di_nextsolvableattr, di_nextsolvablekey, _Repo::disabled, _Dataiterator::di_parent::dp, _Dataiterator::dp, _Repo::end, _KeyValue::entry, _KeyValue::eof, _Datamatcher::flags, _Dataiterator::flags, get_data(), _KeyValue::id, _Dataiterator::idp, _Dataiterator::key, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::di_parent::keyp, _Dataiterator::keyp, _Repodata::keys, _Dataiterator::di_parent::kv, _Dataiterator::kv, _Datamatcher::match, _Dataiterator::matcher, maybe_load_repodata(), _Repokey::name, _Dataiterator::nkeynames, _Dataiterator::nparents, _Repo::nrepodata, _Pool::nrepos, _KeyValue::num, _KeyValue::parent, _Dataiterator::parents, _Dataiterator::pool, _Pool::pos, _Solvable::repo, _Dataiterator::repo, _Repo::repodata, repodata_stringify(), _Dataiterator::repodataid, _Dataiterator::repoid, _Pool::repos, _Dataiterator::rootlevel, _Repodata::schemadata, _Repodata::schemata, SEARCH_ARRAYSENTINEL, SEARCH_DISABLED_REPOS, SEARCH_FILES, SEARCH_NO_STORAGE_SOLVABLE, SEARCH_NOCASE, SEARCH_STRING, SEARCH_STRINGMASK, SEARCH_SUB, SEARCH_THISSOLVID, solvabledata_fetch(), _Pool::solvables, _Repopos::solvid, _Dataiterator::solvid, solvid2data(), SOLVID_POS, _Repo::start, _Dataiterator::state, _KeyValue::str, and _Repokey::type.
Referenced by repodata_create_stubs(), and solvable_lookup_idarray().
void dataiterator_setpos (Dataiterator * di)
Definition at line 1490 of file repodata.c.
References _Dataiterator::data, _Repopos::dp, _KeyValue::eof, _KeyValue::id, _Repodata::incoredata, _Dataiterator::kv, _Dataiterator::pool, pool_clear_pos(), _Pool::pos, _Dataiterator::repo, _Repopos::repo, _Repo::repodata, _Repopos::repodataid, _Repopos::schema, _Dataiterator::solvid, _Repopos::solvid, and _KeyValue::str.
void dataiterator_setpos_parent (Dataiterator * di)
Definition at line 1505 of file repodata.c.
References _Dataiterator::data, _Repopos::dp, _KeyValue::eof, _KeyValue::id, _Repodata::incoredata, _Dataiterator::kv, _KeyValue::parent, _Dataiterator::pool, pool_clear_pos(), _Pool::pos, _Dataiterator::repo, _Repopos::repo, _Repo::repodata, _Repopos::repodataid, _Repopos::schema, _Dataiterator::solvid, _Repopos::solvid, and _KeyValue::str.
int dataiterator_match (Dataiterator * di, Datamatcher * ma)
Definition at line 1684 of file repodata.c.
References _Dataiterator::data, datamatcher_match(), _Dataiterator::flags, _Dataiterator::key, _Dataiterator::kv, _Dataiterator::pool, repodata_stringify(), and _KeyValue::str.
void dataiterator_skip_attribute (Dataiterator * di)
Definition at line 1596 of file repodata.c.
References di_nextsolvableattr, and _Dataiterator::state.
void dataiterator_skip_solvable (Dataiterator * di)
Definition at line 1605 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::rootlevel, and _Dataiterator::state.
void dataiterator_skip_repo (Dataiterator * di)
Definition at line 1615 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::rootlevel, and _Dataiterator::state.
void dataiterator_jump_to_solvid (Dataiterator * di, Id solvid)
Definition at line 1625 of file repodata.c.
References _Dataiterator::data, _Dataiterator::flags, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::kv, _Dataiterator::nparents, _Pool::nrepos, _KeyValue::parent, _Dataiterator::pool, _Pool::pos, _Solvable::repo, _Repopos::repo, _Dataiterator::repo, _Repo::repodata, _Dataiterator::repodataid, _Repopos::repodataid, _Dataiterator::repoid, _Pool::repos, _Dataiterator::rootlevel, _Pool::solvables, _Dataiterator::solvid, SOLVID_POS, and _Dataiterator::state.
Referenced by dataiterator_set_search().
void dataiterator_jump_to_repo (Dataiterator * di, Repo * repo)
Definition at line 1670 of file repodata.c.
References _Dataiterator::flags, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::repo, _Dataiterator::repodataid, _Dataiterator::repoid, _Dataiterator::rootlevel, _Dataiterator::solvid, and _Dataiterator::state.
void dataiterator_entersub (Dataiterator * di)
Definition at line 1483 of file repodata.c.
References di_nextarrayelement, and _Dataiterator::state.
Referenced by repodata_create_stubs().
void dataiterator_clonepos (Dataiterator * di, Dataiterator * from)
Definition at line 1521 of file repodata.c.
References _Dataiterator::data, _Dataiterator::ddp, _Dataiterator::dp, _Dataiterator::flags, _Dataiterator::idp, _Dataiterator::key, _Dataiterator::keyp, _Dataiterator::di_parent::kv, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::parents, _Dataiterator::repo, _Dataiterator::repodataid, _Dataiterator::repoid, _Dataiterator::rootlevel, _Dataiterator::solvid, and _Dataiterator::state.
void dataiterator_seek (Dataiterator * di, int whence)
Definition at line 1550 of file repodata.c.
References _Dataiterator::data, _Dataiterator::ddp, di_enterschema, di_nextarrayelement, DI_SEEK_CHILD, DI_SEEK_PARENT, DI_SEEK_REWIND, DI_SEEK_STAY, _Dataiterator::di_parent::dp, _Dataiterator::dp, _KeyValue::id, _Dataiterator::key, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::di_parent::keyp, _Dataiterator::keyp, _Repodata::keys, _Dataiterator::di_parent::kv, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::parents, _Dataiterator::rootlevel, _Repodata::schemadata, _Repodata::schemata, _Dataiterator::state, and _KeyValue::str.
void repo_set_id (Repo * repo, Id p, Id keyname, Id id)
Definition at line 1059 of file repo.c.
References repo_last_repodata(), and repodata_set_id().
void repo_set_num (Repo * repo, Id p, Id keyname, Id num)
Definition at line 1066 of file repo.c.
References repo_last_repodata(), and repodata_set_num().
void repo_set_str (Repo * repo, Id p, Id keyname, const char * str)
Definition at line 1073 of file repo.c.
References repo_last_repodata(), and repodata_set_str().
void repo_set_poolstr (Repo * repo, Id p, Id keyname, const char * str)
Definition at line 1080 of file repo.c.
References repo_last_repodata(), and repodata_set_poolstr().
void repo_add_poolstr_array (Repo * repo, Id p, Id keyname, const char * str)
Definition at line 1087 of file repo.c.
References repo_last_repodata(), and repodata_add_poolstr_array().
void repo_internalize (Repo * repo)
Definition at line 1094 of file repo.c.
References _Repodata::attrs, _Repo::repodata, repodata_internalize(), and _Repodata::xattrs.
void repo_disable_paging (Repo * repo)
Definition at line 1105 of file repo.c.
References _Repo::repodata, and repodata_disable_paging().