satsolver: src/repodata.h File Reference
repodata.h File Reference
#include <stdio.h>
#include "pooltypes.h"
#include "pool.h"
#include "dirpool.h"
#include "repopage.h"
Classes
struct _Repokey
struct _Repodata
Defines
#define SIZEOF_MD5 16
#define SIZEOF_SHA1 20
#define SIZEOF_SHA256 32
#define KEY_STORAGE_DROPPED 0
#define KEY_STORAGE_SOLVABLE 1
#define KEY_STORAGE_INCORE 2
#define KEY_STORAGE_VERTICAL_OFFSET 3
#define REPODATA_AVAILABLE 0
#define REPODATA_STUB 1
#define REPODATA_ERROR 2
#define REPODATA_STORE 3
#define REPODATA_LOADING 4
#define SOLVID_META -1
#define SOLVID_POS -2
#define SOLVID_SUBSCHEMA -3
Typedefs
typedef struct _Repokey Repokey
typedef struct _Repodata Repodata
Functions
void repodata_initdata (Repodata *data, struct _Repo *repo, int localpool)
void repodata_freedata (Repodata *data)
Repodata * repodata_create (struct _Repo *repo, int localpool)
void repodata_free (Repodata *data)
Id repodata_key2id (Repodata *data, Repokey *key, int create)
static Repokey * repodata_id2key (Repodata *data, Id keyid)
Id repodata_schema2id (Repodata *data, Id *schema, int create)
static Id * repodata_id2schema (Repodata *data, Id schemaid)
static int repodata_precheck_keyname (Repodata *data, Id keyname)
static int repodata_has_keyname (Repodata *data, Id keyname)
void repodata_search (Repodata *data, Id solvid, Id keyname, int flags, int(*callback)(void *cbdata, Solvable *s, Repodata *data, Repokey *key, struct _KeyValue *kv), void *cbdata)
int repodata_stringify (Pool *pool, Repodata *data, Repokey *key, struct _KeyValue *kv, int flags)
int repodata_filelistfilter_matches (Repodata *data, const char *str)
Id repodata_lookup_id (Repodata *data, Id solvid, Id keyname)
const char * repodata_lookup_str (Repodata *data, Id solvid, Id keyname)
int repodata_lookup_num (Repodata *data, Id solvid, Id keyname, unsigned int *value)
int repodata_lookup_void (Repodata *data, Id solvid, Id keyname)
const unsigned char * repodata_lookup_bin_checksum (Repodata *data, Id solvid, Id keyname, Id *typep)
int repodata_lookup_idarray (Repodata *data, Id solvid, Id keyname, Queue *q)
void repodata_extend (Repodata *data, Id p)
void repodata_extend_block (Repodata *data, Id p, int num)
void repodata_shrink (Repodata *data, int end)
void repodata_internalize (Repodata *data)
Id repodata_new_handle (Repodata *data)
void repodata_set_void (Repodata *data, Id solvid, Id keyname)
void repodata_set_num (Repodata *data, Id solvid, Id keyname, unsigned int num)
void repodata_set_id (Repodata *data, Id solvid, Id keyname, Id id)
void repodata_set_str (Repodata *data, Id solvid, Id keyname, const char *str)
void repodata_set_binary (Repodata *data, Id solvid, Id keyname, void *buf, int len)
void repodata_set_poolstr (Repodata *data, Id solvid, Id keyname, const char *str)
void repodata_set_constant (Repodata *data, Id solvid, Id keyname, unsigned int constant)
void repodata_set_constantid (Repodata *data, Id solvid, Id keyname, Id id)
void repodata_set_bin_checksum (Repodata *data, Id solvid, Id keyname, Id type, const unsigned char *buf)
void repodata_set_checksum (Repodata *data, Id solvid, Id keyname, Id type, const char *str)
void repodata_add_dirnumnum (Repodata *data, Id solvid, Id keyname, Id dir, Id num, Id num2)
void repodata_add_dirstr (Repodata *data, Id solvid, Id keyname, Id dir, const char *str)
void repodata_add_idarray (Repodata *data, Id solvid, Id keyname, Id id)
void repodata_add_poolstr_array (Repodata *data, Id solvid, Id keyname, const char *str)
void repodata_add_fixarray (Repodata *data, Id solvid, Id keyname, Id ghandle)
void repodata_add_flexarray (Repodata *data, Id solvid, Id keyname, Id ghandle)
void repodata_delete_uninternalized (Repodata *data, Id solvid, Id keyname)
void repodata_merge_attrs (Repodata *data, Id dest, Id src)
void repodata_merge_some_attrs (Repodata *data, Id dest, Id src, Map *keyidmap, int overwrite)
void repodata_create_stubs (Repodata *data)
void repodata_join (Repodata *data, Id joinkey)
void repodata_disable_paging (Repodata *data)
Id repodata_globalize_id (Repodata *data, Id id, int create)
Id repodata_str2dir (Repodata *data, const char *dir, int create)
const char * repodata_dir2str (Repodata *data, Id did, const char *suf)
const char * repodata_chk2str (Repodata *data, Id type, const unsigned char *buf)
void repodata_set_location (Repodata *data, Id solvid, int medianr, const char *dir, const char *file)
Define Documentation
#define SIZEOF_MD5 16
Definition at line 23 of file repodata.h.
Referenced by repodata_serialize_key().
#define SIZEOF_SHA1 20
Definition at line 24 of file repodata.h.
Referenced by repodata_serialize_key().
#define SIZEOF_SHA256 32
Definition at line 25 of file repodata.h.
Referenced by repodata_serialize_key().
#define KEY_STORAGE_DROPPED 0
Definition at line 37 of file repodata.h.
#define KEY_STORAGE_SOLVABLE 1
Definition at line 38 of file repodata.h.
Referenced by repo_add_solv_flags(), and repodata_stringify().
#define KEY_STORAGE_INCORE 2
Definition at line 39 of file repodata.h.
Referenced by data_skip_key(), forward_to_key(), get_data(), repo_add_solv_flags(), and repodata_internalize().
#define KEY_STORAGE_VERTICAL_OFFSET 3
Definition at line 40 of file repodata.h.
Referenced by data_skip_key(), forward_to_key(), get_data(), repo_add_solv_flags(), repodata_internalize(), and repodata_serialize_key().
#define REPODATA_AVAILABLE 0
Definition at line 46 of file repodata.h.
Referenced by dataiterator_filelistcheck(), load_repodata(), maybe_load_repodata(), pool_addfileprovides_search(), and repo_search_md().
#define REPODATA_STUB 1
Definition at line 47 of file repodata.h.
Referenced by maybe_load_repodata(), repo_add_repodata(), repo_last_repodata(), and repo_search_md().
#define REPODATA_ERROR 2
Definition at line 48 of file repodata.h.
Referenced by maybe_load_repodata(), and repo_search_md().
#define REPODATA_STORE 3
Definition at line 49 of file repodata.h.
#define REPODATA_LOADING 4
Definition at line 50 of file repodata.h.
Referenced by maybe_load_repodata(), and repo_add_repodata().
#define SOLVID_META -1
Definition at line 110 of file repodata.h.
Referenced by pool_addfileprovides_search(), repo_lookup_bin_checksum(), repo_lookup_id(), repo_lookup_num(), repo_lookup_str(), repo_lookup_void(), repodata_create_stubs(), repodata_get_attrp(), and solvid2data().
#define SOLVID_POS -2
Definition at line 111 of file repodata.h.
Referenced by dataiterator_jump_to_solvid(), dataiterator_step(), pool_lookup_bin_checksum(), pool_lookup_checksum(), pool_lookup_id(), pool_lookup_num(), pool_lookup_str(), pool_lookup_void(), and solvid2data().
#define SOLVID_SUBSCHEMA -3
Definition at line 112 of file repodata.h.
Referenced by repodata_search().
Typedef Documentation
typedef struct _Repokey Repokey
typedef struct _Repodata Repodata
Function Documentation
void repodata_initdata (Repodata * data, struct _Repo * repo, int localpool)
Definition at line 48 of file repodata.c.
References _Repodata::keys, _Repodata::localpool, _Repodata::nkeys, _Repodata::nschemata, _Repodata::repo, repopagestore_init(), sat_calloc(), _Repodata::schemadata, _Repodata::schemadatalen, _Repodata::schemata, _Repodata::spool, _Repodata::store, and stringpool_init_empty().
Referenced by repo_add_repodata(), and repodata_create().
void repodata_freedata (Repodata * data)
Definition at line 65 of file repodata.c.
References _Repodata::attrdata, _Repodata::attriddata, _Repodata::attrs, _Repodata::dirpool, dirpool_free(), _Repodata::end, _Repodata::incoredata, _Repodata::incoreoffset, _Repodata::keys, _Repodata::mainschemaoffsets, _Repodata::nxattrs, repopagestore_free(), sat_free(), _Repodata::schemadata, _Repodata::schemata, _Repodata::schematahash, _Repodata::spool, _Repodata::start, _Repodata::store, stringpool_free(), _Repodata::verticaloffset, _Repodata::vincore, and _Repodata::xattrs.
Referenced by repo_add_repodata(), repo_add_solv_flags(), repo_empty(), repo_freedata(), and repodata_free().
Repodata* repodata_create (struct _Repo * repo, int localpool)
Definition at line 101 of file repodata.c.
References _Repo::nrepodata, _Repo::repodata, repodata_initdata(), and sat_realloc2().
Referenced by repo_add_repodata().
void repodata_free (Repodata * data)
Definition at line 113 of file repodata.c.
References _Repo::nrepodata, _Repodata::repo, _Repo::repodata, and repodata_freedata().
Id repodata_key2id (Repodata * data, Repokey * key, int create)
Definition at line 131 of file repodata.c.
References _Repodata::keybits, _Repodata::keys, _Repokey::name, _Repodata::nkeys, sat_realloc2(), _Repokey::size, _Repokey::type, and _Repodata::verticaloffset.
Referenced by repodata_create_stubs(), repodata_internalize(), and repodata_set().
static Repokey* repodata_id2key (Repodata * data, Id keyid) [inline, static]
Definition at line 130 of file repodata.h.
References _Repodata::keys.
Id repodata_schema2id (Repodata * data, Id * schema, int create)
Definition at line 168 of file repodata.c.
References _Repodata::nschemata, sat_calloc(), sat_extend(), sat_extend_resize(), _Repodata::schemadata, _Repodata::schemadatalen, _Repodata::schemata, SCHEMATA_BLOCK, SCHEMATADATA_BLOCK, and _Repodata::schematahash.
Referenced by repodata_internalize(), and repodata_serialize_key().
static Id* repodata_id2schema (Repodata * data, Id schemaid) [inline, static]
Definition at line 140 of file repodata.h.
References _Repodata::schemadata, and _Repodata::schemata.
static int repodata_precheck_keyname (Repodata * data, Id keyname) [inline, static]
Definition at line 152 of file repodata.h.
References _Repodata::keybits.
Referenced by maybe_load_repodata(), repo_lookup_bin_checksum(), repo_lookup_id(), repo_lookup_num(), repo_lookup_str(), repo_lookup_void(), repo_search_md(), and repodata_has_keyname().
static int repodata_has_keyname (Repodata * data, Id keyname) [inline, static]
Definition at line 160 of file repodata.h.
References _Repodata::keys, _Repokey::name, _Repodata::nkeys, and repodata_precheck_keyname().
Referenced by pool_addfileprovides_search().
void repodata_search (Repodata * data, Id solvid, Id keyname, int flags, int(*)(void *cbdata, Solvable *s, Repodata *data, Repokey *key, struct _KeyValue *kv) callback, void * cbdata)
int repodata_stringify (Pool * pool, Repodata * data, Repokey * key, struct _KeyValue * kv, int flags)
Definition at line 684 of file repodata.c.
References _KeyValue::id, id2str(), KEY_STORAGE_SOLVABLE, _Repodata::localpool, repodata_chk2str(), repodata_dir2str(), SEARCH_CHECKSUMS, SEARCH_FILES, SEARCH_SKIP_KIND, _Repodata::spool, _Repokey::storage, _KeyValue::str, stringpool_id2str(), and _Repokey::type.
Referenced by dataiterator_match(), dataiterator_step(), and repo_matchvalue().
int repodata_filelistfilter_matches (Repodata * data, const char * str)
Definition at line 1035 of file repodata.c.
Referenced by dataiterator_filelistcheck(), and pool_addfileprovides_search().
Id repodata_lookup_id (Repodata * data, Id solvid, Id keyname)
Definition at line 554 of file repodata.c.
References data_read_id(), find_key_data(), _Repokey::size, and _Repokey::type.
Referenced by pool_lookup_id(), and repo_lookup_id().
const char* repodata_lookup_str (Repodata * data, Id solvid, Id keyname)
Definition at line 580 of file repodata.c.
References data_read_id(), find_key_data(), id2str(), _Repodata::localpool, _Repo::pool, _Repodata::repo, _Repokey::size, _Repodata::spool, _Stringpool::strings, _Stringpool::stringspace, and _Repokey::type.
Referenced by pool_lookup_str(), and repo_lookup_str().
int repodata_lookup_num (Repodata * data, Id solvid, Id keyname, unsigned int * value)
Definition at line 603 of file repodata.c.
References data_fetch(), find_key_data(), _KeyValue::num, and _Repokey::type.
Referenced by pool_lookup_num(), repo_lookup_num(), and solvable_lookup_bool().
int repodata_lookup_void (Repodata * data, Id solvid, Id keyname)
Definition at line 625 of file repodata.c.
References _Repodata::keys, maybe_load_repodata(), _Repokey::name, _Repodata::schemadata, _Repodata::schemata, solvid2data(), and _Repokey::type.
Referenced by pool_lookup_void(), repo_lookup_void(), and solvable_lookup_bool().
const unsigned char* repodata_lookup_bin_checksum (Repodata * data, Id solvid, Id keyname, Id * typep)
Definition at line 644 of file repodata.c.
References find_key_data(), and _Repokey::type.
Referenced by pool_lookup_bin_checksum(), pool_lookup_checksum(), and repo_lookup_bin_checksum().
int repodata_lookup_idarray (Repodata * data, Id solvid, Id keyname, Queue * q)
Definition at line 657 of file repodata.c.
References data_read_ideof(), find_key_data(), queue_empty(), and queue_push().
Referenced by pool_addfileprovides_search().
void repodata_extend (Repodata * data, Id p)
Definition at line 1699 of file repodata.c.
References _Repodata::attrs, _Repodata::end, _Repodata::incoreoffset, REPODATA_BLOCK, sat_extend(), sat_extend_resize(), and _Repodata::start.
Referenced by repodata_extend_block(), and repodata_get_attrp().
void repodata_extend_block (Repodata * data, Id p, int num)
void repodata_shrink (Repodata * data, int end)
Definition at line 1735 of file repodata.c.
References _Repodata::attrs, _Repodata::end, _Repodata::incoreoffset, REPODATA_BLOCK, sat_extend_resize(), sat_free(), and _Repodata::start.
Referenced by repo_free_solvable_block().
void repodata_internalize (Repodata * data)
Definition at line 2542 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repodata::attriddata, _Repodata::attriddatalen, _Repodata::attrs, extdata::buf, data_addblob(), data_addid(), data_read_id(), data_skip(), data_skip_key(), _Repodata::end, id2str(), _Repodata::incoredata, _Repodata::incoredatafree, _Repodata::incoredatalen, _Repodata::incoreoffset, KEY_STORAGE_INCORE, KEY_STORAGE_VERTICAL_OFFSET, _Repodata::keys, _Repodata::lastdatalen, _Repodata::lasthandle, _Repodata::lastkey, extdata::len, _Repodata::mainschema, _Repodata::mainschemaoffsets, _Repokey::name, _Repodata::nkeys, _Repodata::nxattrs, _Repo::pool, pool_debug(), _Repodata::repo, repodata_free_schemahash(), repodata_key2id(), repodata_schema2id(), repodata_serialize_key(), sat_calloc(), SAT_FATAL, sat_free(), sat_malloc2(), _Repodata::schemadata, _Repodata::schemata, _Repokey::size, _Repodata::start, _Repokey::storage, _Repokey::type, _Repodata::vincore, _Repodata::vincorelen, and _Repodata::xattrs.
Referenced by repo_internalize(), and repodata_create_stubs().
Id repodata_new_handle (Repodata * data)
Definition at line 1791 of file repodata.c.
References _Repodata::nxattrs, REPODATA_BLOCK, sat_calloc_block(), sat_extend(), and _Repodata::xattrs.
void repodata_set_void (Repodata * data, Id solvid, Id keyname)
Definition at line 1930 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_create_stubs(), and repodata_set_location().
void repodata_set_num (Repodata * data, Id solvid, Id keyname, unsigned int num)
Definition at line 1881 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repo_set_num(), and repodata_create_stubs().
void repodata_set_id (Repodata * data, Id solvid, Id keyname, Id id)
Definition at line 1870 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repo_set_id(), and repodata_create_stubs().
void repodata_set_str (Repodata * data, Id solvid, Id keyname, const char * str)
Definition at line 1941 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repokey::name, REPODATA_ATTRDATA_BLOCK, repodata_set(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repo_set_str(), repodata_create_stubs(), and repodata_set_location().
void repodata_set_binary (Repodata * data, Id solvid, Id keyname, void * buf, int len)
Definition at line 1958 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repokey::name, REPODATA_ATTRDATA_BLOCK, repodata_set(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
void repodata_set_poolstr (Repodata * data, Id solvid, Id keyname, const char * str)
Definition at line 1892 of file repodata.c.
References _Repodata::localpool, _Repokey::name, _Repo::pool, _Repodata::repo, repodata_set(), _Repokey::size, _Repodata::spool, _Repokey::storage, str2id(), stringpool_str2id(), and _Repokey::type.
Referenced by repo_set_poolstr().
void repodata_set_constant (Repodata * data, Id solvid, Id keyname, unsigned int constant)
Definition at line 1908 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_set_location().
void repodata_set_constantid (Repodata * data, Id solvid, Id keyname, Id id)
Definition at line 1919 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_create_stubs().
void repodata_set_bin_checksum (Repodata * data, Id solvid, Id keyname, Id type, const unsigned char * buf)
Definition at line 2046 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repokey::name, REPODATA_ATTRDATA_BLOCK, repodata_set(), sat_chksum_len(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_create_stubs(), and repodata_set_checksum().
void repodata_set_checksum (Repodata * data, Id solvid, Id keyname, Id type, const char * str)
Definition at line 2090 of file repodata.c.
References hexstr2bytes(), repodata_set_bin_checksum(), and sat_chksum_len().
void repodata_add_dirnumnum (Repodata * data, Id solvid, Id keyname, Id dir, Id num, Id num2)
Definition at line 2206 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
void repodata_add_dirstr (Repodata * data, Id solvid, Id keyname, Id dir, const char * str)
Definition at line 2220 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repodata::attriddata, _Repodata::attriddatalen, repodata_add_array(), REPODATA_ATTRDATA_BLOCK, and sat_extend().
void repodata_add_idarray (Repodata * data, Id solvid, Id keyname, Id id)
Definition at line 2242 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
Referenced by repodata_add_poolstr_array(), and repodata_create_stubs().
void repodata_add_poolstr_array (Repodata * data, Id solvid, Id keyname, const char * str)
Definition at line 2253 of file repodata.c.
References _Repodata::localpool, _Repo::pool, _Repodata::repo, repodata_add_idarray(), _Repodata::spool, str2id(), and stringpool_str2id().
Referenced by repo_add_poolstr_array().
void repodata_add_fixarray (Repodata * data, Id solvid, Id keyname, Id ghandle)
Definition at line 2265 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
void repodata_add_flexarray (Repodata * data, Id solvid, Id keyname, Id ghandle)
Definition at line 2273 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
void repodata_delete_uninternalized (Repodata * data, Id solvid, Id keyname)
Definition at line 2281 of file repodata.c.
References _Repodata::keys, _Repokey::name, and repodata_get_attrp().
void repodata_merge_attrs (Repodata * data, Id dest, Id src)
Definition at line 2307 of file repodata.c.
References _Repodata::attrs, repodata_insert_keyid(), and _Repodata::start.
void repodata_merge_some_attrs (Repodata * data, Id dest, Id src, Map * keyidmap, int overwrite)
Definition at line 2317 of file repodata.c.
References _Repodata::attrs, MAPTST, repodata_insert_keyid(), and _Repodata::start.
void repodata_create_stubs (Repodata * data)
Definition at line 2773 of file repodata.c.
References _Dataiterator::data, dataiterator_entersub(), dataiterator_free(), dataiterator_init(), dataiterator_step(), _Repodata::end, _KeyValue::eof, _KeyValue::id, _Dataiterator::key, _Dataiterator::kv, _Repodata::loadcallback, _Repokey::name, _Dataiterator::nparents, _KeyValue::num, _Repo::pool, _Repodata::repo, repo_add_repodata(), _Repo::repodata, repodata_add_idarray(), repodata_extend_block(), repodata_internalize(), repodata_key2id(), repodata_set_bin_checksum(), repodata_set_constantid(), repodata_set_id(), repodata_set_num(), repodata_set_str(), repodata_set_void(), sat_calloc(), sat_free(), _Repokey::size, SOLVID_META, _Repodata::start, _Repodata::state, _Repokey::storage, _KeyValue::str, and _Repokey::type.
Referenced by repo_add_solv_flags().
void repodata_join (Repodata * data, Id joinkey)
void repodata_disable_paging (Repodata * data)
Definition at line 2748 of file repodata.c.
References maybe_load_repodata(), repopagestore_disable_paging(), and _Repodata::store.
Referenced by repo_disable_paging().
Id repodata_globalize_id (Repodata * data, Id id, int create)
Definition at line 572 of file repodata.c.
References _Repodata::localpool, _Repo::pool, _Repodata::repo, _Repodata::spool, str2id(), and stringpool_id2str().
Referenced by pool_lookup_id(), and repo_lookup_id().
Id repodata_str2dir (Repodata * data, const char * dir, int create)
Definition at line 242 of file repodata.c.
References _Repodata::dirpool, dirpool_add_dir(), _Repodata::localpool, _Dirpool::ndirs, _Repo::pool, _Repodata::repo, _Repodata::spool, strchrnul(), stringpool_strn2id(), and strn2id().
Referenced by addfileprovides_cb().
const char* repodata_dir2str (Repodata * data, Id did, const char * suf)
Definition at line 278 of file repodata.c.
References _Repodata::dirpool, dirpool_compid(), dirpool_parent(), _Repodata::localpool, _Repo::pool, pool_alloctmpspace(), _Repodata::repo, _Repodata::spool, _Pool::ss, and stringpool_id2str().
Referenced by repodata_stringify().
const char* repodata_chk2str (Repodata * data, Id type, const unsigned char * buf)
Definition at line 2104 of file repodata.c.
References _Repo::pool, pool_alloctmpspace(), _Repodata::repo, subschema_data::s, and sat_chksum_len().
Referenced by pool_lookup_checksum(), repodata_stringify(), and solvable_lookup_checksum().
void repodata_set_location (Repodata * data, Id solvid, int medianr, const char * dir, const char * file)
Definition at line 2137 of file repodata.c.
References _Solvable::arch, _Solvable::evr, evrid2vrstr(), id2str(), _Solvable::name, _Repo::pool, _Repodata::repo, repodata_set_constant(), repodata_set_str(), repodata_set_void(), subschema_data::s, and _Pool::solvables.