satsolver: src/repopack.h File Reference
repopack.h File Reference
Functions
static unsigned char * data_read_id (unsigned char *dp, Id *idp)
static unsigned char * data_read_ideof (unsigned char *dp, Id *idp, int *eof)
static unsigned char * data_read_u32 (unsigned char *dp, unsigned int *nump)
static unsigned char * data_fetch (unsigned char *dp, KeyValue *kv, Repokey *key)
static unsigned char * data_skip (unsigned char *dp, int type)
static unsigned char * data_skip_verify (unsigned char *dp, int type, int maxid, int maxdir)
unsigned char * data_skip_key (Repodata *data, unsigned char *dp, Repokey *key)
Function Documentation
static unsigned char* data_read_id (unsigned char * dp, Id * idp) [inline, static]
Definition at line 14 of file repopack.h.
Referenced by data_fetch(), data_read_id_max(), data_skip(), data_skip_key(), data_skip_verify(), dataiterator_step(), get_data(), repo_add_solv_flags(), repodata_internalize(), repodata_lookup_id(), repodata_lookup_str(), repodata_search(), repodata_serialize_key(), and solvid2data().
static unsigned char* data_read_ideof (unsigned char * dp, Id * idp, int * eof) [inline, static]
Definition at line 31 of file repopack.h.
Referenced by data_fetch(), data_skip_verify(), incore_map_idarray(), and repodata_lookup_idarray().
static unsigned char* data_read_u32 (unsigned char * dp, unsigned int * nump) [inline, static]
Definition at line 55 of file repopack.h.
Referenced by data_fetch(), and repo_add_solv_flags().
static unsigned char* data_fetch (unsigned char * dp, KeyValue * kv, Repokey * key) [inline, static]
Definition at line 62 of file repopack.h.
References data_read_id(), data_read_ideof(), data_read_u32(), _KeyValue::eof, _KeyValue::id, _KeyValue::num, _KeyValue::num2, _Repokey::size, _KeyValue::str, and _Repokey::type.
Referenced by dataiterator_step(), repodata_lookup_num(), and repodata_search().
static unsigned char* data_skip (unsigned char * dp, int type) [inline, static]
Definition at line 121 of file repopack.h.
References data_read_id().
Referenced by data_skip_key(), forward_to_key(), repo_add_solv_flags(), and repodata_internalize().
static unsigned char* data_skip_verify (unsigned char * dp, int type, int maxid, int maxdir) [inline, static]
Definition at line 192 of file repopack.h.
References data_read_id(), and data_read_ideof().
unsigned char* data_skip_key (Repodata * data, unsigned char * dp, Repokey * key)
Definition at line 338 of file repodata.c.
References data_read_id(), data_skip(), data_skip_schema(), KEY_STORAGE_INCORE, KEY_STORAGE_VERTICAL_OFFSET, _Repokey::storage, and _Repokey::type.
Referenced by data_skip_schema(), forward_to_key(), get_data(), and repodata_internalize().