satsolver: src/repodata.c File Reference
repodata.c File Reference
#include <string.h>
#include <fnmatch.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>
#include <regex.h>
#include "repo.h"
#include "pool.h"
#include "poolid_private.h"
#include "util.h"
#include "hash.h"
#include "chksum.h"
#include "repopack.h"
#include "repopage.h"
Classes
struct subschema_data
struct extdata
Defines
#define _GNU_SOURCE
#define REPODATA_BLOCK 255
#define SCHEMATA_BLOCK 31
#define SCHEMATADATA_BLOCK 255
#define REPODATA_ATTRS_BLOCK 31
#define REPODATA_ATTRDATA_BLOCK 1023
#define REPODATA_ATTRIDDATA_BLOCK 63
#define c2h(c)
#define EXTDATA_BLOCK 1023
Enumerations
enum {
di_bye, di_enterrepo, di_entersolvable, di_enterrepodata,
di_enterschema, di_enterkey, di_nextattr, di_nextkey,
di_nextrepodata, di_nextsolvable, di_nextrepo, di_enterarray,
di_nextarrayelement, di_entersub, di_leavesub, di_nextsolvableattr,
di_nextsolvablekey, di_entersolvablekey
}
Functions
unsigned int compress_buf (const unsigned char *in, unsigned int in_len, unsigned char *out, unsigned int out_len)
unsigned int unchecked_decompress_buf (const unsigned char *in, unsigned int in_len, unsigned char *out, unsigned int out_len)
void repodata_initdata (Repodata *data, Repo *repo, int localpool)
void repodata_freedata (Repodata *data)
Repodata * repodata_create (Repo *repo, int localpool)
void repodata_free (Repodata *data)
Id repodata_key2id (Repodata *data, Repokey *key, int create)
Id repodata_schema2id (Repodata *data, Id *schema, int create)
void repodata_free_schemahash (Repodata *data)
char const * strchrnul (char const *str, char x)
Id repodata_str2dir (Repodata *data, const char *dir, int create)
const char * repodata_dir2str (Repodata *data, Id did, const char *suf)
static unsigned char * data_skip_schema (Repodata *data, unsigned char *dp, Id schema)
unsigned char * data_skip_key (Repodata *data, unsigned char *dp, Repokey *key)
static unsigned char * forward_to_key (Repodata *data, Id keyid, Id *keyp, unsigned char *dp)
static unsigned char * get_vertical_data (Repodata *data, Repokey *key, Id off, Id len)
static unsigned char * get_data (Repodata *data, Repokey *key, unsigned char **dpp, int advance)
static int load_repodata (Repodata *data)
static int maybe_load_repodata (Repodata *data, Id keyname)
static unsigned char * solvid2data (Repodata *data, Id solvid, Id *schemap)
static unsigned char * find_key_data (Repodata *data, Id solvid, Id keyname, Repokey **keypp)
Id repodata_lookup_id (Repodata *data, Id solvid, Id keyname)
Id repodata_globalize_id (Repodata *data, Id id, int create)
const char * repodata_lookup_str (Repodata *data, Id solvid, Id keyname)
int repodata_lookup_num (Repodata *data, Id solvid, Id keyname, unsigned int *value)
int repodata_lookup_void (Repodata *data, Id solvid, Id keyname)
const unsigned char * repodata_lookup_bin_checksum (Repodata *data, Id solvid, Id keyname, Id *typep)
int repodata_lookup_idarray (Repodata *data, Id solvid, Id keyname, Queue *q)
int repodata_stringify (Pool *pool, Repodata *data, Repokey *key, KeyValue *kv, int flags)
void repodata_search (Repodata *data, Id solvid, Id keyname, int flags, int(*callback)(void *cbdata, Solvable *s, Repodata *data, Repokey *key, KeyValue *kv), void *cbdata)
void repodata_setpos_kv (Repodata *data, KeyValue *kv)
static Id * solvabledata_fetch (Solvable *s, KeyValue *kv, Id keyname)
int datamatcher_init (Datamatcher *ma, const char *match, int flags)
void datamatcher_free (Datamatcher *ma)
int datamatcher_match (Datamatcher *ma, const char *str)
int repodata_filelistfilter_matches (Repodata *data, const char *str)
int dataiterator_init (Dataiterator *di, Pool *pool, Repo *repo, Id p, Id keyname, const char *match, int flags)
void dataiterator_init_clone (Dataiterator *di, Dataiterator *from)
int dataiterator_set_match (Dataiterator *di, const char *match, int flags)
void dataiterator_set_search (Dataiterator *di, Repo *repo, Id p)
void dataiterator_set_keyname (Dataiterator *di, Id keyname)
void dataiterator_prepend_keyname (Dataiterator *di, Id keyname)
void dataiterator_free (Dataiterator *di)
static unsigned char * dataiterator_find_keyname (Dataiterator *di, Id keyname)
static int dataiterator_filelistcheck (Dataiterator *di)
int dataiterator_step (Dataiterator *di)
void dataiterator_entersub (Dataiterator *di)
void dataiterator_setpos (Dataiterator *di)
void dataiterator_setpos_parent (Dataiterator *di)
void dataiterator_clonepos (Dataiterator *di, Dataiterator *from)
void dataiterator_seek (Dataiterator *di, int whence)
void dataiterator_skip_attribute (Dataiterator *di)
void dataiterator_skip_solvable (Dataiterator *di)
void dataiterator_skip_repo (Dataiterator *di)
void dataiterator_jump_to_solvid (Dataiterator *di, Id solvid)
void dataiterator_jump_to_repo (Dataiterator *di, Repo *repo)
int dataiterator_match (Dataiterator *di, Datamatcher *ma)
void repodata_extend (Repodata *data, Id p)
void repodata_shrink (Repodata *data, int end)
void repodata_extend_block (Repodata *data, Id start, Id num)
Id repodata_new_handle (Repodata *data)
static Id ** repodata_get_attrp (Repodata *data, Id handle)
static void repodata_insert_keyid (Repodata *data, Id handle, Id keyid, Id val, int overwrite)
static void repodata_set (Repodata *data, Id solvid, Repokey *key, Id val)
void repodata_set_id (Repodata *data, Id solvid, Id keyname, Id id)
void repodata_set_num (Repodata *data, Id solvid, Id keyname, unsigned int num)
void repodata_set_poolstr (Repodata *data, Id solvid, Id keyname, const char *str)
void repodata_set_constant (Repodata *data, Id solvid, Id keyname, unsigned int constant)
void repodata_set_constantid (Repodata *data, Id solvid, Id keyname, Id id)
void repodata_set_void (Repodata *data, Id solvid, Id keyname)
void repodata_set_str (Repodata *data, Id solvid, Id keyname, const char *str)
void repodata_set_binary (Repodata *data, Id solvid, Id keyname, void *buf, int len)
static void repodata_add_array (Repodata *data, Id handle, Id keyname, Id keytype, int entrysize)
void repodata_set_bin_checksum (Repodata *data, Id solvid, Id keyname, Id type, const unsigned char *str)
static int hexstr2bytes (unsigned char *buf, const char *str, int buflen)
void repodata_set_checksum (Repodata *data, Id solvid, Id keyname, Id type, const char *str)
const char * repodata_chk2str (Repodata *data, Id type, const unsigned char *buf)
static const char * evrid2vrstr (Pool *pool, Id evrid)
void repodata_set_location (Repodata *data, Id solvid, int medianr, const char *dir, const char *file)
void repodata_add_dirnumnum (Repodata *data, Id solvid, Id keyname, Id dir, Id num, Id num2)
void repodata_add_dirstr (Repodata *data, Id solvid, Id keyname, Id dir, const char *str)
void repodata_add_idarray (Repodata *data, Id solvid, Id keyname, Id id)
void repodata_add_poolstr_array (Repodata *data, Id solvid, Id keyname, const char *str)
void repodata_add_fixarray (Repodata *data, Id solvid, Id keyname, Id ghandle)
void repodata_add_flexarray (Repodata *data, Id solvid, Id keyname, Id ghandle)
void repodata_delete_uninternalized (Repodata *data, Id solvid, Id keyname)
void repodata_merge_attrs (Repodata *data, Id dest, Id src)
void repodata_merge_some_attrs (Repodata *data, Id dest, Id src, Map *keyidmap, int overwrite)
static void data_addid (struct extdata *xd, Id x)
static void data_addideof (struct extdata *xd, Id x, int eof)
static void data_addblob (struct extdata *xd, unsigned char *blob, int len)
static void repodata_serialize_key (Repodata *data, struct extdata *newincore, struct extdata *newvincore, Id *schema, Repokey *key, Id val)
void repodata_internalize (Repodata *data)
void repodata_disable_paging (Repodata *data)
static void repodata_load_stub (Repodata *data)
void repodata_create_stubs (Repodata *data)
Variables
static Repokey solvablekeys [RPM_RPMDBID-SOLVABLE_NAME+1]
Define Documentation
#define _GNU_SOURCE
Definition at line 17 of file repodata.c.
#define REPODATA_BLOCK 255
Definition at line 44 of file repodata.c.
Referenced by repodata_extend(), repodata_extend_block(), repodata_get_attrp(), repodata_new_handle(), and repodata_shrink().
#define SCHEMATA_BLOCK 31
Definition at line 164 of file repodata.c.
Referenced by repodata_schema2id().
#define SCHEMATADATA_BLOCK 255
Definition at line 165 of file repodata.c.
Referenced by repodata_schema2id().
#define REPODATA_ATTRS_BLOCK 31
Definition at line 1785 of file repodata.c.
Referenced by repodata_insert_keyid().
#define REPODATA_ATTRDATA_BLOCK 1023
Definition at line 1786 of file repodata.c.
Referenced by repodata_add_dirstr(), repodata_set_bin_checksum(), repodata_set_binary(), and repodata_set_str().
#define REPODATA_ATTRIDDATA_BLOCK 63
Definition at line 1787 of file repodata.c.
Referenced by repodata_add_array().
#define c2h (c)
Value:
(((c)>='0' && (c)<='9') ? ((c)-'0')             \
                : ((c)>='a' && (c)<='f') ? ((c)-('a'-10))       \
                : ((c)>='A' && (c)<='F') ? ((c)-('A'-10))       \
                : -1)
Referenced by hexstr2bytes().
#define EXTDATA_BLOCK 1023
Definition at line 2333 of file repodata.c.
Referenced by data_addblob(), and data_addid().
Enumeration Type Documentation
anonymous enum
Enumerator:
di_bye
di_enterrepo
di_entersolvable
di_enterrepodata
di_enterschema
di_enterkey
di_nextattr
di_nextkey
di_nextrepodata
di_nextsolvable
di_nextrepo
di_enterarray
di_nextarrayelement
di_entersub
di_leavesub
di_nextsolvableattr
di_nextsolvablekey
di_entersolvablekey
Definition at line 1049 of file repodata.c.
Function Documentation
unsigned int compress_buf (const unsigned char * in, unsigned int in_len, unsigned char * out, unsigned int out_len)
Referenced by repopagestore_compress_page().
unsigned int unchecked_decompress_buf (const unsigned char * in, unsigned int in_len, unsigned char * out, unsigned int out_len)
Referenced by repopagestore_load_page_range(), and repopagestore_read_or_setup_pages().
void repodata_initdata (Repodata * data, Repo * repo, int localpool)
Definition at line 48 of file repodata.c.
References _Repodata::keys, _Repodata::localpool, _Repodata::nkeys, _Repodata::nschemata, _Repodata::repo, repopagestore_init(), sat_calloc(), _Repodata::schemadata, _Repodata::schemadatalen, _Repodata::schemata, _Repodata::spool, _Repodata::store, and stringpool_init_empty().
Referenced by repo_add_repodata(), and repodata_create().
void repodata_freedata (Repodata * data)
Definition at line 65 of file repodata.c.
References _Repodata::attrdata, _Repodata::attriddata, _Repodata::attrs, _Repodata::dirpool, dirpool_free(), _Repodata::end, _Repodata::incoredata, _Repodata::incoreoffset, _Repodata::keys, _Repodata::mainschemaoffsets, _Repodata::nxattrs, repopagestore_free(), sat_free(), _Repodata::schemadata, _Repodata::schemata, _Repodata::schematahash, _Repodata::spool, _Repodata::start, _Repodata::store, stringpool_free(), _Repodata::verticaloffset, _Repodata::vincore, and _Repodata::xattrs.
Referenced by repo_add_repodata(), repo_add_solv_flags(), repo_empty(), repo_freedata(), and repodata_free().
Repodata* repodata_create (Repo * repo, int localpool)
Definition at line 101 of file repodata.c.
References _Repo::nrepodata, _Repo::repodata, repodata_initdata(), and sat_realloc2().
Referenced by repo_add_repodata().
void repodata_free (Repodata * data)
Definition at line 113 of file repodata.c.
References _Repo::nrepodata, _Repodata::repo, _Repo::repodata, and repodata_freedata().
Id repodata_key2id (Repodata * data, Repokey * key, int create)
Definition at line 131 of file repodata.c.
References _Repodata::keybits, _Repodata::keys, _Repokey::name, _Repodata::nkeys, sat_realloc2(), _Repokey::size, _Repokey::type, and _Repodata::verticaloffset.
Referenced by repodata_create_stubs(), repodata_internalize(), and repodata_set().
Id repodata_schema2id (Repodata * data, Id * schema, int create)
Definition at line 168 of file repodata.c.
References _Repodata::nschemata, sat_calloc(), sat_extend(), sat_extend_resize(), _Repodata::schemadata, _Repodata::schemadatalen, _Repodata::schemata, SCHEMATA_BLOCK, SCHEMATADATA_BLOCK, and _Repodata::schematahash.
Referenced by repodata_internalize(), and repodata_serialize_key().
void repodata_free_schemahash (Repodata * data)
Definition at line 221 of file repodata.c.
References _Repodata::nschemata, sat_free(), sat_realloc2(), _Repodata::schemadata, _Repodata::schemadatalen, _Repodata::schemata, and _Repodata::schematahash.
Referenced by repodata_internalize().
char const* strchrnul (char const * str, char x)
Definition at line 230 of file repodata.c.
Referenced by repodata_str2dir().
Id repodata_str2dir (Repodata * data, const char * dir, int create)
Definition at line 242 of file repodata.c.
References _Repodata::dirpool, dirpool_add_dir(), _Repodata::localpool, _Dirpool::ndirs, _Repo::pool, _Repodata::repo, _Repodata::spool, strchrnul(), stringpool_strn2id(), and strn2id().
Referenced by addfileprovides_cb().
const char* repodata_dir2str (Repodata * data, Id did, const char * suf)
Definition at line 278 of file repodata.c.
References _Repodata::dirpool, dirpool_compid(), dirpool_parent(), _Repodata::localpool, _Repo::pool, pool_alloctmpspace(), _Repodata::repo, _Repodata::spool, _Pool::ss, and stringpool_id2str().
Referenced by repodata_stringify().
static unsigned char* data_skip_schema (Repodata * data, unsigned char * dp, Id schema) [inline, static]
Definition at line 329 of file repodata.c.
References data_skip_key(), _Repodata::keys, _Repodata::schemadata, and _Repodata::schemata.
Referenced by data_skip_key(), dataiterator_step(), and repodata_search().
unsigned char* data_skip_key (Repodata * data, unsigned char * dp, Repokey * key)
Definition at line 338 of file repodata.c.
References data_read_id(), data_skip(), data_skip_schema(), KEY_STORAGE_INCORE, KEY_STORAGE_VERTICAL_OFFSET, _Repokey::storage, and _Repokey::type.
Referenced by data_skip_schema(), forward_to_key(), get_data(), and repodata_internalize().
static unsigned char* forward_to_key (Repodata * data, Id keyid, Id * keyp, unsigned char * dp) [static]
Definition at line 372 of file repodata.c.
References data_skip(), data_skip_key(), _Repodata::incoredata, KEY_STORAGE_INCORE, KEY_STORAGE_VERTICAL_OFFSET, _Repodata::keys, _Repodata::mainschema, _Repodata::mainschemaoffsets, _Repodata::schemadata, _Repodata::schemata, and _Repokey::storage.
Referenced by dataiterator_find_keyname(), find_key_data(), and repodata_search().
static unsigned char* get_vertical_data (Repodata * data, Repokey * key, Id off, Id len) [static]
Definition at line 404 of file repodata.c.
References BLOB_PAGESIZE, _Repodata::keys, _Repodata::lastverticaloffset, repopagestore_load_page_range(), _Repokey::size, _Repodata::store, _Repodata::verticaloffset, _Repodata::vincore, and _Repodata::vincorelen.
Referenced by get_data().
static unsigned char* get_data (Repodata * data, Repokey * key, unsigned char ** dpp, int advance) [inline, static]
Definition at line 428 of file repodata.c.
References data_read_id(), data_skip_key(), get_vertical_data(), KEY_STORAGE_INCORE, KEY_STORAGE_VERTICAL_OFFSET, and _Repokey::storage.
Referenced by dataiterator_step(), find_key_data(), and repodata_search().
static int load_repodata (Repodata * data) [static]
Definition at line 453 of file repodata.c.
References _Repodata::loadcallback, REPODATA_AVAILABLE, and _Repodata::state.
Referenced by maybe_load_repodata().
static int maybe_load_repodata (Repodata * data, Id keyname) [inline, static]
Definition at line 466 of file repodata.c.
References _Repodata::keys, load_repodata(), _Repokey::name, _Repodata::nkeys, REPODATA_AVAILABLE, REPODATA_ERROR, REPODATA_LOADING, repodata_precheck_keyname(), REPODATA_STUB, and _Repodata::state.
Referenced by dataiterator_step(), find_key_data(), repodata_disable_paging(), repodata_lookup_void(), and repodata_search().
static unsigned char* solvid2data (Repodata * data, Id solvid, Id * schemap) [inline, static]
Definition at line 495 of file repodata.c.
References data_read_id(), _Repopos::dp, _Repodata::end, _Repodata::incoredata, _Repodata::incoreoffset, _Repo::pool, _Pool::pos, _Repopos::repo, _Repodata::repo, _Repo::repodata, _Repopos::repodataid, _Repopos::schema, SOLVID_META, SOLVID_POS, and _Repodata::start.
Referenced by dataiterator_step(), find_key_data(), repodata_lookup_void(), and repodata_search().
static unsigned char* find_key_data (Repodata * data, Id solvid, Id keyname, Repokey ** keypp) [inline, static]
Definition at line 526 of file repodata.c.
References forward_to_key(), get_data(), _Repodata::keys, maybe_load_repodata(), _Repokey::name, _Repodata::schemadata, _Repodata::schemata, solvid2data(), and _Repokey::type.
Referenced by repodata_lookup_bin_checksum(), repodata_lookup_id(), repodata_lookup_idarray(), repodata_lookup_num(), and repodata_lookup_str().
Id repodata_lookup_id (Repodata * data, Id solvid, Id keyname)
Definition at line 554 of file repodata.c.
References data_read_id(), find_key_data(), _Repokey::size, and _Repokey::type.
Referenced by pool_lookup_id(), and repo_lookup_id().
Id repodata_globalize_id (Repodata * data, Id id, int create)
Definition at line 572 of file repodata.c.
References _Repodata::localpool, _Repo::pool, _Repodata::repo, _Repodata::spool, str2id(), and stringpool_id2str().
Referenced by pool_lookup_id(), and repo_lookup_id().
const char* repodata_lookup_str (Repodata * data, Id solvid, Id keyname)
Definition at line 580 of file repodata.c.
References data_read_id(), find_key_data(), id2str(), _Repodata::localpool, _Repo::pool, _Repodata::repo, _Repokey::size, _Repodata::spool, _Stringpool::strings, _Stringpool::stringspace, and _Repokey::type.
Referenced by pool_lookup_str(), and repo_lookup_str().
int repodata_lookup_num (Repodata * data, Id solvid, Id keyname, unsigned int * value)
Definition at line 603 of file repodata.c.
References data_fetch(), find_key_data(), _KeyValue::num, and _Repokey::type.
Referenced by pool_lookup_num(), repo_lookup_num(), and solvable_lookup_bool().
int repodata_lookup_void (Repodata * data, Id solvid, Id keyname)
Definition at line 625 of file repodata.c.
References _Repodata::keys, maybe_load_repodata(), _Repokey::name, _Repodata::schemadata, _Repodata::schemata, solvid2data(), and _Repokey::type.
Referenced by pool_lookup_void(), repo_lookup_void(), and solvable_lookup_bool().
const unsigned char* repodata_lookup_bin_checksum (Repodata * data, Id solvid, Id keyname, Id * typep)
Definition at line 644 of file repodata.c.
References find_key_data(), and _Repokey::type.
Referenced by pool_lookup_bin_checksum(), pool_lookup_checksum(), and repo_lookup_bin_checksum().
int repodata_lookup_idarray (Repodata * data, Id solvid, Id keyname, Queue * q)
Definition at line 657 of file repodata.c.
References data_read_ideof(), find_key_data(), queue_empty(), and queue_push().
Referenced by pool_addfileprovides_search().
int repodata_stringify (Pool * pool, Repodata * data, Repokey * key, KeyValue * kv, int flags)
Definition at line 684 of file repodata.c.
References _KeyValue::id, id2str(), KEY_STORAGE_SOLVABLE, _Repodata::localpool, repodata_chk2str(), repodata_dir2str(), SEARCH_CHECKSUMS, SEARCH_FILES, SEARCH_SKIP_KIND, _Repodata::spool, _Repokey::storage, _KeyValue::str, stringpool_id2str(), and _Repokey::type.
Referenced by dataiterator_match(), dataiterator_step(), and repo_matchvalue().
void repodata_search (Repodata * data, Id solvid, Id keyname, int flags, int(*)(void *cbdata, Solvable *s, Repodata *data, Repokey *key, KeyValue *kv) callback, void * cbdata)
Definition at line 737 of file repodata.c.
References subschema_data::cbdata, data_fetch(), data_read_id(), data_skip_schema(), _KeyValue::entry, _KeyValue::eof, forward_to_key(), get_data(), _KeyValue::id, _Repodata::keys, maybe_load_repodata(), _Repokey::name, _KeyValue::num, _KeyValue::parent, subschema_data::parent, _Repo::pool, _Repodata::repo, subschema_data::s, _Repodata::schemadata, _Repodata::schemata, SEARCH_ARRAYSENTINEL, SEARCH_ENTERSUB, SEARCH_NEXT_KEY, SEARCH_SUB, _Pool::solvables, solvid2data(), SOLVID_SUBSCHEMA, _KeyValue::str, and _Repokey::type.
Referenced by pool_addfileprovides_search(), and repo_search_md().
void repodata_setpos_kv (Repodata * data, KeyValue * kv)
Definition at line 849 of file repodata.c.
References _Repopos::dp, _KeyValue::id, _Repodata::incoredata, _Repo::pool, pool_clear_pos(), _Pool::pos, _Repopos::repo, _Repodata::repo, _Repo::repodata, _Repopos::repodataid, _Repopos::schema, and _KeyValue::str.
static Id* solvabledata_fetch (Solvable * s, KeyValue * kv, Id keyname) [inline, static]
Definition at line 884 of file repodata.c.
References _Solvable::arch, _Solvable::conflicts, _Solvable::enhances, _KeyValue::eof, _Solvable::evr, _KeyValue::id, _Repo::idarraydata, _Solvable::name, _Solvable::obsoletes, _Repo::pool, _Solvable::provides, _Solvable::recommends, _Solvable::repo, _Solvable::requires, _Repo::rpmdbid, _Pool::solvables, _Repo::start, _Solvable::suggests, _Solvable::supplements, and _Solvable::vendor.
Referenced by dataiterator_step().
int datamatcher_init (Datamatcher * ma, const char * match, int flags)
Definition at line 934 of file repodata.c.
References _Datamatcher::error, _Datamatcher::flags, _Datamatcher::match, _Datamatcher::matchdata, sat_calloc(), sat_free(), SEARCH_ERROR, SEARCH_NOCASE, SEARCH_REGEX, and SEARCH_STRINGMASK.
Referenced by dataiterator_init(), dataiterator_init_clone(), dataiterator_set_match(), and repo_search().
void datamatcher_free (Datamatcher * ma)
Definition at line 954 of file repodata.c.
References _Datamatcher::flags, _Datamatcher::matchdata, sat_free(), SEARCH_REGEX, and SEARCH_STRINGMASK.
Referenced by dataiterator_free(), dataiterator_set_match(), and repo_search().
int datamatcher_match (Datamatcher * ma, const char * str)
Definition at line 964 of file repodata.c.
References _Datamatcher::flags, _Datamatcher::match, _Datamatcher::matchdata, SEARCH_GLOB, SEARCH_NOCASE, SEARCH_REGEX, SEARCH_STRING, SEARCH_STRINGEND, SEARCH_STRINGMASK, SEARCH_STRINGSTART, and SEARCH_SUBSTRING.
Referenced by dataiterator_match(), dataiterator_step(), and repo_matchvalue().
int repodata_filelistfilter_matches (Repodata * data, const char * str)
Definition at line 1035 of file repodata.c.
Referenced by dataiterator_filelistcheck(), and pool_addfileprovides_search().
int dataiterator_init (Dataiterator * di, Pool * pool, Repo * repo, Id p, Id keyname, const char * match, int flags)
Definition at line 1077 of file repodata.c.
References dataiterator_set_search(), datamatcher_init(), _Dataiterator::flags, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::matcher, _Repo::pool, _Dataiterator::pool, and _Dataiterator::state.
Referenced by repodata_create_stubs(), and solvable_lookup_idarray().
void dataiterator_init_clone (Dataiterator * di, Dataiterator * from)
Definition at line 1103 of file repodata.c.
References datamatcher_init(), _Datamatcher::flags, _Dataiterator::kv, _Dataiterator::di_parent::kv, _Datamatcher::match, _Dataiterator::matcher, _Dataiterator::nparents, _KeyValue::parent, and _Dataiterator::parents.
int dataiterator_set_match (Dataiterator * di, const char * match, int flags)
Definition at line 1120 of file repodata.c.
References datamatcher_free(), datamatcher_init(), _Dataiterator::flags, _Dataiterator::matcher, SEARCH_THISSOLVID, and _Dataiterator::state.
void dataiterator_set_search (Dataiterator * di, Repo * repo, Id p)
Definition at line 1138 of file repodata.c.
References dataiterator_jump_to_solvid(), _Dataiterator::flags, _Dataiterator::nparents, _Pool::nrepos, _Dataiterator::pool, _Dataiterator::repo, _Dataiterator::repodataid, _Dataiterator::repoid, _Pool::repos, _Dataiterator::rootlevel, and _Dataiterator::state.
Referenced by dataiterator_init().
void dataiterator_set_keyname (Dataiterator * di, Id keyname)
Definition at line 1162 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, and _Dataiterator::nkeynames.
void dataiterator_prepend_keyname (Dataiterator * di, Id keyname)
Definition at line 1170 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::nkeynames, and _Dataiterator::state.
void dataiterator_free (Dataiterator * di)
Definition at line 1186 of file repodata.c.
References datamatcher_free(), _Datamatcher::match, and _Dataiterator::matcher.
Referenced by repodata_create_stubs(), and solvable_lookup_idarray().
static unsigned char* dataiterator_find_keyname (Dataiterator * di, Id keyname) [inline, static]
Definition at line 1193 of file repodata.c.
References _Dataiterator::data, _Dataiterator::dp, forward_to_key(), _Dataiterator::keyp, and _Repodata::keys.
Referenced by dataiterator_step().
static int dataiterator_filelistcheck (Dataiterator * di) [static]
Definition at line 1212 of file repodata.c.
References _Dataiterator::data, _Datamatcher::flags, _Repodata::keys, _Datamatcher::match, _Dataiterator::matcher, _Repokey::name, _Repodata::nkeys, REPODATA_AVAILABLE, repodata_filelistfilter_matches(), SEARCH_COMPLETE_FILELIST, SEARCH_GLOB, SEARCH_NOCASE, SEARCH_STRING, SEARCH_STRINGMASK, and _Repodata::state.
Referenced by dataiterator_step().
int dataiterator_step (Dataiterator * di)
Definition at line 1233 of file repodata.c.
References _Dataiterator::data, data_fetch(), data_read_id(), data_skip_schema(), dataiterator_filelistcheck(), dataiterator_find_keyname(), datamatcher_match(), _Dataiterator::ddp, di_bye, di_enterarray, di_enterkey, di_enterrepo, di_enterrepodata, di_enterschema, di_entersolvable, di_entersolvablekey, di_entersub, di_leavesub, di_nextarrayelement, di_nextattr, di_nextkey, di_nextrepo, di_nextrepodata, di_nextsolvable, di_nextsolvableattr, di_nextsolvablekey, _Repo::disabled, _Dataiterator::di_parent::dp, _Dataiterator::dp, _Repo::end, _KeyValue::entry, _KeyValue::eof, _Datamatcher::flags, _Dataiterator::flags, get_data(), _KeyValue::id, _Dataiterator::idp, _Dataiterator::key, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::di_parent::keyp, _Dataiterator::keyp, _Repodata::keys, _Dataiterator::di_parent::kv, _Dataiterator::kv, _Datamatcher::match, _Dataiterator::matcher, maybe_load_repodata(), _Repokey::name, _Dataiterator::nkeynames, _Dataiterator::nparents, _Repo::nrepodata, _Pool::nrepos, _KeyValue::num, _KeyValue::parent, _Dataiterator::parents, _Dataiterator::pool, _Pool::pos, _Solvable::repo, _Dataiterator::repo, _Repo::repodata, repodata_stringify(), _Dataiterator::repodataid, _Dataiterator::repoid, _Pool::repos, _Dataiterator::rootlevel, _Repodata::schemadata, _Repodata::schemata, SEARCH_ARRAYSENTINEL, SEARCH_DISABLED_REPOS, SEARCH_FILES, SEARCH_NO_STORAGE_SOLVABLE, SEARCH_NOCASE, SEARCH_STRING, SEARCH_STRINGMASK, SEARCH_SUB, SEARCH_THISSOLVID, solvabledata_fetch(), _Pool::solvables, _Repopos::solvid, _Dataiterator::solvid, solvid2data(), SOLVID_POS, _Repo::start, _Dataiterator::state, _KeyValue::str, and _Repokey::type.
Referenced by repodata_create_stubs(), and solvable_lookup_idarray().
void dataiterator_entersub (Dataiterator * di)
Definition at line 1483 of file repodata.c.
References di_nextarrayelement, and _Dataiterator::state.
Referenced by repodata_create_stubs().
void dataiterator_setpos (Dataiterator * di)
Definition at line 1490 of file repodata.c.
References _Dataiterator::data, _Repopos::dp, _KeyValue::eof, _KeyValue::id, _Repodata::incoredata, _Dataiterator::kv, _Dataiterator::pool, pool_clear_pos(), _Pool::pos, _Dataiterator::repo, _Repopos::repo, _Repo::repodata, _Repopos::repodataid, _Repopos::schema, _Dataiterator::solvid, _Repopos::solvid, and _KeyValue::str.
void dataiterator_setpos_parent (Dataiterator * di)
Definition at line 1505 of file repodata.c.
References _Dataiterator::data, _Repopos::dp, _KeyValue::eof, _KeyValue::id, _Repodata::incoredata, _Dataiterator::kv, _KeyValue::parent, _Dataiterator::pool, pool_clear_pos(), _Pool::pos, _Dataiterator::repo, _Repopos::repo, _Repo::repodata, _Repopos::repodataid, _Repopos::schema, _Dataiterator::solvid, _Repopos::solvid, and _KeyValue::str.
void dataiterator_clonepos (Dataiterator * di, Dataiterator * from)
Definition at line 1521 of file repodata.c.
References _Dataiterator::data, _Dataiterator::ddp, _Dataiterator::dp, _Dataiterator::flags, _Dataiterator::idp, _Dataiterator::key, _Dataiterator::keyp, _Dataiterator::di_parent::kv, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::parents, _Dataiterator::repo, _Dataiterator::repodataid, _Dataiterator::repoid, _Dataiterator::rootlevel, _Dataiterator::solvid, and _Dataiterator::state.
void dataiterator_seek (Dataiterator * di, int whence)
Definition at line 1550 of file repodata.c.
References _Dataiterator::data, _Dataiterator::ddp, di_enterschema, di_nextarrayelement, DI_SEEK_CHILD, DI_SEEK_PARENT, DI_SEEK_REWIND, DI_SEEK_STAY, _Dataiterator::di_parent::dp, _Dataiterator::dp, _KeyValue::id, _Dataiterator::key, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::di_parent::keyp, _Dataiterator::keyp, _Repodata::keys, _Dataiterator::di_parent::kv, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::parents, _Dataiterator::rootlevel, _Repodata::schemadata, _Repodata::schemata, _Dataiterator::state, and _KeyValue::str.
void dataiterator_skip_attribute (Dataiterator * di)
Definition at line 1596 of file repodata.c.
References di_nextsolvableattr, and _Dataiterator::state.
void dataiterator_skip_solvable (Dataiterator * di)
Definition at line 1605 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::rootlevel, and _Dataiterator::state.
void dataiterator_skip_repo (Dataiterator * di)
Definition at line 1615 of file repodata.c.
References _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::rootlevel, and _Dataiterator::state.
void dataiterator_jump_to_solvid (Dataiterator * di, Id solvid)
Definition at line 1625 of file repodata.c.
References _Dataiterator::data, _Dataiterator::flags, _Dataiterator::keyname, _Dataiterator::keynames, _Dataiterator::kv, _Dataiterator::nparents, _Pool::nrepos, _KeyValue::parent, _Dataiterator::pool, _Pool::pos, _Solvable::repo, _Repopos::repo, _Dataiterator::repo, _Repo::repodata, _Dataiterator::repodataid, _Repopos::repodataid, _Dataiterator::repoid, _Pool::repos, _Dataiterator::rootlevel, _Pool::solvables, _Dataiterator::solvid, SOLVID_POS, and _Dataiterator::state.
Referenced by dataiterator_set_search().
void dataiterator_jump_to_repo (Dataiterator * di, Repo * repo)
Definition at line 1670 of file repodata.c.
References _Dataiterator::flags, _Dataiterator::kv, _Dataiterator::nparents, _KeyValue::parent, _Dataiterator::repo, _Dataiterator::repodataid, _Dataiterator::repoid, _Dataiterator::rootlevel, _Dataiterator::solvid, and _Dataiterator::state.
int dataiterator_match (Dataiterator * di, Datamatcher * ma)
Definition at line 1684 of file repodata.c.
References _Dataiterator::data, datamatcher_match(), _Dataiterator::flags, _Dataiterator::key, _Dataiterator::kv, _Dataiterator::pool, repodata_stringify(), and _KeyValue::str.
void repodata_extend (Repodata * data, Id p)
Definition at line 1699 of file repodata.c.
References _Repodata::attrs, _Repodata::end, _Repodata::incoreoffset, REPODATA_BLOCK, sat_extend(), sat_extend_resize(), and _Repodata::start.
Referenced by repodata_extend_block(), and repodata_get_attrp().
void repodata_shrink (Repodata * data, int end)
Definition at line 1735 of file repodata.c.
References _Repodata::attrs, _Repodata::end, _Repodata::incoreoffset, REPODATA_BLOCK, sat_extend_resize(), sat_free(), and _Repodata::start.
Referenced by repo_free_solvable_block().
void repodata_extend_block (Repodata * data, Id start, Id num)
Definition at line 1766 of file repodata.c.
References _Repodata::end, _Repodata::incoreoffset, REPODATA_BLOCK, repodata_extend(), sat_calloc_block(), and _Repodata::start.
Referenced by repo_add_solv_flags(), and repodata_create_stubs().
Id repodata_new_handle (Repodata * data)
Definition at line 1791 of file repodata.c.
References _Repodata::nxattrs, REPODATA_BLOCK, sat_calloc_block(), sat_extend(), and _Repodata::xattrs.
static Id** repodata_get_attrp (Repodata * data, Id handle) [inline, static]
Definition at line 1804 of file repodata.c.
References _Repodata::attrs, _Repodata::end, _Repodata::nxattrs, REPODATA_BLOCK, repodata_extend(), sat_calloc_block(), SOLVID_META, _Repodata::start, and _Repodata::xattrs.
Referenced by repodata_add_array(), repodata_delete_uninternalized(), and repodata_insert_keyid().
static void repodata_insert_keyid (Repodata * data, Id handle, Id keyid, Id val, int overwrite) [static]
Definition at line 1824 of file repodata.c.
References _Repodata::keys, _Repokey::name, REPODATA_ATTRS_BLOCK, repodata_get_attrp(), and sat_extend().
Referenced by repodata_merge_attrs(), repodata_merge_some_attrs(), and repodata_set().
static void repodata_set (Repodata * data, Id solvid, Repokey * key, Id val) [static]
Definition at line 1861 of file repodata.c.
References repodata_insert_keyid(), and repodata_key2id().
Referenced by repodata_add_array(), repodata_set_bin_checksum(), repodata_set_binary(), repodata_set_constant(), repodata_set_constantid(), repodata_set_id(), repodata_set_num(), repodata_set_poolstr(), repodata_set_str(), and repodata_set_void().
void repodata_set_id (Repodata * data, Id solvid, Id keyname, Id id)
Definition at line 1870 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repo_set_id(), and repodata_create_stubs().
void repodata_set_num (Repodata * data, Id solvid, Id keyname, unsigned int num)
Definition at line 1881 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repo_set_num(), and repodata_create_stubs().
void repodata_set_poolstr (Repodata * data, Id solvid, Id keyname, const char * str)
Definition at line 1892 of file repodata.c.
References _Repodata::localpool, _Repokey::name, _Repo::pool, _Repodata::repo, repodata_set(), _Repokey::size, _Repodata::spool, _Repokey::storage, str2id(), stringpool_str2id(), and _Repokey::type.
Referenced by repo_set_poolstr().
void repodata_set_constant (Repodata * data, Id solvid, Id keyname, unsigned int constant)
Definition at line 1908 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_set_location().
void repodata_set_constantid (Repodata * data, Id solvid, Id keyname, Id id)
Definition at line 1919 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_create_stubs().
void repodata_set_void (Repodata * data, Id solvid, Id keyname)
Definition at line 1930 of file repodata.c.
References _Repokey::name, repodata_set(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_create_stubs(), and repodata_set_location().
void repodata_set_str (Repodata * data, Id solvid, Id keyname, const char * str)
Definition at line 1941 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repokey::name, REPODATA_ATTRDATA_BLOCK, repodata_set(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repo_set_str(), repodata_create_stubs(), and repodata_set_location().
void repodata_set_binary (Repodata * data, Id solvid, Id keyname, void * buf, int len)
Definition at line 1958 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repokey::name, REPODATA_ATTRDATA_BLOCK, repodata_set(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
static void repodata_add_array (Repodata * data, Id handle, Id keyname, Id keytype, int entrysize) [static]
Definition at line 1989 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, _Repodata::keys, _Repodata::lastdatalen, _Repodata::lasthandle, _Repodata::lastkey, _Repokey::name, REPODATA_ATTRIDDATA_BLOCK, repodata_get_attrp(), repodata_set(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_add_dirnumnum(), repodata_add_dirstr(), repodata_add_fixarray(), repodata_add_flexarray(), and repodata_add_idarray().
void repodata_set_bin_checksum (Repodata * data, Id solvid, Id keyname, Id type, const unsigned char * str)
Definition at line 2046 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repokey::name, REPODATA_ATTRDATA_BLOCK, repodata_set(), sat_chksum_len(), sat_extend(), _Repokey::size, _Repokey::storage, and _Repokey::type.
Referenced by repodata_create_stubs(), and repodata_set_checksum().
static int hexstr2bytes (unsigned char * buf, const char * str, int buflen) [static]
Definition at line 2065 of file repodata.c.
References c2h.
Referenced by repodata_set_checksum().
void repodata_set_checksum (Repodata * data, Id solvid, Id keyname, Id type, const char * str)
Definition at line 2090 of file repodata.c.
References hexstr2bytes(), repodata_set_bin_checksum(), and sat_chksum_len().
const char* repodata_chk2str (Repodata * data, Id type, const unsigned char * buf)
Definition at line 2104 of file repodata.c.
References _Repo::pool, pool_alloctmpspace(), _Repodata::repo, subschema_data::s, and sat_chksum_len().
Referenced by pool_lookup_checksum(), repodata_stringify(), and solvable_lookup_checksum().
static const char* evrid2vrstr (Pool * pool, Id evrid) [inline, static]
Definition at line 2126 of file repodata.c.
References id2str().
Referenced by repodata_set_location().
void repodata_set_location (Repodata * data, Id solvid, int medianr, const char * dir, const char * file)
Definition at line 2137 of file repodata.c.
References _Solvable::arch, _Solvable::evr, evrid2vrstr(), id2str(), _Solvable::name, _Repo::pool, _Repodata::repo, repodata_set_constant(), repodata_set_str(), repodata_set_void(), subschema_data::s, and _Pool::solvables.
void repodata_add_dirnumnum (Repodata * data, Id solvid, Id keyname, Id dir, Id num, Id num2)
Definition at line 2206 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
void repodata_add_dirstr (Repodata * data, Id solvid, Id keyname, Id dir, const char * str)
Definition at line 2220 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repodata::attriddata, _Repodata::attriddatalen, repodata_add_array(), REPODATA_ATTRDATA_BLOCK, and sat_extend().
void repodata_add_idarray (Repodata * data, Id solvid, Id keyname, Id id)
Definition at line 2242 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
Referenced by repodata_add_poolstr_array(), and repodata_create_stubs().
void repodata_add_poolstr_array (Repodata * data, Id solvid, Id keyname, const char * str)
Definition at line 2253 of file repodata.c.
References _Repodata::localpool, _Repo::pool, _Repodata::repo, repodata_add_idarray(), _Repodata::spool, str2id(), and stringpool_str2id().
Referenced by repo_add_poolstr_array().
void repodata_add_fixarray (Repodata * data, Id solvid, Id keyname, Id ghandle)
Definition at line 2265 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
void repodata_add_flexarray (Repodata * data, Id solvid, Id keyname, Id ghandle)
Definition at line 2273 of file repodata.c.
References _Repodata::attriddata, _Repodata::attriddatalen, and repodata_add_array().
void repodata_delete_uninternalized (Repodata * data, Id solvid, Id keyname)
Definition at line 2281 of file repodata.c.
References _Repodata::keys, _Repokey::name, and repodata_get_attrp().
void repodata_merge_attrs (Repodata * data, Id dest, Id src)
Definition at line 2307 of file repodata.c.
References _Repodata::attrs, repodata_insert_keyid(), and _Repodata::start.
void repodata_merge_some_attrs (Repodata * data, Id dest, Id src, Map * keyidmap, int overwrite)
Definition at line 2317 of file repodata.c.
References _Repodata::attrs, MAPTST, repodata_insert_keyid(), and _Repodata::start.
static void data_addid (struct extdata * xd, Id x) [static]
Definition at line 2341 of file repodata.c.
References extdata::buf, EXTDATA_BLOCK, extdata::len, and sat_extend().
Referenced by data_addideof(), repodata_internalize(), and repodata_serialize_key().
static void data_addideof (struct extdata * xd, Id x, int eof) [static]
Definition at line 2363 of file repodata.c.
References data_addid().
Referenced by repodata_serialize_key().
static void data_addblob (struct extdata * xd, unsigned char * blob, int len) [static]
Definition at line 2371 of file repodata.c.
References extdata::buf, EXTDATA_BLOCK, extdata::len, and sat_extend().
Referenced by repodata_internalize(), and repodata_serialize_key().
static void repodata_serialize_key (Repodata * data, struct extdata * newincore, struct extdata * newvincore, Id * schema, Repokey * key, Id val) [static]
Definition at line 2381 of file repodata.c.
References _Repodata::attrdata, _Repodata::attriddata, data_addblob(), data_addid(), data_addideof(), data_read_id(), id2str(), KEY_STORAGE_VERTICAL_OFFSET, _Repodata::keys, _Repodata::lastverticaloffset, extdata::len, _Repokey::name, _Repo::pool, pool_debug(), _Repodata::repo, repodata_schema2id(), SAT_FATAL, SIZEOF_MD5, SIZEOF_SHA1, SIZEOF_SHA256, _Repokey::storage, _Repokey::type, and _Repodata::xattrs.
Referenced by repodata_internalize().
void repodata_internalize (Repodata * data)
Definition at line 2542 of file repodata.c.
References _Repodata::attrdata, _Repodata::attrdatalen, _Repodata::attriddata, _Repodata::attriddatalen, _Repodata::attrs, extdata::buf, data_addblob(), data_addid(), data_read_id(), data_skip(), data_skip_key(), _Repodata::end, id2str(), _Repodata::incoredata, _Repodata::incoredatafree, _Repodata::incoredatalen, _Repodata::incoreoffset, KEY_STORAGE_INCORE, KEY_STORAGE_VERTICAL_OFFSET, _Repodata::keys, _Repodata::lastdatalen, _Repodata::lasthandle, _Repodata::lastkey, extdata::len, _Repodata::mainschema, _Repodata::mainschemaoffsets, _Repokey::name, _Repodata::nkeys, _Repodata::nxattrs, _Repo::pool, pool_debug(), _Repodata::repo, repodata_free_schemahash(), repodata_key2id(), repodata_schema2id(), repodata_serialize_key(), sat_calloc(), SAT_FATAL, sat_free(), sat_malloc2(), _Repodata::schemadata, _Repodata::schemata, _Repokey::size, _Repodata::start, _Repokey::storage, _Repokey::type, _Repodata::vincore, _Repodata::vincorelen, and _Repodata::xattrs.
Referenced by repo_internalize(), and repodata_create_stubs().
void repodata_disable_paging (Repodata * data)
Definition at line 2748 of file repodata.c.
References maybe_load_repodata(), repopagestore_disable_paging(), and _Repodata::store.
Referenced by repo_disable_paging().
static void repodata_load_stub (Repodata * data) [static]
Definition at line 2755 of file repodata.c.
References _Pool::loadcallback, _Pool::loadcallbackdata, _Repo::pool, _Repodata::repo, and _Repodata::state.
void repodata_create_stubs (Repodata * data)
Definition at line 2773 of file repodata.c.
References _Dataiterator::data, dataiterator_entersub(), dataiterator_free(), dataiterator_init(), dataiterator_step(), _Repodata::end, _KeyValue::eof, _KeyValue::id, _Dataiterator::key, _Dataiterator::kv, _Repodata::loadcallback, _Repokey::name, _Dataiterator::nparents, _KeyValue::num, _Repo::pool, _Repodata::repo, repo_add_repodata(), _Repo::repodata, repodata_add_idarray(), repodata_extend_block(), repodata_internalize(), repodata_key2id(), repodata_set_bin_checksum(), repodata_set_constantid(), repodata_set_id(), repodata_set_num(), repodata_set_str(), repodata_set_void(), sat_calloc(), sat_free(), _Repokey::size, SOLVID_META, _Repodata::start, _Repodata::state, _Repokey::storage, _KeyValue::str, and _Repokey::type.
Referenced by repo_add_solv_flags().
Variable Documentation
Repokey solvablekeys[RPM_RPMDBID-SOLVABLE_NAME+1] [static]
Initial value:
 {
  { SOLVABLE_NAME,        REPOKEY_TYPE_ID, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_ARCH,        REPOKEY_TYPE_ID, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_EVR,         REPOKEY_TYPE_ID, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_VENDOR,      REPOKEY_TYPE_ID, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_PROVIDES,    REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_OBSOLETES,   REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_CONFLICTS,   REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_REQUIRES,    REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_RECOMMENDS,  REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_SUGGESTS,    REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_SUPPLEMENTS, REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { SOLVABLE_ENHANCES,    REPOKEY_TYPE_IDARRAY, 0, KEY_STORAGE_SOLVABLE },
  { RPM_RPMDBID,          REPOKEY_TYPE_U32, 0, KEY_STORAGE_SOLVABLE },
}
Definition at line 867 of file repodata.c.