satsolver: src/repo_solv.h File Reference
repo_solv.h File Reference
#include <stdio.h>
#include "pool.h"
#include "repo.h"
Defines
#define SOLV_ADD_NO_STUBS (1 << 8)
Functions
int repo_add_solv (Repo *repo, FILE *fp)
int repo_add_solv_flags (Repo *repo, FILE *fp, int flags)
Define Documentation
#define SOLV_ADD_NO_STUBS (1 << 8)
Definition at line 28 of file repo_solv.h.
Referenced by repo_add_solv_flags().
Function Documentation
int repo_add_solv (Repo * repo, FILE * fp)
Definition at line 1305 of file repo_solv.c.
References repo_add_solv_flags().
int repo_add_solv_flags (Repo * repo, FILE * fp, int flags)
Definition at line 417 of file repo_solv.c.
References _Solvable::arch, _Solvable::conflicts, DATA_READ_CHUNK, data_read_id(), data_read_id_max(), data_read_idarray(), data_read_rel_idarray(), data_read_u32(), data_skip(), dep2str(), _Repodata::dirpool, _Dirpool::dirs, _Repodata::end, _Solvable::enhances, _Repodata::error, _Solvable::evr, _Reldep::evr, _Reldep::flags, _Repodata::fp, HASHCHAIN_NEXT, id2str(), _Repo::idarraydata, _Repo::idarraysize, incore_add_blob(), incore_add_id(), incore_add_u32(), incore_map_idarray(), _Repodata::incoredata, _Repodata::incoredatafree, _Repodata::incoredatalen, _Repodata::incoreoffset, INTERESTED_END, INTERESTED_START, KEY_STORAGE_INCORE, KEY_STORAGE_SOLVABLE, KEY_STORAGE_VERTICAL_OFFSET, _Repodata::keybits, _Repodata::keys, _Repo::lastoff, _Repodata::lastverticaloffset, _Repodata::localpool, _Repodata::mainschema, _Repodata::mainschemaoffsets, MAKERELDEP, mkmask(), _Solvable::name, _Repokey::name, _Reldep::name, _Dirpool::ndirs, _Repodata::nkeys, _Pool::nrels, _Repo::nrepodata, _Repodata::nschemata, _Repo::nsolvables, _Stringpool::nstrings, _Solvable::obsoletes, _Repo::pool, POOL_DEBUG, pool_debug(), pool_freeidhashes(), pool_id2solvable(), pool_shrink_rels(), pool_shrink_strings(), _Solvable::provides, read_id(), read_idarray(), read_u32(), read_u8(), _Solvable::recommends, relhash(), _Pool::rels, _Solvable::repo, _Repodata::repo, repo_add_repodata(), repo_add_solvable_block(), repo_free_solvable_block(), REPO_LOCALPOOL, repo_reserve_ids(), REPO_REUSE_REPODATA, repo_sidedata_create(), REPO_USE_LOADING, _Repo::repodata, repodata_create_stubs(), repodata_extend_block(), repodata_freedata(), repopagestore_init(), repopagestore_read_or_setup_pages(), _Solvable::requires, _Repo::rpmdbid, sat_calloc(), SAT_DEBUG_STATS, SAT_ERROR, sat_free(), sat_malloc(), sat_malloc2(), sat_realloc(), sat_realloc2(), sat_timems(), _Repodata::schemadata, _Repodata::schemadatalen, _Repodata::schemata, _Repokey::size, SOLV_ADD_NO_STUBS, SOLV_FLAG_PREFIX_POOL, SOLV_VERSION_8, _Pool::solvables, _Repodata::spool, _Pool::ss, _Stringpool::sstrings, _Repo::start, _Repodata::start, _Repokey::storage, _Repodata::store, str2id(), strhash(), stringpool_id2str(), _Stringpool::strings, _Stringpool::stringspace, _Solvable::suggests, _Solvable::supplements, _Repokey::type, _Solvable::vendor, and _Repodata::verticaloffset.
Referenced by repo_add_solv().