satsolver: src/repopage.h File Reference
repopage.h File Reference
Classes
struct _Attrblobpage
struct _Repopagestore
Defines
#define BLOB_PAGEBITS 15
#define BLOB_PAGESIZE (1 << BLOB_PAGEBITS)
Typedefs
typedef struct _Attrblobpage Attrblobpage
typedef struct _Repopagestore Repopagestore
Functions
void repopagestore_init (Repopagestore *store)
void repopagestore_free (Repopagestore *store)
unsigned char * repopagestore_load_page_range (Repopagestore *store, unsigned int pstart, unsigned int pend)
unsigned int repopagestore_compress_page (unsigned char *page, unsigned int len, unsigned char *cpage, unsigned int max)
int repopagestore_read_or_setup_pages (Repopagestore *store, FILE *fp, unsigned int pagesz, unsigned int blobsz)
void repopagestore_disable_paging (Repopagestore *store)
Define Documentation
#define BLOB_PAGEBITS 15
Definition at line 11 of file repopage.h.
#define BLOB_PAGESIZE (1 << BLOB_PAGEBITS)
Definition at line 12 of file repopage.h.
Referenced by get_vertical_data(), repopagestore_load_page_range(), and repopagestore_read_or_setup_pages().
Typedef Documentation
typedef struct _Attrblobpage Attrblobpage
typedef struct _Repopagestore Repopagestore
Function Documentation
void repopagestore_init (Repopagestore * store)
Definition at line 554 of file repopage.c.
References _Repopagestore::pagefd.
Referenced by repo_add_solv_flags(), and repodata_initdata().
void repopagestore_free (Repopagestore * store)
Definition at line 560 of file repopage.c.
References _Repopagestore::blob_store, _Repopagestore::mapped, _Repopagestore::pagefd, _Repopagestore::pages, and sat_free().
Referenced by repodata_freedata().
unsigned char* repopagestore_load_page_range (Repopagestore * store, unsigned int pstart, unsigned int pend)
Definition at line 573 of file repopage.c.
References BLOB_PAGESIZE, _Repopagestore::blob_store, _Attrblobpage::file_offset, _Attrblobpage::file_size, _Repopagestore::mapped, _Attrblobpage::mapped_at, _Repopagestore::ncanmap, _Repopagestore::pagefd, _Repopagestore::pages, _Repopagestore::rr_counter, sat_realloc2(), and unchecked_decompress_buf().
Referenced by get_vertical_data(), and repopagestore_disable_paging().
unsigned int repopagestore_compress_page (unsigned char * page, unsigned int len, unsigned char * cpage, unsigned int max)
Definition at line 734 of file repopage.c.
References compress_buf().
int repopagestore_read_or_setup_pages (Repopagestore * store, FILE * fp, unsigned int pagesz, unsigned int blobsz)
Definition at line 762 of file repopage.c.
References BLOB_PAGESIZE, _Repopagestore::blob_store, _Attrblobpage::file_offset, _Attrblobpage::file_size, _Attrblobpage::mapped_at, _Repopagestore::num_pages, _Repopagestore::pagefd, _Repopagestore::pages, read_u32(), sat_malloc2(), and unchecked_decompress_buf().
Referenced by repo_add_solv_flags().
void repopagestore_disable_paging (Repopagestore * store)
Definition at line 850 of file repopage.c.
References _Repopagestore::num_pages, and repopagestore_load_page_range().
Referenced by repodata_disable_paging().