satsolver: src/rules.h File Reference
rules.h File Reference
Classes
struct _Rule
Defines
#define SOLVER_RULE_TYPEMASK 0xff00
Typedefs
typedef struct _Rule Rule
Enumerations
enum SolverRuleinfo {
SOLVER_RULE_UNKNOWN = 0, SOLVER_RULE_RPM = 0x100, SOLVER_RULE_RPM_NOT_INSTALLABLE, SOLVER_RULE_RPM_NOTHING_PROVIDES_DEP,
SOLVER_RULE_RPM_PACKAGE_REQUIRES, SOLVER_RULE_RPM_SELF_CONFLICT, SOLVER_RULE_RPM_PACKAGE_CONFLICT, SOLVER_RULE_RPM_SAME_NAME,
SOLVER_RULE_RPM_PACKAGE_OBSOLETES, SOLVER_RULE_RPM_IMPLICIT_OBSOLETES, SOLVER_RULE_RPM_INSTALLEDPKG_OBSOLETES, SOLVER_RULE_UPDATE = 0x200,
SOLVER_RULE_FEATURE = 0x300, SOLVER_RULE_JOB = 0x400, SOLVER_RULE_JOB_NOTHING_PROVIDES_DEP, SOLVER_RULE_DISTUPGRADE = 0x500,
SOLVER_RULE_INFARCH = 0x600, SOLVER_RULE_CHOICE = 0x700, SOLVER_RULE_LEARNT = 0x800
}
Functions
static void solver_disablerule (struct _Solver *solv, Rule *r)
static void solver_enablerule (struct _Solver *solv, Rule *r)
Rule * solver_addrule (struct _Solver *solv, Id p, Id d)
void solver_unifyrules (struct _Solver *solv)
int solver_samerule (struct _Solver *solv, Rule *r1, Rule *r2)
void solver_addrpmrulesforsolvable (struct _Solver *solv, Solvable *s, Map *m)
void solver_addrpmrulesforweak (struct _Solver *solv, Map *m)
void solver_addrpmrulesforupdaters (struct _Solver *solv, Solvable *s, Map *m, int allow_all)
void solver_addupdaterule (struct _Solver *solv, Solvable *s, int allow_all)
void solver_addinfarchrules (struct _Solver *solv, Map *addedmap)
void solver_createdupmaps (struct _Solver *solv)
void solver_freedupmaps (struct _Solver *solv)
void solver_addduprules (struct _Solver *solv, Map *addedmap)
void solver_disablepolicyrules (struct _Solver *solv)
void solver_reenablepolicyrules (struct _Solver *solv, int jobidx)
int solver_allruleinfos (struct _Solver *solv, Id rid, Queue *rq)
SolverRuleinfo solver_ruleinfo (struct _Solver *solv, Id rid, Id *fromp, Id *top, Id *depp)
void solver_addchoicerules (struct _Solver *solv)
void solver_disablechoicerules (struct _Solver *solv, Rule *r)
Define Documentation
#define SOLVER_RULE_TYPEMASK 0xff00
Definition at line 71 of file rules.h.
Typedef Documentation
typedef struct _Rule Rule
Enumeration Type Documentation
enum SolverRuleinfo
Enumerator:
SOLVER_RULE_UNKNOWN
SOLVER_RULE_RPM
SOLVER_RULE_RPM_NOT_INSTALLABLE
SOLVER_RULE_RPM_NOTHING_PROVIDES_DEP
SOLVER_RULE_RPM_PACKAGE_REQUIRES
SOLVER_RULE_RPM_SELF_CONFLICT
SOLVER_RULE_RPM_PACKAGE_CONFLICT
SOLVER_RULE_RPM_SAME_NAME
SOLVER_RULE_RPM_PACKAGE_OBSOLETES
SOLVER_RULE_RPM_IMPLICIT_OBSOLETES
SOLVER_RULE_RPM_INSTALLEDPKG_OBSOLETES
SOLVER_RULE_UPDATE
SOLVER_RULE_FEATURE
SOLVER_RULE_JOB
SOLVER_RULE_JOB_NOTHING_PROVIDES_DEP
SOLVER_RULE_DISTUPGRADE
SOLVER_RULE_INFARCH
SOLVER_RULE_CHOICE
SOLVER_RULE_LEARNT
Definition at line 49 of file rules.h.
Function Documentation
static void solver_disablerule (struct _Solver * solv, Rule * r) [inline, static]
Definition at line 80 of file rules.h.
References _Rule::d.
Referenced by disableduprule(), disableinfarchrule(), disableupdaterule(), enabledisablelearntrules(), findrecommendedsuggested(), makeruledecisions(), solver_disablechoicerules(), solver_disableproblem(), solver_enableproblem(), and solver_solve().
static void solver_enablerule (struct _Solver * solv, Rule * r) [inline, static]
Definition at line 91 of file rules.h.
References _Rule::d.
Referenced by enabledisablelearntrules(), enableweakrules(), findrecommendedsuggested(), reenableduprule(), reenableinfarchrule(), reenableupdaterule(), refine_suggestion(), solver_disableproblem(), and solver_enableproblem().
Rule* solver_addrule (struct _Solver * solv, Id p, Id d)
Definition at line 259 of file rules.c.
References _Rule::d, IF_POOLDEBUG, _Rule::n1, _Rule::n2, _Solver::nrules, _Rule::p, _Solver::pool, POOL_DEBUG, _Solver::rpmrules_end, _Solver::rules, RULES_BLOCK, SAT_DEBUG_RULE_CREATION, sat_extend(), solver_printrule(), _Rule::w1, _Rule::w2, and _Pool::whatprovidesdata.
Referenced by addrpmrule(), setpropagatelearn(), solver_addchoicerules(), solver_addduprules(), solver_addinfarchrules(), solver_addjobrule(), solver_addupdaterule(), and solver_solve().
void solver_unifyrules (struct _Solver * solv)
Definition at line 133 of file rules.c.
References _Rule::d, IF_POOLDEBUG, _Solver::nrules, _Solver::pool, POOL_DEBUG, _Solver::rules, RULES_BLOCK, SAT_DEBUG_SCHUBI, SAT_DEBUG_STATS, sat_extend_resize(), sat_sort(), unifyrules_sortcmp(), and _Pool::whatprovidesdata.
Referenced by solver_solve().
int solver_samerule (struct _Solver * solv, Rule * r1, Rule * r2)
Definition at line 120 of file rules.c.
References _Solver::pool, and unifyrules_sortcmp().
Referenced by solver_solve().
void solver_addrpmrulesforsolvable (struct _Solver * solv, Solvable * s, Map * m)
Definition at line 452 of file rules.c.
References addrpmrule(), _Pool::allowselfconflicts, _Solvable::arch, _Solvable::conflicts, _Queue::count, dep2str(), _Solvable::evr, _Solver::fixmap, _Solver::fixmap_all, _Reldep::flags, FOR_PROVIDES, GETRELDEP, id2str(), _Repo::idarraydata, IF_POOLDEBUG, _Pool::implicitobsoleteusesprovides, _Solver::installed, ISRELDEP, makemultiversionconflict(), MAPSET, MAPTST, _Reldep::name, _Solvable::name, _Pool::noinstalledobsoletes, _Solver::noobsoletes, _Pool::nscallback, _Pool::nscallbackdata, _Solvable::obsoletes, _Pool::obsoleteusescolors, _Pool::obsoleteusesprovides, _Solver::pool, pool_colormatch(), POOL_DEBUG, pool_installable(), pool_match_nevr(), pool_whatprovides_ptr(), queue_free(), queue_init_buffer(), queue_push(), queue_shift(), _Solvable::recommends, REL_NAMESPACE, _Solvable::repo, _Solvable::requires, SAT_DEBUG_RULE_CREATION, SAT_DEBUG_SCHUBI, _Map::size, solvable2str(), solvable_selfprovidedep(), _Pool::solvables, SOLVER_RULE_RPM_IMPLICIT_OBSOLETES, SOLVER_RULE_RPM_INSTALLEDPKG_OBSOLETES, SOLVER_RULE_RPM_NOT_INSTALLABLE, SOLVER_RULE_RPM_NOTHING_PROVIDES_DEP, SOLVER_RULE_RPM_PACKAGE_CONFLICT, SOLVER_RULE_RPM_PACKAGE_OBSOLETES, SOLVER_RULE_RPM_PACKAGE_REQUIRES, SOLVER_RULE_RPM_SAME_NAME, SOLVER_RULE_RPM_SELF_CONFLICT, solvid2str(), _Repo::start, _Solvable::suggests, SYSTEMSOLVABLE, and _Pool::whatprovidesdata.
Referenced by solver_addrpmrulesforupdaters(), solver_addrpmrulesforweak(), solver_allruleinfos(), solver_ruleinfo(), and solver_solve().
void solver_addrpmrulesforweak (struct _Solver * solv, Map * m)
Definition at line 762 of file rules.c.
References dep_possible(), _Solvable::enhances, _Repo::idarraydata, MAPTST, _Pool::nsolvables, _Solver::pool, POOL_DEBUG, pool_installable(), _Solvable::repo, SAT_DEBUG_SCHUBI, _Pool::solvables, solver_addrpmrulesforsolvable(), and _Solvable::supplements.
Referenced by solver_solve().
void solver_addrpmrulesforupdaters (struct _Solver * solv, Solvable * s, Map * m, int allow_all)
Definition at line 820 of file rules.c.
References _Queue::count, _Queue::elements, MAPTST, policy_findupdatepackages(), _Solver::pool, POOL_DEBUG, queue_free(), queue_init_buffer(), SAT_DEBUG_SCHUBI, _Pool::solvables, and solver_addrpmrulesforsolvable().
Referenced by solver_solve().
void solver_addupdaterule (struct _Solver * solv, Solvable * s, int allow_all)
Definition at line 918 of file rules.c.
References addduppackages(), _Solvable::arch, _Queue::count, _Solver::dupinvolvedmap, _Solver::dupmap_all, _Queue::elements, _Repo::end, _Solvable::evr, finddistupgradepackages(), _Solver::installed, MAPTST, _Solver::multiversionupdaters, _Solvable::name, _Solver::noobsoletes, _Solver::orphaned, policy_findupdatepackages(), _Solver::pool, POOL_DEBUG, pool_queuetowhatprovides(), queue_free(), queue_init_buffer(), queue_push(), queue_shift(), _Solvable::repo, sat_calloc(), SAT_DEBUG_SCHUBI, _Map::size, _Pool::solvables, solver_addrule(), _Repo::start, SYSTEMSOLVABLE, _Solver::updatemap, and _Solver::updatemap_all.
Referenced by solver_solve().
void solver_addinfarchrules (struct _Solver * solv, Map * addedmap)
Definition at line 1036 of file rules.c.
References _Solvable::arch, _Queue::count, _Solver::dupinvolvedmap, _Solver::dupmap_all, _Queue::elements, FOR_PROVIDES, _Pool::id2arch, _Solver::infarchrules, _Solver::infarchrules_end, _Pool::installed, _Pool::lastarch, MAPTST, _Solvable::name, _Solver::nrules, _Pool::nsolvables, _Solver::pool, queue_empty(), queue_free(), queue_init(), queue_push(), queue_pushunique(), _Solvable::repo, _Map::size, _Pool::solvables, solver_addrule(), and SYSTEMSOLVABLE.
Referenced by solver_solve().
void solver_createdupmaps (struct _Solver * solv)
Definition at line 1167 of file rules.c.
References _Queue::count, _Solver::dupinvolvedmap, _Solver::dupmap, _Queue::elements, FOR_PROVIDES, FOR_REPO_SOLVABLES, _Repo::idarraydata, _Solver::job, map_init(), MAPCLR, MAPSET, _Solvable::name, _Pool::nrepos, _Pool::nsolvables, _Solvable::obsoletes, _Pool::obsoleteusescolors, _Pool::obsoleteusesprovides, _Solver::pool, pool_colormatch(), pool_id2repo(), pool_match_nevr(), _Solvable::repo, _Pool::solvables, SOLVER_DISTUPGRADE, SOLVER_JOBMASK, SOLVER_SELECTMASK, SOLVER_SOLVABLE_REPO, and SYSTEMSOLVABLE.
Referenced by solver_solve().
void solver_freedupmaps (struct _Solver * solv)
Definition at line 1227 of file rules.c.
References _Solver::dupmap, and map_free().
Referenced by solver_solve().
void solver_addduprules (struct _Solver * solv, Map * addedmap)
Definition at line 1235 of file rules.c.
References _Solver::dupinvolvedmap, _Solver::dupmap, _Solver::duprules, _Solver::duprules_end, _Repo::end, _Solvable::evr, FOR_PROVIDES, _Solver::installed, map_grow(), MAPSET, MAPTST, _Solvable::name, _Solver::nrules, _Pool::nsolvables, _Solver::pool, _Solvable::repo, _Map::size, solvable_identical(), _Pool::solvables, solver_addrule(), _Repo::start, SYSTEMSOLVABLE, and _Solver::updatemap.
Referenced by solver_solve().
void solver_disablepolicyrules (struct _Solver * solv)
Definition at line 1558 of file rules.c.
References _Solver::cleandepsmap, _Queue::count, _Rule::d, DISABLE_DUP, DISABLE_INFARCH, DISABLE_UPDATE, disableduprule(), disableinfarchrule(), disableupdaterule(), _Queue::elements, _Solver::installed, _Solver::job, _Solver::jobrules, jobtodisablelist(), MAPTST, MAPZERO, _Solver::noupdate, queue_free(), queue_init_buffer(), queue_push2(), _Solver::rules, _Solver::ruletojob, _Map::size, solver_createcleandepsmap(), and _Repo::start.
Referenced by refine_suggestion(), and solver_solve().
void solver_reenablepolicyrules (struct _Solver * solv, int jobidx)
Definition at line 1612 of file rules.c.
References _Solver::cleandepsmap, _Queue::count, _Rule::d, DISABLE_DUP, DISABLE_INFARCH, DISABLE_UPDATE, _Queue::elements, _Solver::installed, _Solver::job, _Solver::jobrules, jobtodisablelist(), MAPTST, queue_free(), queue_init_buffer(), queue_push2(), reenableduprule(), reenableinfarchrule(), reenableupdaterule(), _Solver::rules, _Solver::ruletojob, _Map::size, solver_createcleandepsmap(), and _Repo::start.
Referenced by analyze_unsolvable(), makeruledecisions(), and refine_suggestion().
int solver_allruleinfos (struct _Solver * solv, Id rid, Queue * rq)
Definition at line 1779 of file rules.c.
References _Queue::count, _Rule::d, _Queue::elements, _Rule::p, _Solver::pool, queue_empty(), queue_push(), queue_shift(), _Solver::rpmrules_end, _Solver::ruleinfoq, _Solver::rules, sat_sort(), _Pool::solvables, solver_addrpmrulesforsolvable(), solver_allruleinfos_cmp(), solver_ruleinfo(), and _Rule::w2.
SolverRuleinfo solver_ruleinfo (struct _Solver * solv, Id rid, Id * fromp, Id * top, Id * depp)
Definition at line 1831 of file rules.c.
References _Solver::choicerules, _Queue::count, _Rule::d, _Solver::duprules, _Queue::elements, _Solver::featurerules, _Solver::infarchrules, _Solver::installed, _Solver::job, _Solver::jobrules, _Solver::learntrules, _Solvable::name, _Rule::p, _Solver::pool, queue_free(), queue_init(), queue_push(), _Solver::ruleinfoq, _Solver::rules, _Solver::ruletojob, _Pool::solvables, solver_addrpmrulesforsolvable(), SOLVER_RULE_RPM, SOLVER_SELECTMASK, SOLVER_SOLVABLE_ONE_OF, _Repo::start, SYSTEMSOLVABLE, _Solver::updaterules, and _Rule::w2.
Referenced by solver_allruleinfos(), solver_printproblemruleinfo(), and solver_problemruleinfo().
void solver_addchoicerules (struct _Solver * solv)
Definition at line 1935 of file rules.c.
References _Solver::choicerules, _Solver::choicerules_end, _Solver::choicerules_ref, _Queue::count, _Rule::d, _Solver::duprules, _Queue::elements, _Solver::featurerules, FOR_PROVIDES, FOR_RULELITERALS, _Repo::idarraydata, _Pool::implicitobsoleteusesprovides, _Solver::infarchrules, _Pool::installed, map_empty(), map_free(), map_init(), MAPSET, MAPTST, _Solvable::name, _Solver::nrules, _Pool::nsolvables, _Solvable::obsoletes, _Pool::obsoleteusescolors, _Pool::obsoleteusesprovides, _Rule::p, policy_is_illegal(), _Solver::pool, pool_colormatch(), pool_match_nevr(), pool_queuetowhatprovides(), queue_empty(), queue_free(), queue_init(), queue_push(), _Solvable::repo, _Solver::rpmrules_end, _Solver::rules, sat_calloc(), SAT_DEBUG_RESULT, _Pool::solvables, solver_addrule(), solver_printrule(), _Repo::start, _Solver::updaterules, _Rule::w2, and _Solver::weakruleq.
Referenced by solver_solve().
void solver_disablechoicerules (struct _Solver * solv, Rule * r)
Definition at line 2102 of file rules.c.
References _Solver::choicerules, _Solver::choicerules_ref, _Rule::d, FOR_RULELITERALS, map_init(), MAPCLR, MAPSET, MAPTST, _Pool::nsolvables, _Solver::pool, _Solver::rules, and solver_disablerule().
Referenced by analyze_unsolvable().