satsolver: src/sha1.h File Reference
sha1.h File Reference
#include <stdint.h>
Classes
struct SHA1_CTX
Defines
#define SHA1_DIGEST_SIZE 20
Functions
void sat_SHA1_Init (SHA1_CTX *context)
void sat_SHA1_Update (SHA1_CTX *context, const uint8_t *data, const size_t len)
void sat_SHA1_Final (SHA1_CTX *context, uint8_t digest[SHA1_DIGEST_SIZE])
Define Documentation
#define SHA1_DIGEST_SIZE 20
Definition at line 12 of file sha1.h.
Function Documentation
void sat_SHA1_Init (SHA1_CTX * context)
Definition at line 163 of file sha1.c.
References SHA1_CTX::count, and SHA1_CTX::state.
Referenced by sat_chksum_create().
void sat_SHA1_Update (SHA1_CTX * context, const uint8_t * data, const size_t len)
Definition at line 176 of file sha1.c.
References SHA1_CTX::buffer, SHA1_CTX::count, SHA1_Transform(), and SHA1_CTX::state.
Referenced by sat_chksum_add(), and sat_SHA1_Final().
void sat_SHA1_Final (SHA1_CTX * context, uint8_t digest[SHA1_DIGEST_SIZE])
Definition at line 205 of file sha1.c.
References SHA1_CTX::buffer, SHA1_CTX::count, sat_SHA1_Update(), and SHA1_CTX::state.
Referenced by sat_chksum_get().