satsolver: src/sha2.c File Reference
sha2.c File Reference
#include <sys/types.h>
#include <string.h>
#include <stdio.h>
#include <sysexits.h>
#include <sys/uio.h>
#include <unistd.h>
#include <inttypes.h>
#include "sha2.h"
Defines
#define SHA2_UNROLL_TRANSFORM
#define __BYTE_ORDER __LITTLE_ENDIAN
#define SHA256_SHORT_BLOCK_LENGTH (SHA256_BLOCK_LENGTH - 8)
#define SHA384_SHORT_BLOCK_LENGTH (SHA384_BLOCK_LENGTH - 16)
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
#define REVERSE32(w, x)
#define REVERSE64(w, x)
#define ADDINC128(w, n)
#define SHA2_USE_MEMSET_MEMCPY 1
#define MEMSET_BZERO(p, l) memset((p), 0, (l))
#define MEMCPY_BCOPY(d, s, l) memcpy((d), (s), (l))
#define R(b, x) ((x) >> (b))
#define S32(b, x) (((x) >> (b)) | ((x) << (32 - (b))))
#define S64(b, x) (((x) >> (b)) | ((x) << (64 - (b))))
#define Ch(x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define Maj(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define Sigma0_256(x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
#define Sigma1_256(x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
#define sigma0_256(x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3 , (x)))
#define sigma1_256(x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
#define Sigma0_512(x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
#define Sigma1_512(x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
#define sigma0_512(x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
#define sigma1_512(x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
#define ROUND256_0_TO_15(a, b, c, d, e, f, g, h)
#define ROUND256(a, b, c, d, e, f, g, h)
#define ROUND512_0_TO_15(a, b, c, d, e, f, g, h)
#define ROUND512(a, b, c, d, e, f, g, h)
Typedefs
typedef uint8_t sha2_byte
typedef uint32_t sha2_word32
typedef uint64_t sha2_word64
Functions
static void SHA512_Last (SHA512_CTX *)
static void SHA256_Transform (SHA256_CTX *, const sha2_word32 *)
static void SHA512_Transform (SHA512_CTX *, const sha2_word64 *)
void sat_SHA256_Init (SHA256_CTX *context)
void sat_SHA256_Update (SHA256_CTX *context, const sha2_byte *data, size_t len)
void sat_SHA256_Final (sha2_byte digest[], SHA256_CTX *context)
char * sat_SHA256_End (SHA256_CTX *context, char buffer[])
char * sat_SHA256_Data (const sha2_byte *data, size_t len, char digest[SHA256_DIGEST_STRING_LENGTH])
void sat_SHA512_Init (SHA512_CTX *context)
void sat_SHA512_Update (SHA512_CTX *context, const sha2_byte *data, size_t len)
void sat_SHA512_Final (sha2_byte digest[], SHA512_CTX *context)
char * sat_SHA512_End (SHA512_CTX *context, char buffer[])
char * sat_SHA512_Data (const sha2_byte *data, size_t len, char digest[SHA512_DIGEST_STRING_LENGTH])
void sat_SHA384_Init (SHA384_CTX *context)
void sat_SHA384_Update (SHA384_CTX *context, const sha2_byte *data, size_t len)
void sat_SHA384_Final (sha2_byte digest[], SHA384_CTX *context)
char * sat_SHA384_End (SHA384_CTX *context, char buffer[])
char * sat_SHA384_Data (const sha2_byte *data, size_t len, char digest[SHA384_DIGEST_STRING_LENGTH])
Variables
static const sha2_word32 K256 [64]
static const sha2_word32 sha256_initial_hash_value [8]
static const sha2_word64 K512 [80]
static const sha2_word64 sha384_initial_hash_value [8]
static const sha2_word64 sha512_initial_hash_value [8]
static const char * sha2_hex_digits = "0123456789abcdef"
Define Documentation
#define SHA2_UNROLL_TRANSFORM
Definition at line 68 of file sha2.c.
#define __BYTE_ORDER __LITTLE_ENDIAN
Definition at line 101 of file sha2.c.
#define SHA256_SHORT_BLOCK_LENGTH (SHA256_BLOCK_LENGTH - 8)
Definition at line 132 of file sha2.c.
Referenced by sat_SHA256_Final().
#define SHA384_SHORT_BLOCK_LENGTH (SHA384_BLOCK_LENGTH - 16)
Definition at line 133 of file sha2.c.
#define SHA512_SHORT_BLOCK_LENGTH (SHA512_BLOCK_LENGTH - 16)
Definition at line 134 of file sha2.c.
Referenced by SHA512_Last().
#define REVERSE32 (w, x)
Value:
{ \
        sha2_word32 tmp = (w); \
        tmp = (tmp >> 16) | (tmp << 16); \
        (x) = ((tmp & 0xff00ff00UL) >> 8) | ((tmp & 0x00ff00ffUL) << 8); \
}
Definition at line 139 of file sha2.c.
Referenced by sat_SHA256_Final().
#define REVERSE64 (w, x)
Value:
{ \
        sha2_word64 tmp = (w); \
        tmp = (tmp >> 32) | (tmp << 32); \
        tmp = ((tmp & 0xff00ff00ff00ff00ULL) >> 8) | \
              ((tmp & 0x00ff00ff00ff00ffULL) << 8); \
        (x) = ((tmp & 0xffff0000ffff0000ULL) >> 16) | \
              ((tmp & 0x0000ffff0000ffffULL) << 16); \
}
Definition at line 144 of file sha2.c.
Referenced by sat_SHA256_Final(), sat_SHA384_Final(), sat_SHA512_Final(), and SHA512_Last().
#define ADDINC128 (w, n)
Value:
{ \
        (w)[0] += (sha2_word64)(n); \
        if ((w)[0] < (n)) { \
                (w)[1]++; \
        } \
}
Definition at line 159 of file sha2.c.
Referenced by sat_SHA512_Update().
#define SHA2_USE_MEMSET_MEMCPY 1
Definition at line 177 of file sha2.c.
#define MEMSET_BZERO (p, l) memset((p), 0, (l))
Definition at line 185 of file sha2.c.
Referenced by sat_SHA256_End(), sat_SHA256_Final(), sat_SHA256_Init(), sat_SHA384_End(), sat_SHA384_Final(), sat_SHA384_Init(), sat_SHA512_End(), sat_SHA512_Final(), sat_SHA512_Init(), and SHA512_Last().
#define MEMCPY_BCOPY (d, s, l) memcpy((d), (s), (l))
Definition at line 186 of file sha2.c.
Referenced by sat_SHA256_Final(), sat_SHA256_Init(), sat_SHA256_Update(), sat_SHA384_Final(), sat_SHA384_Init(), sat_SHA512_Final(), sat_SHA512_Init(), and sat_SHA512_Update().
#define R (b, x) ((x) >> (b))
Definition at line 204 of file sha2.c.
#define S32 (b, x) (((x) >> (b)) | ((x) << (32 - (b))))
Definition at line 206 of file sha2.c.
#define S64 (b, x) (((x) >> (b)) | ((x) << (64 - (b))))
Definition at line 208 of file sha2.c.
#define Ch (x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
Definition at line 211 of file sha2.c.
#define Maj (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
Definition at line 212 of file sha2.c.
#define Sigma0_256 (x) (S32(2, (x)) ^ S32(13, (x)) ^ S32(22, (x)))
Definition at line 215 of file sha2.c.
#define Sigma1_256 (x) (S32(6, (x)) ^ S32(11, (x)) ^ S32(25, (x)))
Definition at line 216 of file sha2.c.
#define sigma0_256 (x) (S32(7, (x)) ^ S32(18, (x)) ^ R(3 , (x)))
Definition at line 217 of file sha2.c.
#define sigma1_256 (x) (S32(17, (x)) ^ S32(19, (x)) ^ R(10, (x)))
Definition at line 218 of file sha2.c.
#define Sigma0_512 (x) (S64(28, (x)) ^ S64(34, (x)) ^ S64(39, (x)))
Definition at line 221 of file sha2.c.
#define Sigma1_512 (x) (S64(14, (x)) ^ S64(18, (x)) ^ S64(41, (x)))
Definition at line 222 of file sha2.c.
#define sigma0_512 (x) (S64(1, (x)) ^ S64(8, (x)) ^ R(7, (x)))
Definition at line 223 of file sha2.c.
#define sigma1_512 (x) (S64(19, (x)) ^ S64(61, (x)) ^ R(6, (x)))
Definition at line 224 of file sha2.c.
#define ROUND256_0_TO_15 (a, b, c, d, e, f, g, h)
Value:
REVERSE32(*data++, W256[j]); \
        T1 = (h) + Sigma1_256(e) + Ch((e), (f), (g)) + \
             K256[j] + W256[j]; \
        (d) += T1; \
        (h) = T1 + Sigma0_256(a) + Maj((a), (b), (c)); \
        j++
Definition at line 360 of file sha2.c.
Referenced by SHA256_Transform().
#define ROUND256 (a, b, c, d, e, f, g, h)
Value:
s0 = W256[(j+1)&0x0f]; \
        s0 = sigma0_256(s0); \
        s1 = W256[(j+14)&0x0f]; \
        s1 = sigma1_256(s1); \
        T1 = (h) + Sigma1_256(e) + Ch((e), (f), (g)) + K256[j] + \
             (W256[j&0x0f] += s1 + W256[(j+9)&0x0f] + s0); \
        (d) += T1; \
        (h) = T1 + Sigma0_256(a) + Maj((a), (b), (c)); \
        j++
Definition at line 380 of file sha2.c.
#define ROUND512_0_TO_15 (a, b, c, d, e, f, g, h)
Value:
REVERSE64(*data++, W512[j]); \
        T1 = (h) + Sigma1_512(e) + Ch((e), (f), (g)) + \
             K512[j] + W512[j]; \
        (d) += T1, \
        (h) = T1 + Sigma0_512(a) + Maj((a), (b), (c)), \
        j++
Definition at line 687 of file sha2.c.
Referenced by SHA512_Transform().
#define ROUND512 (a, b, c, d, e, f, g, h)
Value:
s0 = W512[(j+1)&0x0f]; \
        s0 = sigma0_512(s0); \
        s1 = W512[(j+14)&0x0f]; \
        s1 = sigma1_512(s1); \
        T1 = (h) + Sigma1_512(e) + Ch((e), (f), (g)) + K512[j] + \
             (W512[j&0x0f] += s1 + W512[(j+9)&0x0f] + s0); \
        (d) += T1; \
        (h) = T1 + Sigma0_512(a) + Maj((a), (b), (c)); \
        j++
Definition at line 707 of file sha2.c.
Typedef Documentation
typedef uint8_t sha2_byte
Definition at line 125 of file sha2.c.
typedef uint32_t sha2_word32
Definition at line 126 of file sha2.c.
typedef uint64_t sha2_word64
Definition at line 127 of file sha2.c.
Function Documentation
static void SHA512_Last (SHA512_CTX * context) [static]
Definition at line 899 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMSET_BZERO, REVERSE64, SHA512_BLOCK_LENGTH, SHA512_SHORT_BLOCK_LENGTH, and SHA512_Transform().
Referenced by sat_SHA384_Final(), and sat_SHA512_Final().
static void SHA256_Transform (SHA256_CTX * context, const sha2_word32 * data) [static]
Definition at line 391 of file sha2.c.
References _SHA256_CTX::buffer, ROUND256_0_TO_15, and _SHA256_CTX::state.
Referenced by sat_SHA256_Final(), and sat_SHA256_Update().
static void SHA512_Transform (SHA512_CTX * context, const sha2_word64 * data) [static]
Definition at line 718 of file sha2.c.
References _SHA512_CTX::buffer, ROUND512_0_TO_15, and _SHA512_CTX::state.
Referenced by sat_SHA512_Update(), and SHA512_Last().
void sat_SHA256_Init (SHA256_CTX * context)
Definition at line 345 of file sha2.c.
References _SHA256_CTX::bitcount, _SHA256_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, sha256_initial_hash_value, and _SHA256_CTX::state.
Referenced by sat_chksum_create(), and sat_SHA256_Data().
void sat_SHA256_Update (SHA256_CTX * context, const sha2_byte * data, size_t len)
Definition at line 529 of file sha2.c.
References _SHA256_CTX::bitcount, _SHA256_CTX::buffer, MEMCPY_BCOPY, SHA256_BLOCK_LENGTH, and SHA256_Transform().
Referenced by sat_chksum_add(), and sat_SHA256_Data().
void sat_SHA256_Final (sha2_byte digest[], SHA256_CTX * context)
Definition at line 577 of file sha2.c.
References _SHA256_CTX::bitcount, _SHA256_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, REVERSE32, REVERSE64, SHA256_BLOCK_LENGTH, SHA256_DIGEST_LENGTH, SHA256_SHORT_BLOCK_LENGTH, SHA256_Transform(), and _SHA256_CTX::state.
Referenced by sat_chksum_get(), and sat_SHA256_End().
char* sat_SHA256_End (SHA256_CTX * context, char buffer[])
Definition at line 640 of file sha2.c.
References MEMSET_BZERO, sat_SHA256_Final(), SHA256_DIGEST_LENGTH, and sha2_hex_digits.
Referenced by sat_SHA256_Data().
char* sat_SHA256_Data (const sha2_byte * data, size_t len, char digest[SHA256_DIGEST_STRING_LENGTH])
Definition at line 663 of file sha2.c.
References sat_SHA256_End(), sat_SHA256_Init(), and sat_SHA256_Update().
void sat_SHA512_Init (SHA512_CTX * context)
Definition at line 673 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA512_BLOCK_LENGTH, SHA512_DIGEST_LENGTH, sha512_initial_hash_value, and _SHA512_CTX::state.
Referenced by sat_SHA512_Data().
void sat_SHA512_Update (SHA512_CTX * context, const sha2_byte * data, size_t len)
Definition at line 851 of file sha2.c.
References ADDINC128, _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, SHA512_BLOCK_LENGTH, and SHA512_Transform().
Referenced by sat_SHA384_Update(), and sat_SHA512_Data().
void sat_SHA512_Final (sha2_byte digest[], SHA512_CTX * context)
Definition at line 940 of file sha2.c.
References MEMCPY_BCOPY, MEMSET_BZERO, REVERSE64, SHA512_DIGEST_LENGTH, SHA512_Last(), and _SHA512_CTX::state.
Referenced by sat_SHA512_End().
char* sat_SHA512_End (SHA512_CTX * context, char buffer[])
Definition at line 969 of file sha2.c.
References MEMSET_BZERO, sat_SHA512_Final(), sha2_hex_digits, and SHA512_DIGEST_LENGTH.
Referenced by sat_SHA512_Data().
char* sat_SHA512_Data (const sha2_byte * data, size_t len, char digest[SHA512_DIGEST_STRING_LENGTH])
Definition at line 992 of file sha2.c.
References sat_SHA512_End(), sat_SHA512_Init(), and sat_SHA512_Update().
void sat_SHA384_Init (SHA384_CTX * context)
Definition at line 1002 of file sha2.c.
References _SHA512_CTX::bitcount, _SHA512_CTX::buffer, MEMCPY_BCOPY, MEMSET_BZERO, SHA384_BLOCK_LENGTH, sha384_initial_hash_value, SHA512_DIGEST_LENGTH, and _SHA512_CTX::state.
Referenced by sat_SHA384_Data().
void sat_SHA384_Update (SHA384_CTX * context, const sha2_byte * data, size_t len)
Definition at line 1011 of file sha2.c.
References sat_SHA512_Update().
Referenced by sat_SHA384_Data().
void sat_SHA384_Final (sha2_byte digest[], SHA384_CTX * context)
Definition at line 1015 of file sha2.c.
References MEMCPY_BCOPY, MEMSET_BZERO, REVERSE64, SHA384_DIGEST_LENGTH, SHA512_Last(), and _SHA512_CTX::state.
Referenced by sat_SHA384_End().
char* sat_SHA384_End (SHA384_CTX * context, char buffer[])
Definition at line 1044 of file sha2.c.
References MEMSET_BZERO, sat_SHA384_Final(), sha2_hex_digits, and SHA384_DIGEST_LENGTH.
Referenced by sat_SHA384_Data().
char* sat_SHA384_Data (const sha2_byte * data, size_t len, char digest[SHA384_DIGEST_STRING_LENGTH])
Definition at line 1067 of file sha2.c.
References sat_SHA384_End(), sat_SHA384_Init(), and sat_SHA384_Update().
Variable Documentation
const sha2_word32 K256[64] [static]
Initial value:
 {
        0x428a2f98UL, 0x71374491UL, 0xb5c0fbcfUL, 0xe9b5dba5UL,
        0x3956c25bUL, 0x59f111f1UL, 0x923f82a4UL, 0xab1c5ed5UL,
        0xd807aa98UL, 0x12835b01UL, 0x243185beUL, 0x550c7dc3UL,
        0x72be5d74UL, 0x80deb1feUL, 0x9bdc06a7UL, 0xc19bf174UL,
        0xe49b69c1UL, 0xefbe4786UL, 0x0fc19dc6UL, 0x240ca1ccUL,
        0x2de92c6fUL, 0x4a7484aaUL, 0x5cb0a9dcUL, 0x76f988daUL,
        0x983e5152UL, 0xa831c66dUL, 0xb00327c8UL, 0xbf597fc7UL,
        0xc6e00bf3UL, 0xd5a79147UL, 0x06ca6351UL, 0x14292967UL,
        0x27b70a85UL, 0x2e1b2138UL, 0x4d2c6dfcUL, 0x53380d13UL,
        0x650a7354UL, 0x766a0abbUL, 0x81c2c92eUL, 0x92722c85UL,
        0xa2bfe8a1UL, 0xa81a664bUL, 0xc24b8b70UL, 0xc76c51a3UL,
        0xd192e819UL, 0xd6990624UL, 0xf40e3585UL, 0x106aa070UL,
        0x19a4c116UL, 0x1e376c08UL, 0x2748774cUL, 0x34b0bcb5UL,
        0x391c0cb3UL, 0x4ed8aa4aUL, 0x5b9cca4fUL, 0x682e6ff3UL,
        0x748f82eeUL, 0x78a5636fUL, 0x84c87814UL, 0x8cc70208UL,
        0x90befffaUL, 0xa4506cebUL, 0xbef9a3f7UL, 0xc67178f2UL
}
Definition at line 238 of file sha2.c.
const sha2_word32 sha256_initial_hash_value[8] [static]
Initial value:
 {
        0x6a09e667UL,
        0xbb67ae85UL,
        0x3c6ef372UL,
        0xa54ff53aUL,
        0x510e527fUL,
        0x9b05688cUL,
        0x1f83d9abUL,
        0x5be0cd19UL
}
Definition at line 258 of file sha2.c.
Referenced by sat_SHA256_Init().
const sha2_word64 K512[80] [static]
Definition at line 270 of file sha2.c.
const sha2_word64 sha384_initial_hash_value[8] [static]
Initial value:
 {
        0xcbbb9d5dc1059ed8ULL,
        0x629a292a367cd507ULL,
        0x9159015a3070dd17ULL,
        0x152fecd8f70e5939ULL,
        0x67332667ffc00b31ULL,
        0x8eb44a8768581511ULL,
        0xdb0c2e0d64f98fa7ULL,
        0x47b5481dbefa4fa4ULL
}
Definition at line 314 of file sha2.c.
Referenced by sat_SHA384_Init().
const sha2_word64 sha512_initial_hash_value[8] [static]
Initial value:
 {
        0x6a09e667f3bcc908ULL,
        0xbb67ae8584caa73bULL,
        0x3c6ef372fe94f82bULL,
        0xa54ff53a5f1d36f1ULL,
        0x510e527fade682d1ULL,
        0x9b05688c2b3e6c1fULL,
        0x1f83d9abfb41bd6bULL,
        0x5be0cd19137e2179ULL
}
Definition at line 326 of file sha2.c.
Referenced by sat_SHA512_Init().
const char* sha2_hex_digits = "0123456789abcdef" [static]
Definition at line 341 of file sha2.c.
Referenced by sat_SHA256_End(), sat_SHA384_End(), and sat_SHA512_End().