satsolver: src/solvable.c File Reference
solvable.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <unistd.h>
#include <string.h>
#include "pool.h"
#include "repo.h"
#include "util.h"
Functions
const char * solvable2str (Pool *pool, Solvable *s)
Id solvable_lookup_id (Solvable *s, Id keyname)
int solvable_lookup_idarray (Solvable *s, Id keyname, Queue *q)
const char * solvable_lookup_str (Solvable *s, Id keyname)
static const char * solvable_lookup_str_base (Solvable *s, Id keyname, Id basekeyname, int usebase)
const char * solvable_lookup_str_poollang (Solvable *s, Id keyname)
const char * solvable_lookup_str_lang (Solvable *s, Id keyname, const char *lang, int usebase)
unsigned int solvable_lookup_num (Solvable *s, Id keyname, unsigned int notfound)
int solvable_lookup_void (Solvable *s, Id keyname)
int solvable_lookup_bool (Solvable *s, Id keyname)
const unsigned char * solvable_lookup_bin_checksum (Solvable *s, Id keyname, Id *typep)
const char * solvable_lookup_checksum (Solvable *s, Id keyname, Id *typep)
static const char * evrid2vrstr (Pool *pool, Id evrid)
char * solvable_get_location (Solvable *s, unsigned int *medianrp)
static Id dep2name (Pool *pool, Id dep)
static int providedbyinstalled (Pool *pool, Map *installed, Id dep)
int solvable_trivial_installable_map (Solvable *s, Map *installedmap, Map *conflictsmap)
int solvable_trivial_installable_queue (Solvable *s, Queue *installed)
int solvable_trivial_installable_repo (Solvable *s, Repo *installed)
void pool_create_state_maps (Pool *pool, Queue *installed, Map *installedmap, Map *conflictsmap)
int solvable_identical (Solvable *s1, Solvable *s2)
Id solvable_selfprovidedep (Solvable *s)
Function Documentation
const char* solvable2str (Pool * pool, Solvable * s)
Definition at line 25 of file solvable.c.
References _Solvable::arch, _Solvable::evr, id2str(), _Solvable::name, and pool_alloctmpspace().
Referenced by addsolvableedges(), dump_tes(), makeruledecisions(), prune_to_best_version(), solver_addrpmrulesforsolvable(), solver_createcleandepsmap(), solver_printdecisions(), solver_printruleelement(), solver_printsolution(), solver_printtransaction(), solvid2str(), and transaction_check_pkg().
Id solvable_lookup_id (Solvable * s, Id keyname)
Definition at line 38 of file solvable.c.
References _Repo::pool, _Solvable::repo, repo_lookup_id(), and _Pool::solvables.
Referenced by pool_lookup_id().
int solvable_lookup_idarray (Solvable * s, Id keyname, Queue * q)
Definition at line 46 of file solvable.c.
References dataiterator_free(), dataiterator_init(), dataiterator_step(), _KeyValue::eof, _KeyValue::id, _Dataiterator::key, _Dataiterator::kv, _Repo::pool, queue_empty(), queue_push(), _Solvable::repo, SEARCH_ARRAYSENTINEL, _Pool::solvables, and _Repokey::type.
Referenced by addsolvableedges().
const char* solvable_lookup_str (Solvable * s, Id keyname)
Definition at line 69 of file solvable.c.
References _Repo::pool, _Solvable::repo, repo_lookup_str(), and _Pool::solvables.
Referenced by pool_lookup_str(), solvable_get_location(), solvable_lookup_str_base(), solvable_lookup_str_lang(), and solvable_lookup_str_poollang().
static const char* solvable_lookup_str_base (Solvable * s, Id keyname, Id basekeyname, int usebase) [static]
Definition at line 77 of file solvable.c.
References FOR_PROVIDES, _Solvable::name, _Repo::pool, _Solvable::repo, solvable_lookup_str(), _Pool::solvables, _Solvable::vendor, and _Pool::whatprovides.
Referenced by solvable_lookup_str_lang(), and solvable_lookup_str_poollang().
const char* solvable_lookup_str_poollang (Solvable * s, Id keyname)
Definition at line 120 of file solvable.c.
References _Pool::languagecache, _Pool::languagecacheother, _Pool::languages, _Pool::nlanguages, _Repo::pool, pool_id2langid(), _Solvable::repo, sat_calloc(), sat_realloc2(), solvable_lookup_str(), and solvable_lookup_str_base().
const char* solvable_lookup_str_lang (Solvable * s, Id keyname, const char * lang, int usebase)
Definition at line 166 of file solvable.c.
References _Repo::pool, pool_id2langid(), _Solvable::repo, solvable_lookup_str(), and solvable_lookup_str_base().
unsigned int solvable_lookup_num (Solvable * s, Id keyname, unsigned int notfound)
Definition at line 180 of file solvable.c.
References _Repo::pool, _Solvable::repo, repo_lookup_num(), and _Pool::solvables.
Referenced by pool_calc_installsizechange(), pool_lookup_num(), solvable_get_location(), solvable_identical(), and transaction_order().
int solvable_lookup_void (Solvable * s, Id keyname)
Definition at line 188 of file solvable.c.
References _Repo::pool, _Solvable::repo, repo_lookup_void(), and _Pool::solvables.
Referenced by pool_lookup_void(), and solvable_get_location().
int solvable_lookup_bool (Solvable * s, Id keyname)
Definition at line 196 of file solvable.c.
References _Repodata::end, _Repodata::keys, _Repokey::name, _Repodata::nkeys, _Repo::pool, _Solvable::repo, _Repo::repodata, repodata_lookup_num(), repodata_lookup_void(), _Pool::solvables, and _Repokey::type.
const unsigned char* solvable_lookup_bin_checksum (Solvable * s, Id keyname, Id * typep)
Definition at line 232 of file solvable.c.
References _Repo::pool, _Solvable::repo, repo_lookup_bin_checksum(), and _Pool::solvables.
Referenced by pool_lookup_bin_checksum(), and solvable_lookup_checksum().
const char* solvable_lookup_checksum (Solvable * s, Id keyname, Id * typep)
Definition at line 245 of file solvable.c.
References _Solvable::repo, _Repo::repodata, repodata_chk2str(), and solvable_lookup_bin_checksum().
Referenced by pool_lookup_checksum().
static const char* evrid2vrstr (Pool * pool, Id evrid) [inline, static]
Definition at line 253 of file solvable.c.
References id2str().
Referenced by solvable_get_location().
char* solvable_get_location (Solvable * s, unsigned int * medianrp)
Definition at line 264 of file solvable.c.
References _Solvable::arch, _Solvable::evr, evrid2vrstr(), id2str(), _Solvable::name, _Repo::pool, pool_alloctmpspace(), _Solvable::repo, solvable_lookup_num(), solvable_lookup_str(), and solvable_lookup_void().
static Id dep2name (Pool * pool, Id dep) [inline, static]
Definition at line 311 of file solvable.c.
References GETRELDEP, ISRELDEP, and _Reldep::name.
Referenced by solvable_trivial_installable_map().
static int providedbyinstalled (Pool * pool, Map * installed, Id dep) [inline, static]
Definition at line 321 of file solvable.c.
References FOR_PROVIDES, MAPTST, and SYSTEMSOLVABLE.
Referenced by solvable_trivial_installable_map().
int solvable_trivial_installable_map (Solvable * s, Map * installedmap, Map * conflictsmap)
Definition at line 351 of file solvable.c.
References _Solvable::conflicts, dep2name(), FOR_PROVIDES, _Repo::idarraydata, ISRELDEP, MAPTST, _Solvable::name, _Pool::nsolvables, _Solvable::obsoletes, _Repo::pool, pool_whatprovides_ptr(), providedbyinstalled(), _Solvable::repo, _Solvable::requires, and _Pool::solvables.
Referenced by solvable_trivial_installable_queue(), and solvable_trivial_installable_repo().
int solvable_trivial_installable_queue (Solvable * s, Queue * installed)
Definition at line 445 of file solvable.c.
References _Queue::count, _Queue::elements, map_free(), map_init(), MAPSET, _Pool::nsolvables, _Repo::pool, _Solvable::repo, and solvable_trivial_installable_map().
int solvable_trivial_installable_repo (Solvable * s, Repo * installed)
Definition at line 471 of file solvable.c.
References FOR_REPO_SOLVABLES, map_free(), map_init(), MAPSET, _Pool::nsolvables, _Repo::pool, _Solvable::repo, and solvable_trivial_installable_map().
void pool_create_state_maps (Pool * pool, Queue * installed, Map * installedmap, Map * conflictsmap)
Definition at line 499 of file solvable.c.
References _Solvable::conflicts, _Queue::count, _Queue::elements, _Repo::idarraydata, map_init(), MAPSET, _Pool::nsolvables, pool_whatprovides_ptr(), _Solvable::repo, and _Pool::solvables.
Referenced by solver_create_state_maps().
int solvable_identical (Solvable * s1, Solvable * s2)
Definition at line 534 of file solvable.c.
References _Solvable::arch, _Solvable::evr, _Repo::idarraydata, _Solvable::name, _Solvable::repo, _Solvable::requires, solvable_lookup_num(), and _Solvable::vendor.
Referenced by finddistupgradepackages(), prune_installed_dup_packages(), solver_addduprules(), and transaction_base_type().
Id solvable_selfprovidedep (Solvable * s)
Definition at line 577 of file solvable.c.
References _Solvable::evr, _Reldep::evr, _Reldep::flags, GETRELDEP, _Repo::idarraydata, ISRELDEP, _Reldep::name, _Solvable::name, _Repo::pool, _Solvable::provides, rel2id(), REL_EQ, and _Solvable::repo.
Referenced by solver_addrpmrulesforsolvable().