satsolver: src/solverdebug.h File Reference
solverdebug.h File Reference
#include "pooltypes.h"
#include "pool.h"
#include "solver.h"
Functions
Id * solver_create_decisions_obsoletesmap (Solver *solv)
void solver_printruleelement (Solver *solv, int type, Rule *r, Id v)
void solver_printrule (Solver *solv, int type, Rule *r)
void solver_printruleclass (Solver *solv, int type, Rule *r)
void solver_printproblem (Solver *solv, Id v)
void solver_printwatches (Solver *solv, int type)
void solver_printdecisionq (Solver *solv, int type)
void solver_printdecisions (Solver *solv)
void solver_printtransaction (Solver *solv)
void solver_printprobleminfo (Solver *solv, Id problem)
void solver_printcompleteprobleminfo (Solver *solv, Id problem)
void solver_printsolution (Solver *solv, Id problem, Id solution)
void solver_printallsolutions (Solver *solv)
void solver_printtrivial (Solver *solv)
const char * solver_select2str (Pool *pool, Id select, Id what)
Function Documentation
Id* solver_create_decisions_obsoletesmap (Solver * solv)
Definition at line 44 of file solverdebug.c.
References _Solvable::arch, _Queue::count, _Solver::decisionq, _Queue::elements, _Solvable::evr, FOR_PROVIDES, _Repo::idarraydata, _Pool::implicitobsoleteusesprovides, _Solver::installed, MAPTST, _Solvable::name, _Solver::noobsoletes, _Pool::nsolvables, _Solvable::obsoletes, _Pool::obsoleteusescolors, _Pool::obsoleteusesprovides, _Solver::pool, pool_colormatch(), pool_match_nevr(), _Solvable::repo, sat_calloc(), _Map::size, _Pool::solvables, and SYSTEMSOLVABLE.
void solver_printruleelement (Solver * solv, int type, Rule * r, Id v)
Definition at line 125 of file solverdebug.c.
References _Solver::decisionmap, _Pool::installed, _Solver::pool, POOL_DEBUG, _Solvable::repo, solvable2str(), _Pool::solvables, _Rule::w1, and _Rule::w2.
Referenced by analyze(), propagate(), setpropagatelearn(), solver_printdecisions(), and solver_printrule().
void solver_printrule (Solver * solv, int type, Rule * r)
Definition at line 161 of file solverdebug.c.
References _Rule::d, _Rule::n1, _Rule::n2, _Solver::nrules, _Rule::p, _Solver::pool, POOL_DEBUG, rules(), _Solver::rules, solver_printruleelement(), _Rule::w2, and _Pool::whatprovidesdata.
Referenced by makeruledecisions(), propagate(), setpropagatelearn(), solver_addchoicerules(), solver_addrule(), solver_printproblem(), solver_printruleclass(), and solver_solve().
void solver_printruleclass (Solver * solv, int type, Rule * r)
Definition at line 198 of file solverdebug.c.
References _Solver::choicerules, _Solver::choicerules_end, _Solver::duprules, _Solver::duprules_end, _Solver::featurerules, _Solver::featurerules_end, _Solver::infarchrules, _Solver::infarchrules_end, _Solver::jobrules, _Solver::jobrules_end, _Solver::learntrules, MAPTST, _Solver::pool, POOL_DEBUG, _Solver::rules, solver_printrule(), _Solver::updaterules, _Solver::updaterules_end, and _Solver::weakrulemap.
Referenced by analyze(), analyze_unsolvable(), analyze_unsolvable_rule(), enabledisablelearntrules(), makeruledecisions(), reenableduprule(), reenableinfarchrule(), reenableupdaterule(), solver_printdecisionq(), solver_printproblem(), and solver_run_sat().
void solver_printproblem (Solver * solv, Id v)
Definition at line 224 of file solverdebug.c.
References _Queue::elements, _Solver::jobrules, _Solver::jobrules_end, _Solver::pool, POOL_DEBUG, _Solver::rules, _Solver::ruletojob, SAT_DEBUG_SOLUTIONS, solver_printrule(), and solver_printruleclass().
Referenced by refine_suggestion().
void solver_printwatches (Solver * solv, int type)
Definition at line 249 of file solverdebug.c.
References _Pool::nsolvables, _Solver::pool, POOL_DEBUG, and _Solver::watches.
void solver_printdecisionq (Solver * solv, int type)
Definition at line 260 of file solverdebug.c.
References _Queue::count, _Solver::decisionmap, _Solver::decisionq, _Solver::decisionq_why, _Queue::elements, _Solver::pool, POOL_DEBUG, _Solver::rules, solver_printruleclass(), and solvid2str().
Referenced by solver_run_sat().
void solver_printdecisions (Solver * solv)
Definition at line 295 of file solverdebug.c.
References _Queue::count, _Solver::decisionmap, _Solver::decisionq, _Queue::elements, IF_POOLDEBUG, _Solver::installed, _Solver::orphaned, _Solver::pool, POOL_DEBUG, queue_free(), queue_init(), _Solver::recommendations, _Solvable::repo, SAT_DEBUG_RESULT, SAT_DEBUG_SCHUBI, solvable2str(), _Pool::solvables, solver_printruleelement(), SOLVER_TRANSACTION_CHANGE, SOLVER_TRANSACTION_DOWNGRADE, SOLVER_TRANSACTION_ERASE, SOLVER_TRANSACTION_INSTALL, SOLVER_TRANSACTION_MULTIINSTALL, SOLVER_TRANSACTION_MULTIREINSTALL, SOLVER_TRANSACTION_OBSOLETES, SOLVER_TRANSACTION_REINSTALL, SOLVER_TRANSACTION_SHOW_ACTIVE, SOLVER_TRANSACTION_SHOW_ALL, SOLVER_TRANSACTION_SHOW_MULTIINSTALL, SOLVER_TRANSACTION_SHOW_OBSOLETES, SOLVER_TRANSACTION_UPGRADE, solvid2str(), _Transaction::steps, _Solver::suggestions, _Solver::trans, transaction_all_obs_pkgs(), and transaction_type().
Referenced by refine_suggestion(), and solver_run_sat().
void solver_printtransaction (Solver * solv)
Definition at line 444 of file solverdebug.c.
References _Queue::count, _Queue::elements, id2str(), id2strnone(), _Solvable::name, _Transaction::pool, _Solver::pool, POOL_DEBUG, queue_free(), queue_init(), SAT_DEBUG_RESULT, solvable2str(), _Pool::solvables, SOLVER_TRANSACTION_ARCHCHANGE, SOLVER_TRANSACTION_CHANGED, SOLVER_TRANSACTION_DOWNGRADED, SOLVER_TRANSACTION_ERASE, SOLVER_TRANSACTION_IGNORE, SOLVER_TRANSACTION_INSTALL, SOLVER_TRANSACTION_REINSTALLED, SOLVER_TRANSACTION_UPGRADED, SOLVER_TRANSACTION_VENDORCHANGE, _Solver::trans, transaction_classify(), transaction_classify_pkgs(), and transaction_obs_pkg().
void solver_printprobleminfo (Solver * solv, Id problem)
Definition at line 609 of file solverdebug.c.
References solver_findproblemrule(), and solver_printproblemruleinfo().
Referenced by solver_printallsolutions().
void solver_printcompleteprobleminfo (Solver * solv, Id problem)
Definition at line 615 of file solverdebug.c.
References _Queue::count, _Queue::elements, _Solver::jobrules, queue_free(), queue_init(), solver_findallproblemrules(), solver_printproblemruleinfo(), and _Solver::updaterules.
Referenced by solver_printallsolutions().
void solver_printsolution (Solver * solv, Id problem, Id solution)
Definition at line 643 of file solverdebug.c.
References _Queue::elements, id2str(), _Solver::installed, _Solver::job, POLICY_ILLEGAL_ARCHCHANGE, POLICY_ILLEGAL_DOWNGRADE, POLICY_ILLEGAL_VENDORCHANGE, policy_is_illegal(), _Solver::pool, POOL_DEBUG, _Solvable::repo, SAT_DEBUG_RESULT, solvable2str(), _Pool::solvables, SOLVER_ERASE, SOLVER_INSTALL, SOLVER_JOBMASK, SOLVER_LOCK, solver_next_solutionelement(), solver_select2str(), SOLVER_SOLUTION_DISTUPGRADE, SOLVER_SOLUTION_INFARCH, SOLVER_SOLUTION_JOB, SOLVER_SOLVABLE, SOLVER_SOLVABLE_PROVIDES, SOLVER_UPDATE, solvid2str(), and _Solvable::vendor.
Referenced by solver_printallsolutions().
void solver_printallsolutions (Solver * solv)
Definition at line 734 of file solverdebug.c.
References _Solver::pool, POOL_DEBUG, SAT_DEBUG_RESULT, solver_next_problem(), solver_next_solution(), solver_printcompleteprobleminfo(), solver_printprobleminfo(), and solver_printsolution().
void solver_printtrivial (Solver * solv)
Definition at line 764 of file solverdebug.c.
References _Queue::count, _Queue::elements, id2str(), _Solvable::name, _Pool::nsolvables, _Solver::pool, POOL_DEBUG, queue_free(), queue_init(), queue_push(), SAT_DEBUG_RESULT, _Pool::solvables, solver_trivial_installable(), and solvid2str().
const char* solver_select2str (Pool * pool, Id select, Id what)
Definition at line 797 of file solverdebug.c.
References dep2str(), pool_alloctmpspace(), SOLVER_SOLVABLE, SOLVER_SOLVABLE_ALL, SOLVER_SOLVABLE_NAME, SOLVER_SOLVABLE_ONE_OF, SOLVER_SOLVABLE_PROVIDES, SOLVER_SOLVABLE_REPO, solvid2str(), and _Pool::whatprovidesdata.
Referenced by solver_printsolution(), and solver_solve().