satsolver: src/strpool.h File Reference
strpool.h File Reference
#include "pooltypes.h"
#include "hash.h"
Classes
struct _Stringpool
Defines
#define STRID_NULL 0
#define STRID_EMPTY 1
Functions
void stringpool_init (Stringpool *ss, const char *strs[])
void stringpool_init_empty (Stringpool *ss)
void stringpool_clone (Stringpool *ss, Stringpool *from)
void stringpool_free (Stringpool *ss)
void stringpool_freehash (Stringpool *ss)
Id stringpool_str2id (Stringpool *ss, const char *str, int create)
Id stringpool_strn2id (Stringpool *ss, const char *str, unsigned int len, int create)
void stringpool_shrink (Stringpool *ss)
static const char * stringpool_id2str (Stringpool *ss, Id id)
Define Documentation
#define STRID_NULL 0
Definition at line 13 of file strpool.h.
#define STRID_EMPTY 1
Definition at line 14 of file strpool.h.
Function Documentation
void stringpool_init (Stringpool * ss, const char * strs[])
Definition at line 16 of file strpool.c.
References _Stringpool::nstrings, sat_extend_resize(), _Stringpool::sstrings, STRING_BLOCK, _Stringpool::strings, _Stringpool::stringspace, and STRINGSPACE_BLOCK.
Referenced by pool_create(), and stringpool_init_empty().
void stringpool_init_empty (Stringpool * ss)
Definition at line 57 of file strpool.c.
References stringpool_init().
Referenced by repodata_initdata().
void stringpool_clone (Stringpool * ss, Stringpool * from)
Definition at line 68 of file strpool.c.
References _Stringpool::nstrings, sat_extend_resize(), _Stringpool::sstrings, STRING_BLOCK, _Stringpool::strings, _Stringpool::stringspace, and STRINGSPACE_BLOCK.
void stringpool_free (Stringpool * ss)
Definition at line 42 of file strpool.c.
References sat_free(), _Stringpool::stringhashtbl, _Stringpool::strings, and _Stringpool::stringspace.
Referenced by pool_free(), and repodata_freedata().
void stringpool_freehash (Stringpool * ss)
Definition at line 50 of file strpool.c.
References sat_free(), _Stringpool::stringhashmask, and _Stringpool::stringhashtbl.
Referenced by pool_freeidhashes().
Id stringpool_str2id (Stringpool * ss, const char * str, int create)
Definition at line 148 of file strpool.c.
References stringpool_strn2id().
Referenced by repodata_add_poolstr_array(), repodata_set_poolstr(), and str2id().
Id stringpool_strn2id (Stringpool * ss, const char * str, unsigned int len, int create)
Definition at line 80 of file strpool.c.
References HASHCHAIN_NEXT, mkmask(), _Stringpool::nstrings, sat_calloc(), sat_extend(), sat_free(), _Stringpool::sstrings, strhash(), STRING_BLOCK, _Stringpool::stringhashmask, _Stringpool::stringhashtbl, _Stringpool::strings, _Stringpool::stringspace, STRINGSPACE_BLOCK, and strnhash().
Referenced by repodata_str2dir(), stringpool_str2id(), and strn2id().
void stringpool_shrink (Stringpool * ss)
Definition at line 158 of file strpool.c.
References _Stringpool::nstrings, sat_extend_resize(), _Stringpool::sstrings, STRING_BLOCK, _Stringpool::strings, _Stringpool::stringspace, and STRINGSPACE_BLOCK.
Referenced by pool_shrink_strings().
static const char* stringpool_id2str (Stringpool * ss, Id id) [inline, static]
Definition at line 40 of file strpool.h.
References _Stringpool::strings, and _Stringpool::stringspace.
Referenced by repo_add_solv_flags(), repodata_dir2str(), repodata_globalize_id(), repodata_stringify(), and solver_fill_DU_cb().