satsolver: src/transaction.h File Reference
transaction.h File Reference
#include "pooltypes.h"
#include "queue.h"
#include "bitmap.h"
Classes
struct _Transaction
Defines
#define SOLVER_TRANSACTION_IGNORE 0x00
#define SOLVER_TRANSACTION_ERASE 0x10
#define SOLVER_TRANSACTION_REINSTALLED 0x11
#define SOLVER_TRANSACTION_DOWNGRADED 0x12
#define SOLVER_TRANSACTION_CHANGED 0x13
#define SOLVER_TRANSACTION_UPGRADED 0x14
#define SOLVER_TRANSACTION_OBSOLETED 0x15
#define SOLVER_TRANSACTION_INSTALL 0x20
#define SOLVER_TRANSACTION_REINSTALL 0x21
#define SOLVER_TRANSACTION_DOWNGRADE 0x22
#define SOLVER_TRANSACTION_CHANGE 0x23
#define SOLVER_TRANSACTION_UPGRADE 0x24
#define SOLVER_TRANSACTION_OBSOLETES 0x25
#define SOLVER_TRANSACTION_MULTIINSTALL 0x30
#define SOLVER_TRANSACTION_MULTIREINSTALL 0x31
#define SOLVER_TRANSACTION_MAXTYPE 0x3f
#define SOLVER_TRANSACTION_SHOW_ACTIVE (1 << 0)
#define SOLVER_TRANSACTION_SHOW_ALL (1 << 1)
#define SOLVER_TRANSACTION_SHOW_OBSOLETES (1 << 2)
#define SOLVER_TRANSACTION_SHOW_MULTIINSTALL (1 << 3)
#define SOLVER_TRANSACTION_CHANGE_IS_REINSTALL (1 << 4)
#define SOLVER_TRANSACTION_MERGE_VENDORCHANGES (1 << 5)
#define SOLVER_TRANSACTION_MERGE_ARCHCHANGES (1 << 6)
#define SOLVER_TRANSACTION_RPM_ONLY (1 << 7)
#define SOLVER_TRANSACTION_ARCHCHANGE 0x100
#define SOLVER_TRANSACTION_VENDORCHANGE 0x101
#define SOLVER_TRANSACTION_KEEP_ORDERDATA (1 << 0)
Typedefs
typedef struct _Transaction Transaction
Functions
void transaction_init (Transaction *trans, struct _Pool *pool)
void transaction_init_clone (Transaction *trans, Transaction *srctrans)
void transaction_free (Transaction *trans)
void transaction_free_orderdata (Transaction *trans)
void transaction_calculate (Transaction *trans, Queue *decisionq, Map *noobsmap)
Id transaction_obs_pkg (Transaction *trans, Id p)
void transaction_all_obs_pkgs (Transaction *trans, Id p, Queue *pkgs)
Id transaction_type (Transaction *trans, Id p, int mode)
void transaction_classify (Transaction *trans, int mode, Queue *classes)
void transaction_classify_pkgs (Transaction *trans, int mode, Id type, Id from, Id to, Queue *pkgs)
int transaction_installedresult (Transaction *trans, Queue *installedq)
int transaction_calc_installsizechange (Transaction *trans)
void transaction_calc_duchanges (Transaction *trans, struct _DUChanges *mps, int nmps)
void transaction_order (Transaction *trans, int flags)
int transaction_order_add_choices (Transaction *trans, Id chosen, Queue *choices)
void transaction_add_obsoleted (Transaction *trans)
void transaction_check_order (Transaction *trans)
Define Documentation
#define SOLVER_TRANSACTION_IGNORE 0x00
Definition at line 44 of file transaction.h.
Referenced by solver_printtransaction(), and transaction_type().
#define SOLVER_TRANSACTION_ERASE 0x10
Definition at line 46 of file transaction.h.
Referenced by solver_printdecisions(), solver_printtransaction(), transaction_classify(), and transaction_type().
#define SOLVER_TRANSACTION_REINSTALLED 0x11
Definition at line 47 of file transaction.h.
Referenced by solver_printtransaction().
#define SOLVER_TRANSACTION_DOWNGRADED 0x12
Definition at line 48 of file transaction.h.
Referenced by solver_printtransaction().
#define SOLVER_TRANSACTION_CHANGED 0x13
Definition at line 49 of file transaction.h.
Referenced by solver_printtransaction(), and transaction_type().
#define SOLVER_TRANSACTION_UPGRADED 0x14
Definition at line 50 of file transaction.h.
Referenced by solver_printtransaction().
#define SOLVER_TRANSACTION_OBSOLETED 0x15
Definition at line 51 of file transaction.h.
Referenced by transaction_type().
#define SOLVER_TRANSACTION_INSTALL 0x20
Definition at line 53 of file transaction.h.
Referenced by solver_printdecisions(), solver_printtransaction(), and transaction_type().
#define SOLVER_TRANSACTION_REINSTALL 0x21
Definition at line 54 of file transaction.h.
Referenced by solver_printdecisions().
#define SOLVER_TRANSACTION_DOWNGRADE 0x22
Definition at line 55 of file transaction.h.
Referenced by solver_printdecisions().
#define SOLVER_TRANSACTION_CHANGE 0x23
Definition at line 56 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_UPGRADE 0x24
Definition at line 57 of file transaction.h.
Referenced by solver_printdecisions().
#define SOLVER_TRANSACTION_OBSOLETES 0x25
Definition at line 58 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_MULTIINSTALL 0x30
Definition at line 60 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_MULTIREINSTALL 0x31
Definition at line 61 of file transaction.h.
Referenced by solver_printdecisions(), transaction_base_type(), and transaction_type().
#define SOLVER_TRANSACTION_MAXTYPE 0x3f
Definition at line 63 of file transaction.h.
Referenced by transaction_classify(), and transaction_classify_pkgs().
#define SOLVER_TRANSACTION_SHOW_ACTIVE (1 << 0)
Definition at line 66 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_SHOW_ALL (1 << 1)
Definition at line 67 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_SHOW_OBSOLETES (1 << 2)
Definition at line 68 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_SHOW_MULTIINSTALL (1 << 3)
Definition at line 69 of file transaction.h.
Referenced by solver_printdecisions(), and transaction_type().
#define SOLVER_TRANSACTION_CHANGE_IS_REINSTALL (1 << 4)
Definition at line 70 of file transaction.h.
Referenced by transaction_type().
#define SOLVER_TRANSACTION_MERGE_VENDORCHANGES (1 << 5)
Definition at line 71 of file transaction.h.
Referenced by transaction_classify().
#define SOLVER_TRANSACTION_MERGE_ARCHCHANGES (1 << 6)
Definition at line 72 of file transaction.h.
Referenced by transaction_classify().
#define SOLVER_TRANSACTION_RPM_ONLY (1 << 7)
Definition at line 74 of file transaction.h.
Referenced by transaction_type().
#define SOLVER_TRANSACTION_ARCHCHANGE 0x100
Definition at line 77 of file transaction.h.
Referenced by solver_printtransaction(), transaction_classify(), and transaction_classify_pkgs().
#define SOLVER_TRANSACTION_VENDORCHANGE 0x101
Definition at line 78 of file transaction.h.
Referenced by solver_printtransaction(), transaction_classify(), and transaction_classify_pkgs().
#define SOLVER_TRANSACTION_KEEP_ORDERDATA (1 << 0)
Definition at line 81 of file transaction.h.
Referenced by transaction_order().
Typedef Documentation
typedef struct _Transaction Transaction
Function Documentation
void transaction_init (Transaction * trans, struct _Pool * pool)
Definition at line 792 of file transaction.c.
References _Transaction::pool.
Referenced by solver_create().
void transaction_init_clone (Transaction * trans, Transaction * srctrans)
Definition at line 799 of file transaction.c.
References _Repo::end, _Pool::installed, _TransactionOrderdata::invedgedata, map_init_clone(), _TransactionOrderdata::ninvedgedata, _Transaction::noobsmap, _TransactionOrderdata::ntes, _Transaction::orderdata, _Transaction::pool, queue_init_clone(), sat_calloc(), sat_malloc2(), _Repo::start, _Transaction::steps, _TransactionOrderdata::tes, _Transaction::transaction_info, _Transaction::transaction_installed, and _Transaction::transactsmap.
void transaction_free (Transaction * trans)
Definition at line 827 of file transaction.c.
References map_free(), _Transaction::noobsmap, queue_free(), sat_free(), _Transaction::steps, transaction_free_orderdata(), _Transaction::transaction_info, _Transaction::transaction_installed, and _Transaction::transactsmap.
Referenced by solver_free().
void transaction_free_orderdata (Transaction * trans)
Definition at line 838 of file transaction.c.
References _TransactionOrderdata::invedgedata, _Transaction::orderdata, sat_free(), and _TransactionOrderdata::tes.
Referenced by transaction_free().
void transaction_calculate (Transaction * trans, Queue * decisionq, Map * noobsmap)
Definition at line 631 of file transaction.c.
References _Queue::count, create_transaction_info(), _Queue::elements, FOR_REPO_SOLVABLES, id2str(), _Pool::installed, map_init(), map_init_clone(), MAPCLR, MAPSET, MAPTST, _Solvable::name, _Transaction::noobsmap, _Pool::nsolvables, _Transaction::pool, queue_empty(), queue_push(), _Solvable::repo, _Map::size, _Pool::solvables, _Transaction::steps, SYSTEMSOLVABLE, and _Transaction::transactsmap.
Referenced by solver_solve().
Id transaction_obs_pkg (Transaction * trans, Id p)
Definition at line 111 of file transaction.c.
References _Queue::count, _Queue::elements, _Pool::installed, _Transaction::pool, queue_free(), queue_init_buffer(), _Solvable::repo, _Pool::solvables, _Repo::start, transaction_all_obs_pkgs(), and _Transaction::transaction_installed.
Referenced by solver_printtransaction(), transaction_base_type(), transaction_classify(), transaction_classify_pkgs(), and transaction_type().
void transaction_all_obs_pkgs (Transaction * trans, Id p, Queue * pkgs)
Definition at line 62 of file transaction.c.
References _Queue::count, _Queue::elements, _Pool::installed, obsq_sortcmp(), _Transaction::pool, queue_empty(), queue_push(), _Solvable::repo, sat_sort(), _Pool::solvables, _Repo::start, _Transaction::transaction_info, and _Transaction::transaction_installed.
Referenced by addedge(), dump_tes(), havechoice(), solver_printdecisions(), transaction_add_obsoleted(), transaction_obs_pkg(), and transaction_type().
Id transaction_type (Transaction * trans, Id p, int mode)
Definition at line 201 of file transaction.c.
References _Queue::count, _Queue::elements, id2str(), _Pool::installed, _Solvable::name, _Transaction::pool, queue_free(), queue_init(), _Solvable::repo, _Pool::solvables, SOLVER_TRANSACTION_CHANGE, SOLVER_TRANSACTION_CHANGE_IS_REINSTALL, SOLVER_TRANSACTION_CHANGED, SOLVER_TRANSACTION_ERASE, SOLVER_TRANSACTION_IGNORE, SOLVER_TRANSACTION_INSTALL, SOLVER_TRANSACTION_MULTIINSTALL, SOLVER_TRANSACTION_MULTIREINSTALL, SOLVER_TRANSACTION_OBSOLETED, SOLVER_TRANSACTION_OBSOLETES, SOLVER_TRANSACTION_RPM_ONLY, SOLVER_TRANSACTION_SHOW_ACTIVE, SOLVER_TRANSACTION_SHOW_ALL, SOLVER_TRANSACTION_SHOW_MULTIINSTALL, SOLVER_TRANSACTION_SHOW_OBSOLETES, transaction_all_obs_pkgs(), transaction_base_type(), and transaction_obs_pkg().
Referenced by solver_printdecisions(), transaction_classify(), and transaction_classify_pkgs().
void transaction_classify (Transaction * trans, int mode, Queue * classes)
Definition at line 402 of file transaction.c.
References _Solvable::arch, classify_cmp(), _Queue::count, _Queue::elements, _Pool::installed, _Transaction::pool, queue_empty(), queue_push(), queue_unshift(), _Solvable::repo, sat_sort(), _Pool::solvables, SOLVER_TRANSACTION_ARCHCHANGE, SOLVER_TRANSACTION_ERASE, SOLVER_TRANSACTION_MAXTYPE, SOLVER_TRANSACTION_MERGE_ARCHCHANGES, SOLVER_TRANSACTION_MERGE_VENDORCHANGES, SOLVER_TRANSACTION_VENDORCHANGE, _Transaction::steps, transaction_obs_pkg(), transaction_type(), and _Solvable::vendor.
Referenced by solver_printtransaction().
void transaction_classify_pkgs (Transaction * trans, int mode, Id type, Id from, Id to, Queue * pkgs)
Definition at line 493 of file transaction.c.
References _Solvable::arch, classify_cmp_pkgs(), _Queue::count, _Queue::elements, _Pool::installed, _Transaction::pool, queue_empty(), queue_push(), _Solvable::repo, sat_sort(), _Pool::solvables, SOLVER_TRANSACTION_ARCHCHANGE, SOLVER_TRANSACTION_MAXTYPE, SOLVER_TRANSACTION_VENDORCHANGE, _Transaction::steps, transaction_obs_pkg(), transaction_type(), and _Solvable::vendor.
Referenced by solver_printtransaction().
int transaction_installedresult (Transaction * trans, Queue * installedq)
Definition at line 689 of file transaction.c.
References _Queue::count, _Queue::elements, FOR_REPO_SOLVABLES, _Pool::installed, MAPTST, _Transaction::pool, queue_empty(), queue_push(), _Solvable::repo, _Pool::solvables, _Transaction::steps, and _Transaction::transactsmap.
int transaction_calc_installsizechange (Transaction * trans)
Definition at line 743 of file transaction.c.
References map_free(), _Transaction::pool, pool_calc_installsizechange(), and transaction_create_installedmap().
void transaction_calc_duchanges (Transaction * trans, struct _DUChanges * mps, int nmps)
Definition at line 755 of file transaction.c.
References map_free(), _Transaction::pool, pool_calc_duchanges(), and transaction_create_installedmap().
void transaction_order (Transaction * trans, int flags)
Definition at line 1536 of file transaction.c.
References addcycleedges(), addsolvableedges(), breakcycle(), _Queue::count, orderdata::cycles, orderdata::cyclesdata, dump_tes(), orderdata::edgedata, EDGEDATA_BLOCK, _TransactionElement::edges, _Queue::elements, _Pool::installed, orderdata::invedgedata, _TransactionOrderdata::invedgedata, _TransactionElement::mark, orderdata::ncycles, orderdata::nedgedata, _TransactionOrderdata::ninvedgedata, _TransactionOrderdata::ntes, orderdata::ntes, _Transaction::orderdata, _TransactionElement::p, _Transaction::pool, POOL_DEBUG, queue_empty(), queue_free(), queue_init(), queue_pop(), queue_push(), queue_shift(), _Solvable::repo, sat_calloc(), SAT_DEBUG_STATS, sat_extend(), sat_free(), sat_timems(), solvable_lookup_num(), _Pool::solvables, SOLVER_TRANSACTION_KEEP_ORDERDATA, solvid2str(), _Repo::start, _Transaction::steps, orderdata::tes, _TransactionOrderdata::tes, orderdata::trans, transaction_add_obsoleted(), _Transaction::transaction_installed, TYPE_BROKEN, and TYPE_REQ.
int transaction_order_add_choices (Transaction * trans, Id chosen, Queue * choices)
Definition at line 1883 of file transaction.c.
References _Queue::count, _TransactionElement::edges, _TransactionOrderdata::invedgedata, _TransactionElement::mark, _TransactionOrderdata::ntes, _Transaction::orderdata, _TransactionElement::p, queue_push(), and _TransactionOrderdata::tes.
void transaction_add_obsoleted (Transaction * trans)
Definition at line 1927 of file transaction.c.
References _Queue::count, _Queue::elements, _Repo::end, FOR_REPO_SOLVABLES, _Pool::installed, map_free(), map_init(), MAPSET, MAPTST, _TransactionElement::p, _Transaction::pool, queue_empty(), queue_free(), queue_init(), queue_insertn(), queue_truncate(), _Solvable::repo, _Pool::solvables, _Repo::start, _Transaction::steps, transaction_all_obs_pkgs(), _Transaction::transaction_installed, and _Transaction::transactsmap.
Referenced by transaction_order().
void transaction_check_order (Transaction * trans)
Definition at line 2056 of file transaction.c.
References _Queue::count, _Queue::elements, FOR_REPO_SOLVABLES, havescripts(), _Pool::installed, map_free(), map_init(), MAPCLR, MAPSET, MAPZERO, _Pool::nsolvables, _TransactionElement::p, _Transaction::pool, POOL_DEBUG, _Solvable::repo, SAT_WARN, _Pool::solvables, _Transaction::steps, and transaction_check_pkg().