satsolver: src/util.c File Reference
util.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/time.h>
#include "util.h"
Defines
#define _GNU_SOURCE
Functions
void sat_oom (size_t num, size_t len)
void * sat_malloc (size_t len)
malloc exits with error message on error
void * sat_malloc2 (size_t num, size_t len)
void * sat_realloc (void *old, size_t len)
void * sat_realloc2 (void *old, size_t num, size_t len)
void * sat_calloc (size_t num, size_t len)
void * sat_free (void *mem)
unsigned int sat_timems (unsigned int subtract)
void sat_sort (void *base, size_t nmemb, size_t size, int(*compar)(const void *, const void *, void *), void *compard)
char * sat_dupjoin (const char *str1, const char *str2, const char *str3)
Define Documentation
#define _GNU_SOURCE
Definition at line 8 of file util.c.
Function Documentation
void sat_oom (size_t num, size_t len)
Definition at line 19 of file util.c.
Referenced by sat_calloc(), sat_malloc(), sat_malloc2(), sat_realloc(), and sat_realloc2().
void* sat_malloc (size_t len)
malloc exits with error message on error
Definition at line 30 of file util.c.
References sat_oom().
Referenced by map_init_clone(), pool_addfileprovides_dep(), pool_id2langid(), repo_add_solv_flags(), sat_dupjoin(), and sat_malloc2().
void* sat_malloc2 (size_t num, size_t len)
Definition at line 39 of file util.c.
References sat_malloc(), and sat_oom().
Referenced by pool_shrink_whatprovides(), queue_alloc_one(), queue_init_clone(), repo_add_solv_flags(), repodata_internalize(), repopagestore_read_or_setup_pages(), sat_calloc_block(), and transaction_init_clone().
void* sat_realloc (void * old, size_t len)
Definition at line 47 of file util.c.
References sat_oom().
Referenced by incore_add_blob(), incore_add_id(), incore_add_u32(), map_grow(), pool_alloctmpspace(), pool_queuetowhatprovides(), pool_setarch(), pool_shrink_whatprovides(), repo_add_solv_flags(), sat_realloc2(), str2id(), and strn2id().
void* sat_realloc2 (void * old, size_t num, size_t len)
Definition at line 59 of file util.c.
References sat_oom(), and sat_realloc().
Referenced by pool_addfileprovides_search(), queue_alloc_one(), queue_insertn(), rel2id(), repo_add_solv_flags(), repo_create(), repodata_create(), repodata_free_schemahash(), repodata_key2id(), repopagestore_load_page_range(), sat_extend(), sat_extend_resize(), and solvable_lookup_str_poollang().
void* sat_calloc (size_t num, size_t len)
Definition at line 67 of file util.c.
References sat_oom().
Referenced by create_transaction_info(), datamatcher_init(), makewatches(), map_init(), policy_create_obsolete_index(), pool_arch2color_slow(), pool_create(), pool_createwhatprovides(), pool_set_languages(), pool_setarch(), pool_trivial_installable_noobsoletesmap(), rel2id(), repo_add_solv_flags(), repo_create(), repodata_create_stubs(), repodata_initdata(), repodata_internalize(), repodata_schema2id(), sat_chksum_create(), solvable_lookup_str_poollang(), solver_addchoicerules(), solver_addupdaterule(), solver_create(), solver_create_decisions_obsoletesmap(), solver_fill_DU_cb(), stringpool_strn2id(), transaction_init_clone(), and transaction_order().
void* sat_free (void * mem)
Definition at line 80 of file util.c.
Referenced by create_transaction_info(), datamatcher_free(), datamatcher_init(), dirpool_free(), dirpool_free_dirtraverse(), makewatches(), map_free(), pool_addfileprovides_ids(), pool_calc_duchanges(), pool_free(), pool_freeidhashes(), pool_freewhatprovides(), pool_set_languages(), pool_setarch(), pool_shrink_whatprovides(), queue_free(), rel2id(), repo_add_solv_flags(), repo_empty(), repo_freeallrepos(), repo_freedata(), repodata_create_stubs(), repodata_free_schemahash(), repodata_freedata(), repodata_internalize(), repodata_shrink(), repopagestore_free(), sat_chksum_free(), solver_fill_DU_cb(), solver_free(), stringpool_free(), stringpool_freehash(), stringpool_strn2id(), transaction_free(), transaction_free_orderdata(), and transaction_order().
unsigned int sat_timems (unsigned int subtract)
Definition at line 88 of file util.c.
Referenced by create_solutions(), pool_addfileprovides_ids(), pool_createwhatprovides(), repo_add_solv_flags(), solver_solve(), and transaction_order().
void sat_sort (void * base, size_t nmemb, size_t size, int(*)(const void *, const void *, void *) compar, void * compard)
Definition at line 107 of file util.c.
Referenced by create_solutions(), create_transaction_info(), pool_shrink_whatprovides(), prune_to_best_version(), prune_to_highest_prio_per_name(), solver_allruleinfos(), solver_unifyrules(), transaction_all_obs_pkgs(), transaction_classify(), and transaction_classify_pkgs().
char* sat_dupjoin (const char * str1, const char * str2, const char * str3)
Definition at line 122 of file util.c.
References sat_malloc().